#!/usr/bin/env python3
"""
NoBASIC Compiler for Nova-16

Compiles NoBASIC source code to Nova-16 assembly language.

This compiler translates NoBASIC programs (inspired by TI-83/84 calculators)
into optimized Nova-16 assembly code for native execution.
"""

import sys
import os
import re
from typing import Dict, List, Tuple, Optional, Set
from pathlib import Path

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from nova_cpu import CPU
from nova_memory import Memory
from nova_gfx import GFX
from nova_keyboard import NovaKeyboard
from nova_sound import NovaSound


class NoBasicCompiler:
    """
    Compiles NoBASIC source code to Nova-16 assembly.
    """

    def __init__(self):
        # Initialize Nova-16 components for reference
        self.memory = Memory(0x10000)
        self.gfx = GFX()
        self.keyboard = NovaKeyboard()
        self.sound = NovaSound()
        self.sound.set_memory_reference(self.memory)
        self.cpu = CPU(self.memory, self.gfx, self.keyboard, self.sound)

        # Memory layout for compiled NoBASIC
        self.PROGRAM_START = 0x1000
        self.VARIABLE_START = 0x2000  # Variables A-Z
        self.LIST_START = 0x3000     # Lists L1-L6 (each 100 elements × 2 bytes)
        self.STRING_START = 0x4000   # Strings Str1-Str9
        self.MATRIX_START = 0x5000   # Matrices [A]-[J]
        self.TEMP_START = 0x6000     # Temporary storage
        self.STACK_START = 0xF000    # Parameter stack (grows downward)

        # List management
        self.lists: Dict[str, int] = {}  # List name -> memory address
        self.list_sizes: Dict[str, int] = {}  # List name -> size

        # Compilation state
        self.assembly_lines: List[str] = []
        self.variables: Dict[str, int] = {}  # Variable name -> memory address
        self.labels: Dict[str, str] = {}     # Label name -> assembly label
        self.label_counter = 0
        self.string_counter = 0
        self.strings: Dict[str, int] = {}    # String content -> memory address
        
        # Register allocation for expression evaluation
        self.available_registers = ["P0", "P1", "P2", "P3", "P4", "P5", "P6", "P7"]
        self.register_stack: List[str] = []
        
        # Text cursor position for display statements
        self.cursor_x = 0
        self.cursor_y = 0

        # Initialize standard header
        self._init_assembly()

    def _init_assembly(self):
        """Initialize the assembly output with standard header"""
        self.assembly_lines = [
            "; NoBASIC Program - Generated by nobasic_compiler.py",
            "; Generated automatically - do not edit",
            "",
            "ORG 0x1000",
            "",
            "; Initialize stack pointer",
            "MOV P8,0xF000",
            "",
            "; Initialize text cursor position",
            "MOV VX,0",      # X position
            "MOV VY,0",      # Y position
            "MOV VL,0",      # Layer 0
            "",
            "; Program start",
            "start:",
        ]

    def _parse_tokens_for_expression(self, tokens: List[str]) -> Tuple[List[str], int]:
        """Parse a subset of tokens as an expression (helper for list indexing)"""
        # Simple implementation - just parse additive expression
        return self._parse_additive_expression(tokens, 0)

    def _allocate_register(self) -> str:
        """Allocate a register for expression evaluation"""
        if self.available_registers:
            reg = self.available_registers.pop(0)
            self.register_stack.append(reg)
            return reg
        # If no registers available, use stack as fallback
        return "P0"

    def _free_register(self, reg: str):
        """Free a register back to the pool"""
        if reg in self.register_stack:
            self.register_stack.remove(reg)
            if reg not in self.available_registers:
                self.available_registers.insert(0, reg)

    def _get_current_register(self) -> str:
        """Get the current result register"""
        return self.register_stack[-1] if self.register_stack else "P0"

    def _generate_label(self, prefix: str = "label") -> str:
        """Generate a unique label"""
        self.label_counter += 1
        return f"{prefix}_{self.label_counter}"

    def _tokenize(self, source: str) -> List[str]:
        """Tokenize NoBASIC source code"""
        # Split on whitespace and special characters, preserving newlines
        tokens = re.findall(r'[A-Za-z_][A-Za-z0-9_]*|:=|<=|>=|<>|[0-9]+(?:\.[0-9]+)?|"[^"]*"|\n|\S', source)

        # Filter out empty tokens
        filtered_tokens = []
        for token in tokens:
            if token:  # Keep all non-empty tokens including \n
                filtered_tokens.append(token)

        return filtered_tokens

    def _parse_tokens(self, tokens: List[str]):
        """Parse tokens and generate assembly"""
        i = 0
        while i < len(tokens):
            token = tokens[i].upper()

            # Only check for keywords at the start of statements (after newline or at beginning)
            is_statement_start = (i == 0 or tokens[i-1] == '\n')

            if is_statement_start:
                if token == "CLRHOME":
                    lines = self._compile_clrhome()
                    self.assembly_lines.extend(lines)
                    i += 1

                elif token == "DISP":
                    lines, new_i = self._compile_disp(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "FOR":
                    lines, new_i = self._compile_for(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "IF":
                    lines, new_i = self._compile_if(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "INPUT":
                    lines, new_i = self._compile_input(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "PROMPT":
                    lines, new_i = self._compile_prompt(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "WHILE":
                    lines, new_i = self._compile_while(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "WEND":
                    lines = self._compile_wend()
                    self.assembly_lines.extend(lines)
                    i += 1

                elif token == "PAUSE":
                    lines = self._compile_pause()
                    self.assembly_lines.extend(lines)
                    i += 1

                elif token == "END":
                    lines = self._compile_end()
                    self.assembly_lines.extend(lines)
                    i += 1

                elif token == "GOTO":
                    lines, new_i = self._compile_goto(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "LBL":
                    lines, new_i = self._compile_lbl(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif ((token.isalpha() or (token.upper().startswith('L') and len(token) == 2 and token[1].isdigit())) and i + 1 < len(tokens) and 
                      (tokens[i + 1] == "=" or tokens[i + 1] == "(")):
                    # Variable or list assignment
                    lines, new_i = self._compile_assignment(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == '\n':
                    i += 1
                    continue

                else:
                    # Skip unknown tokens at statement start
                    i += 1
            else:
                # Not at statement start, skip this token
                i += 1

        # Add program end with infinite loop to keep display visible
        self.assembly_lines.extend([
            "",
            "; Program end - infinite loop to keep display visible",
            "halt:",
            "JMP halt",
        ])

        # Add variable declarations
        for var_name, addr in self.variables.items():
            self.assembly_lines.extend([
                f"ORG 0x{addr:04X}",
                f"DW 0  ; Variable {var_name}",
            ])

        # Add string declarations
        for string_content, addr in self.strings.items():
            self.assembly_lines.extend([
                f"ORG 0x{addr:04X}",
            ])
            # Add string bytes
            for char in string_content:
                self.assembly_lines.append(f"DB {ord(char)}")
            self.assembly_lines.append("DB 0  ; Null terminator")

        # Add final ORG back to program area
        self.assembly_lines.extend([
            "",
            "ORG 0x1000",
        ])

    def _compile_clrhome(self) -> List[str]:
        """Compile ClrHome statement"""
        return [
            "    ; ClrHome",
            "    MOV P0,0",
            "    MOV [0xF102],P0",  # VM = 0 (coordinate mode)
            "    MOV [0xF103],P0",  # VL = 0 (layer 0)
            "    MOV [0xF100],P0",  # VX = 0
            "    MOV [0xF101],P0",  # VY = 0
            "    SFILL P0",         # Fill screen with black
        ]

    def _compile_disp(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile Disp statement"""
        lines = ["    ; Disp"]
        i += 1  # Skip DISP

        # Set cursor to current position
        lines.extend([
            f"    MOV P0,{self.cursor_x}",
            "    MOV [0xF100],P0",  # VX
            f"    MOV P0,{self.cursor_y}",
            "    MOV [0xF101],P0",  # VY
            "    MOV P0,0",
            "    MOV [0xF103],P0",  # VL
        ])

        # Parse display arguments
        while i < len(tokens):
            token = tokens[i]

            if token == '\n':
                i += 1
                break

            if token.startswith('"'):
                # String literal
                string_content = token.strip('"')
                lines.extend(self._compile_display_string(string_content))
            elif token.isdigit() or token.isalpha():
                # Variable or number
                if token.isalpha():
                    # Variable
                    lines.extend(self._load_variable(token))
                else:
                    # Number
                    value = int(token)
                    lines.extend([
                        f"    MOV P0,{value}",
                    ])
                lines.extend(self._compile_display_value())
            elif token == ',':
                # New line
                lines.extend([
                    "    MOV P0,[0xF101]",  # Get current VY
                    "    ADD P0,8",
                    "    MOV [0xF101],P0",  # Set new VY
                    "    MOV P0,0",
                    "    MOV [0xF100],P0",  # Reset VX
                ])
                self.cursor_y += 8  # Update cursor position for next item in same Disp

            i += 1

        # Advance cursor to next line for next Disp statement
        self.cursor_y += 8
        if self.cursor_y >= 256:  # Wrap around if we reach bottom
            self.cursor_y = 0
        self.cursor_x = 0  # Reset X for next line

        return lines, i

    def _compile_for(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile For loop"""
        lines = []
        i += 1  # Skip FOR

        # Parse: FOR variable = start TO end
        if i < len(tokens):
            var_name = tokens[i]
            i += 2  # Skip variable and =

            start_value = tokens[i]
            i += 2  # Skip start and TO

            end_value = tokens[i]
            i += 1  # Skip end

            # Generate labels
            loop_label = self._generate_label("for_loop")
            end_label = self._generate_label("for_end")

            # Initialize loop variable
            var_addr = self._get_variable_address(var_name)
            lines.extend([
                f"    ; For {var_name} = {start_value} To {end_value}",
                f"    MOV P0,{start_value}",
                f"    MOV [0x{var_addr:04X}],P0",
                f"{loop_label}:",
            ])

            # Store loop info for END
            self.labels[f"end_{var_name}"] = end_label

        return lines, i

    def _compile_if(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile If statement"""
        lines = []
        i += 1  # Skip IF

        # Parse condition
        condition_lines, i = self._parse_condition(tokens, i)

        # Generate labels
        else_label = self._generate_label("if_else")
        end_label = self._generate_label("if_end")

        lines.extend(condition_lines)
        lines.extend([
            f"    JZ {else_label}",
            f"{else_label}:",
        ])

        # Skip THEN
        if i < len(tokens) and tokens[i].upper() == "THEN":
            i += 1

        return lines, i

    def _compile_input(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile Input statement"""
        lines = ["    ; Input"]
        i += 1  # Skip INPUT

        if i < len(tokens):
            var_name = tokens[i]
            var_addr = self._get_variable_address(var_name)

            lines.extend([
                f"    ; Input {var_name}",
                "    CALL read_number",
            ])
            lines.extend(self._store_variable(var_name))
            i += 1

        return lines, i

    def _compile_prompt(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile Prompt statement"""
        lines = ["    ; Prompt"]
        i += 1  # Skip PROMPT

        if i < len(tokens):
            var_name = tokens[i]
            var_addr = self._get_variable_address(var_name)

            lines.extend([
                f"    ; Prompt {var_name}",
                "    CALL read_number",
            ])
            lines.extend(self._store_variable(var_name))
            i += 1

        return lines, i

    def _compile_while(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile While loop"""
        lines = []
        i += 1  # Skip WHILE

        # Generate labels
        loop_label = self._generate_label("while_loop")
        end_label = self._generate_label("while_end")

        lines.extend([
            f"    ; While loop",
            f"{loop_label}:",
        ])

        # Parse condition
        condition_lines, i = self._parse_condition(tokens, i)
        lines.extend(condition_lines)
        lines.extend([
            f"    JZ {end_label}",
        ])

        # Store end label for WEND
        self.labels["current_while_end"] = end_label
        self.labels["current_while_loop"] = loop_label

        return lines, i

    def _compile_wend(self) -> List[str]:
        """Compile WEnd statement"""
        end_label = self.labels.get("current_while_end", "while_end")
        loop_label = self.labels.get("current_while_loop", "while_loop")

        return [
            f"    JMP {loop_label}",
            f"{end_label}:",
        ]

    def _compile_assignment(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile variable or list assignment with optimizations"""
        target_name = tokens[i]
        i += 1  # Skip target name
        
        # Check if this is a list assignment (L1(index) = ...)
        is_list_assignment = False
        list_name = ""
        index_tokens = []
        
        if tokens[i] == '(':
            # This is a list assignment
            is_list_assignment = True
            list_name = target_name.upper()
            i += 1  # Skip '('
            
            # Collect index tokens until ')'
            paren_count = 1
            while i < len(tokens) and paren_count > 0:
                if tokens[i] == '(':
                    paren_count += 1
                elif tokens[i] == ')':
                    paren_count -= 1
                    if paren_count == 0:
                        break
                index_tokens.append(tokens[i])
                i += 1
            i += 1  # Skip ')'
        
        if tokens[i] != '=':
            raise ValueError("Expected '=' in assignment")
        i += 1  # Skip '='

        lines = [f"    ; {target_name} = "]
        
        # Parse the value expression
        expr_lines, i = self._parse_expression(tokens, i)
        lines.extend(expr_lines)
        
        if is_list_assignment:
            # For now, simple list assignment: assume index is a constant
            # TODO: Handle complex index expressions
            if len(index_tokens) == 1 and index_tokens[0].isdigit():
                index = int(index_tokens[0])
                list_addr = self._get_list_address(list_name)
                
                value_reg = self._get_current_register()
                
                lines.extend([
                    f"    ; Store to {list_name}({index})",
                    f"    MOV [0x{list_addr + index * 2:04X}],{value_reg}",  # Direct address calculation
                ])
            else:
                raise ValueError(f"Complex list indices not yet supported: {index_tokens}")
        else:
            # Regular variable assignment
            var_addr = self._get_variable_address(target_name)
            result_reg = self._get_current_register()
            lines.extend(self._store_variable_from_reg(target_name, result_reg))
        
        # Free the result register
        result_reg = self._get_current_register()
        self._free_register(result_reg)
        
        return lines, i

    def _parse_condition(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Parse a condition for IF/WHILE"""
        lines = []

        # Simple comparison for now: var op value
        left = tokens[i]
        i += 1
        op = tokens[i]
        i += 1
        right = tokens[i]
        i += 1

        # Load left side
        if left.isalpha():
            left_reg = self._allocate_register()
            lines.extend(self._load_variable_to_reg(left, left_reg))
        else:
            left_reg = self._allocate_register()
            lines.append(f"    MOV {left_reg},{left}")

        # Compare with right side
        if right.isalpha():
            right_reg = self._allocate_register()
            lines.extend(self._load_variable_to_reg(right, right_reg))
            lines.append(f"    CMP {left_reg},{right_reg}")
            self._free_register(right_reg)
        else:
            lines.append(f"    CMP {left_reg},{right}")

        self._free_register(left_reg)

        return lines, i

    def _parse_expression(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Parse an arithmetic expression with proper precedence"""
        return self._parse_additive_expression(tokens, i)

    def _parse_additive_expression(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Parse additive expressions (+, -) - lowest precedence"""
        lines, i = self._parse_multiplicative_expression(tokens, i)

        while i < len(tokens) and tokens[i] in ['+', '-']:
            op = tokens[i]
            i += 1

            # Save current result register
            left_reg = self._get_current_register()
            
            # Allocate new register for right operand
            right_reg = self._allocate_register()

            # Parse right operand
            right_lines, i = self._parse_multiplicative_expression(tokens, i)
            lines.extend(right_lines)

            # Perform operation
            if op == '+':
                lines.append(f"    ADD {left_reg},{right_reg}")
            else:  # op == '-'
                lines.append(f"    SUB {left_reg},{right_reg}")

            # Free the right register
            self._free_register(right_reg)

        return lines, i

    def _parse_multiplicative_expression(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Parse multiplicative expressions (*, /, MOD)"""
        lines, i = self._parse_primary_expression(tokens, i)

        while i < len(tokens) and tokens[i] in ['*', '/', 'MOD']:
            op = tokens[i]
            i += 1

            # Save current result register
            left_reg = self._get_current_register()
            
            # Allocate new register for right operand
            right_reg = self._allocate_register()

            # Parse right operand
            right_lines, i = self._parse_primary_expression(tokens, i)
            lines.extend(right_lines)

            # Perform operation
            if op == '*':
                lines.append(f"    MUL {left_reg},{right_reg}")
            elif op == '/':
                lines.append(f"    DIV {left_reg},{right_reg}")
            else:  # op == 'MOD'
                lines.append(f"    MOD {left_reg},{right_reg}")

            # Free the right register
            self._free_register(right_reg)

        return lines, i

    def _parse_primary_expression(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Parse primary expressions (numbers, variables, parentheses, strings, functions)"""
        lines = []
        token = tokens[i]

        if token == '(':
            # Parenthesized expression
            i += 1
            lines, i = self._parse_additive_expression(tokens, i)
            if i < len(tokens) and tokens[i] == ')':
                i += 1
            else:
                raise ValueError("Missing closing parenthesis")
        elif token.startswith('"') and token.endswith('"'):
            # String literal - store in memory and return address
            string_content = token.strip('"')
            string_addr = self._store_string_in_memory(string_content)
            result_reg = self._allocate_register()
            lines.append(f"    MOV {result_reg},{string_addr}")
            i += 1
        elif token.isdigit():
            # Number literal - check for constant folding
            folded_val, new_i = self._fold_constants(tokens, i)
            if folded_val is not None:
                result_reg = self._allocate_register()
                lines.append(f"    MOV {result_reg},{folded_val}")
                i = new_i
            else:
                result_reg = self._allocate_register()
                lines.append(f"    MOV {result_reg},{token}")
                i += 1
        elif token.isalpha() or '$' in token or (token.upper().startswith('L') and len(token) == 2 and token[1].isdigit()):
            # Check if this is a list access (L1(index))
            if token.upper().startswith('L') and len(token) == 2 and token[1].isdigit():
                # List access like L1, L2, etc.
                list_name = token.upper()
                i += 1
                if i < len(tokens) and tokens[i] == '(':
                    i += 1
                    # Parse index expression
                    index_lines, i = self._parse_additive_expression(tokens, i)
                    lines.extend(index_lines)
                    
                    if i < len(tokens) and tokens[i] == ')':
                        i += 1
                    else:
                        raise ValueError("Missing closing parenthesis in list access")
                    
                    # Generate code to load from list
                    list_addr = self._get_list_address(list_name)
                    index_reg = self._get_current_register()  # Save index register
                    result_reg = self._allocate_register()    # Allocate result register
                    
                    lines.extend([
                        f"    ; Load {list_name}({index_reg}) into {result_reg}",
                        f"    MOV P2,{list_addr}",        # Base address of list
                        f"    ADD P2,{index_reg}",        # Add index (×2 for 16-bit)
                        f"    ADD P2,{index_reg}",
                        f"    MOV {result_reg},[P2]",     # Load value
                    ])
                else:
                    # Regular variable
                    result_reg = self._allocate_register()
                    lines.extend(self._load_variable_to_reg(token, result_reg))
                    i += 1
            # Check if this is a function call
            elif i + 1 < len(tokens) and tokens[i + 1] == '(':
                # Function call
                func_name = token.upper()
                i += 2  # Skip function name and '('
                
                if func_name == 'INT':
                    # INT(string) - convert string to number
                    lines, i = self._parse_additive_expression(tokens, i)  # Parse string argument
                    if i < len(tokens) and tokens[i] == ')':
                        i += 1
                    else:
                        raise ValueError("Missing closing parenthesis in INT()")
                    # Assume current register contains string address, convert with STOI
                    current_reg = self._get_current_register()
                    lines.append(f"    STOI {current_reg},{current_reg}")  # Convert string at reg to integer in reg
                elif func_name == 'STR':
                    # STR(number) - convert number to string address
                    lines, i = self._parse_additive_expression(tokens, i)  # Parse number argument
                    if i < len(tokens) and tokens[i] == ')':
                        i += 1
                    else:
                        raise ValueError("Missing closing parenthesis in STR()")
                    # Convert number in current register to string at temporary buffer
                    current_reg = self._get_current_register()
                    lines.extend([
                        f"    PUSH {current_reg}",
                        "    MOV P1,0x6000",  # Temporary string buffer
                        f"    ITOS P1,{current_reg}",     # Convert reg to string at 0x6000
                        f"    MOV {current_reg},P1",      # Return string address
                        f"    POP {current_reg}",
                    ])
                else:
                    raise ValueError(f"Unknown function: {func_name}")
            else:
                # Variable
                result_reg = self._allocate_register()
                lines.extend(self._load_variable_to_reg(token, result_reg))
                i += 1
        else:
            raise ValueError(f"Unexpected token in expression: {token}")

        return lines, i

    def _fold_constants(self, tokens: List[str], i: int) -> Tuple[int, int]:
        """Try to fold constants in an expression. Returns (folded_value, new_i) or (None, original_i)"""
        # Enhanced constant folding for arithmetic expressions
        if not tokens[i].isdigit():
            return None, i
        
        left_val = int(tokens[i])
        original_i = i
        i += 1
        
        # Look for operator and right operand
        if i < len(tokens) and tokens[i] in ['+', '-', '*', '/']:
            op = tokens[i]
            i += 1
            
            if i < len(tokens) and tokens[i].isdigit():
                right_val = int(tokens[i])
                i += 1
                
                try:
                    if op == '+':
                        result = left_val + right_val
                    elif op == '-':
                        result = left_val - right_val
                    elif op == '*':
                        result = left_val * right_val
                    elif op == '/' and right_val != 0:
                        result = left_val // right_val  # Integer division
                    else:
                        return None, original_i
                    
                    # Check for more operations (for expressions like 1+2*3)
                    if i < len(tokens) and tokens[i] in ['+', '-', '*', '/']:
                        # Try to fold the next operation too
                        next_op = tokens[i]
                        i += 1
                        if i < len(tokens) and tokens[i].isdigit():
                            next_val = int(tokens[i])
                            i += 1
                            
                            if next_op == '+':
                                result = result + next_val
                            elif next_op == '-':
                                result = result - next_val
                            elif next_op == '*':
                                result = result * next_val
                            elif next_op == '/' and next_val != 0:
                                result = result // next_val
                            else:
                                return None, original_i
                    
                    return result, i
                    
                except:
                    return None, original_i
        
        return None, original_i

    def _store_string_in_memory(self, string: str) -> int:
        """Store a string in memory and return its address"""
        if string in self.strings:
            return self.strings[string]

        # Allocate new string (add null terminator)
        addr = 0x8000 + self.string_counter * 100  # Simple allocation
        self.strings[string] = addr
        self.string_counter += 1
        return addr

    def compile_program(self, nobasic_source: str, output_file: str):
        """Compile NoBASIC source code to assembly"""
        tokens = self._tokenize(nobasic_source)
        self._parse_tokens(tokens)

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(self.assembly_lines))

        print(f"Compiled NoBASIC program to {output_file}")

    def compile_to_lines(self, nobasic_source: str) -> list:
        """Compile NoBASIC source code to assembly lines without writing file"""
        tokens = self._tokenize(nobasic_source)
        self._parse_tokens(tokens)
        return self.assembly_lines

    def _compile_display_string(self, string: str) -> List[str]:
        """Generate code to display a string by inlining character display"""
        lines = []
        for char in string:
            if char == '\n':
                # Newline
                lines.extend([
                    f"    ; Newline",
                    "    MOV P0,[0xF101]",  # Get current VY
                    "    ADD P0,8",
                    "    MOV [0xF101],P0",  # Set new VY
                    "    MOV P0,0",
                    "    MOV [0xF100],P0",  # Reset VX
                ])
            else:
                ascii_val = ord(char)
                lines.extend([
                    f"    ; Display '{char}'",
                    f"    MOV P0,{ascii_val}",  # Character code
                    "    MOV P1,7",            # White color
                    "    CHAR P0,P1",          # Display character
                ])
        return lines

    def _compile_display_value(self) -> List[str]:
        """Generate code to display a value from P0 (either number or string address)"""
        # Check if P0 contains a string address (0x4000-0x7FFF range)
        return [
            "    ; Display value (number or string)",
            f"    MOV P1,P0",              # Save original value
            f"    CMP P0,0x4000",          # Check if >= string start
            f"    JC display_as_number",   # If < 0x4000, treat as number
            f"    CMP P0,0x8000",          # Check if < string end
            f"    JNC display_as_number",  # If >= 0x8000, treat as number
            f"    ; Display as string",
            f"    MOV P2,P0",              # P2 = string pointer
            f"display_str_loop:",
            f"    MOV P0,[P2]",            # Load character
            f"    CMP P0,0",               # Check for null terminator
            f"    JZ display_value_done",
            f"    CMP P0,10",              # Check for newline
            f"    JZ display_str_newline",
            f"    MOV P3,7",               # White color
            f"    CHAR P0,P3",             # Display character
            f"    INC P2",                 # Next character
            f"    JMP display_str_loop",
            f"display_str_newline:",
            f"    MOV P0,[0xF101]",        # Get current VY
            f"    ADD P0,8",
            f"    MOV [0xF101],P0",        # Set new VY
            f"    MOV P0,0",
            f"    MOV [0xF100],P0",        # Reset VX
            f"    INC P2",                 # Next character
            f"    JMP display_str_loop",
            f"display_as_number:",
            f"    MOV P0,P1",              # Restore original value
            f"    ; Display as number",
            f"    MOV P1,0x6000",          # Temporary buffer for string
            f"    ITOS P1,P0",             # Convert P0 to string at buffer
            f"    MOV P2,P1",              # P2 = string pointer
            f"display_num_loop:",
            f"    MOV P0,[P2]",            # Load character
            f"    CMP P0,0",               # Check for null terminator
            f"    JZ display_value_done",
            f"    MOV P3,7",               # White color
            f"    CHAR P0,P3",             # Display character
            f"    INC P2",                 # Next character
            f"    JMP display_num_loop",
            f"display_value_done:",
        ]

    def _compile_pause(self) -> List[str]:
        """Compile Pause statement - wait for key press"""
        return [
            "    ; Pause - wait for key press",
            "pause_loop:",
            "    KEYSTAT P0",     # Check if key available
            "    CMP P0,0",
            "    JZ pause_loop",  # Wait for key
            "    KEYIN P0",       # Read and discard the key
        ]

    def _compile_end(self) -> List[str]:
        """Compile End statement - terminate program"""
        return [
            "    ; End - terminate program",
            "    JMP halt",  # Jump to the halt loop
        ]

    def _compile_goto(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile Goto statement"""
        i += 1  # Skip GOTO
        if i < len(tokens):
            label_name = tokens[i]
            i += 1
            return [
                f"    ; Goto {label_name}",
                f"    JMP {label_name}",
            ], i
        return [], i

    def _compile_lbl(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile Lbl statement"""
        i += 1  # Skip LBL
        if i < len(tokens):
            label_name = tokens[i]
            i += 1
            return [
                f"    ; Lbl {label_name}",
                f"{label_name}:",
            ], i
        return [], i

    def _load_variable(self, var_name: str, dest_register: str = "P0") -> List[str]:
        """Generate code to load a variable into a register"""
        var_addr = self._get_variable_address(var_name)
        return [
            f"    ; Load {var_name} into {dest_register}",
            f"    MOV {dest_register},[0x{var_addr:04X}]",  # Direct memory access
        ]

    def _load_variable_to_reg(self, var_name: str, dest_register: str) -> List[str]:
        """Generate code to load a variable into a specific register"""
        var_addr = self._get_variable_address(var_name)
        return [
            f"    ; Load {var_name} into {dest_register}",
            f"    MOV {dest_register},[0x{var_addr:04X}]",  # Direct memory access
        ]

    def _store_variable(self, var_name: str, source_register: str = "P0") -> List[str]:
        """Generate code to store a register value into a variable"""
        var_addr = self._get_variable_address(var_name)
        return [
            f"    ; Store {source_register} into {var_name}",
            f"    MOV [0x{var_addr:04X}],{source_register}",  # Direct memory access
        ]

    def _store_variable_from_reg(self, var_name: str, source_register: str) -> List[str]:
        """Generate code to store a register value into a variable"""
        var_addr = self._get_variable_address(var_name)
        return [
            f"    ; Store {source_register} into {var_name}",
            f"    MOV [0x{var_addr:04X}],{source_register}",  # Direct memory access
        ]

    def _get_variable_address(self, var_name: str) -> int:
        """Get or allocate memory address for a variable"""
        var_name = var_name.upper()
        if var_name not in self.variables:
            # Allocate new variable address (2 bytes per variable)
            addr = self.VARIABLE_START + len(self.variables) * 2
            self.variables[var_name] = addr
        return self.variables[var_name]

    def _get_list_address(self, list_name: str) -> int:
        """Get or allocate memory address for a list"""
        list_name = list_name.upper()
        if list_name not in self.lists:
            # Allocate new list address (100 elements × 2 bytes = 200 bytes per list)
            addr = self.LIST_START + len(self.lists) * 200
            self.lists[list_name] = addr
            self.list_sizes[list_name] = 100  # Default size
        return self.lists[list_name]


def main():
    if len(sys.argv) != 3:
        print("Usage: python nobasic_compiler.py <input.nob> <output.asm>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    with open(input_file, 'r', encoding='utf-8') as f:
        nobasic_source = f.read()

    compiler = NoBasicCompiler()
    compiler.compile_program(nobasic_source, output_file)


if __name__ == "__main__":
    main()
