#!/usr/bin/env python3
"""
NoBASIC Compiler for Nova-16

Compiles NoBASIC source code to Nova-16 assembly language.

This compiler translates NoBASIC programs (inspired by TI-83/84 calculators)
into optimized Nova-16 assembly code for native execution.
"""

import sys
import os
import re
from typing import Dict, List, Tuple, Optional, Set
from pathlib import Path

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from nova_cpu import CPU
from nova_memory import Memory
from nova_gfx import GFX
from nova_keyboard import NovaKeyboard
from nova_sound import NovaSound


class NoBasicCompiler:
    """
    Compiles NoBASIC source code to Nova-16 assembly.
    """

    def __init__(self):
        # Initialize Nova-16 components for reference
        self.memory = Memory(0x10000)
        self.gfx = GFX()
        self.keyboard = NovaKeyboard()
        self.sound = NovaSound()
        self.sound.set_memory_reference(self.memory)
        self.cpu = CPU(self.memory, self.gfx, self.keyboard, self.sound)

        # Memory layout for compiled NoBASIC
        self.PROGRAM_START = 0x1000
        self.VARIABLE_START = 0x2000  # Variables A-Z
        self.LIST_START = 0x3000     # Lists L1-L6
        self.STRING_START = 0x4000   # Strings Str1-Str9
        self.MATRIX_START = 0x5000   # Matrices [A]-[J]
        self.TEMP_START = 0x6000     # Temporary storage
        self.STACK_START = 0xF000    # Parameter stack (grows downward)

        # Compilation state
        self.assembly_lines: List[str] = []
        self.variables: Dict[str, int] = {}  # Variable name -> memory address
        self.labels: Dict[str, str] = {}     # Label name -> assembly label
        self.label_counter = 0
        self.string_counter = 0
        self.strings: Dict[str, int] = {}    # String content -> memory address
        
        # Text cursor position for display statements
        self.cursor_x = 0
        self.cursor_y = 0

        # Initialize standard header
        self._init_assembly()

    def _init_assembly(self):
        """Initialize the assembly output with standard header"""
        self.assembly_lines = [
            "; NoBASIC Program - Generated by nobasic_compiler.py",
            "; Generated automatically - do not edit",
            "",
            "ORG 0x1000",
            "",
            "; Initialize stack pointer",
            "MOV P8,0xF000",
            "",
            "; Initialize text cursor position",
            "MOV VX,0",      # X position
            "MOV VY,0",      # Y position
            "MOV VL,0",      # Layer 0
            "",
            "; Program start",
            "start:",
        ]

    def _get_variable_address(self, var_name: str) -> int:
        """Get memory address for a variable"""
        if var_name not in self.variables:
            # Allocate new variable (2 bytes for 16-bit values)
            addr = self.VARIABLE_START + len(self.variables) * 2
            self.variables[var_name] = addr
        return self.variables[var_name]

    def _generate_label(self, prefix: str = "label") -> str:
        """Generate a unique label"""
        self.label_counter += 1
        return f"{prefix}_{self.label_counter}"

    def _tokenize(self, source: str) -> List[str]:
        """Tokenize NoBASIC source code"""
        # Split on whitespace and special characters, preserving newlines
        tokens = re.findall(r'[A-Za-z_][A-Za-z0-9_]*|:=|<=|>=|<>|[0-9]+(?:\.[0-9]+)?|"[^"]*"|\n|\S', source)

        # Filter out empty tokens
        filtered_tokens = []
        for token in tokens:
            if token:  # Keep all non-empty tokens including \n
                filtered_tokens.append(token)

        return filtered_tokens

    def _parse_tokens(self, tokens: List[str]):
        """Parse tokens and generate assembly"""
        i = 0
        while i < len(tokens):
            token = tokens[i].upper()

            # Only check for keywords at the start of statements (after newline or at beginning)
            is_statement_start = (i == 0 or tokens[i-1] == '\n')

            if is_statement_start:
                if token == "CLRHOME":
                    lines = self._compile_clrhome()
                    self.assembly_lines.extend(lines)
                    i += 1

                elif token == "DISP":
                    lines, new_i = self._compile_disp(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "FOR":
                    lines, new_i = self._compile_for(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "IF":
                    lines, new_i = self._compile_if(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "INPUT":
                    lines, new_i = self._compile_input(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "PROMPT":
                    lines, new_i = self._compile_prompt(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "WHILE":
                    lines, new_i = self._compile_while(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == "WEND":
                    lines = self._compile_wend()
                    self.assembly_lines.extend(lines)
                    i += 1

                elif token.isalpha() and i + 1 < len(tokens) and tokens[i + 1] == "=":
                    # Variable assignment
                    lines, new_i = self._compile_assignment(tokens, i)
                    self.assembly_lines.extend(lines)
                    i = new_i

                elif token == '\n':
                    i += 1
                    continue

                else:
                    # Skip unknown tokens at statement start
                    i += 1
            else:
                # Not at statement start, skip this token
                i += 1

        # Add program end with infinite loop to keep display visible
        self.assembly_lines.extend([
            "",
            "; Program end - infinite loop to keep display visible",
            "halt:",
            "JMP halt",
        ])

        # Add variable declarations
        for var_name, addr in self.variables.items():
            self.assembly_lines.extend([
                f"ORG 0x{addr:04X}",
                f"DW 0  ; Variable {var_name}",
            ])

        # Add string declarations
        for string_content, addr in self.strings.items():
            self.assembly_lines.extend([
                f"ORG 0x{addr:04X}",
            ])
            # Add string bytes
            for char in string_content:
                self.assembly_lines.append(f"DB {ord(char)}")
            self.assembly_lines.append("DB 0  ; Null terminator")

        # Add final ORG back to program area
        self.assembly_lines.extend([
            "",
            "ORG 0x1000",
        ])

    def _compile_clrhome(self) -> List[str]:
        """Compile ClrHome statement"""
        return [
            "    ; ClrHome",
            "    MOV VM,0",      # Coordinate mode
            "    MOV VL,0",      # Layer 0
            "    MOV VX,0",      # X = 0
            "    MOV VY,0",      # Y = 0
            "    MOV P0,0",      # Black color
            "    SFILL P0",      # Fill screen with black
        ]

    def _compile_disp(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile Disp statement"""
        lines = ["    ; Disp"]
        i += 1  # Skip DISP

        # Set cursor to current position
        lines.extend([
            f"    MOV VX,{self.cursor_x}",  # X position
            f"    MOV VY,{self.cursor_y}",  # Y position
            "    MOV VL,0",                 # Layer 0
        ])

        # Parse display arguments
        while i < len(tokens):
            token = tokens[i]

            if token == '\n':
                i += 1
                break

            if token.startswith('"'):
                # String literal
                string_content = token.strip('"')
                lines.extend(self._compile_display_string(string_content))
            elif token.isdigit() or token.isalpha():
                # Variable or number
                if token.isalpha():
                    # Variable
                    lines.extend(self._load_variable(token))
                else:
                    # Number
                    value = int(token)
                    lines.extend([
                        f"    MOV P0,{value}",
                    ])
                lines.extend(self._compile_display_number())
            elif token == ',':
                # New line
                lines.extend([
                    "    ADD VY,8",    # Move down 8 pixels
                    "    MOV VX,0",    # Reset X to left
                ])

            i += 1

        # Advance cursor to next line for next Disp statement
        self.cursor_y += 8
        if self.cursor_y >= 256:  # Wrap around if we reach bottom
            self.cursor_y = 0
        self.cursor_x = 0  # Reset X for next line

        return lines, i

    def _compile_for(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile For loop"""
        lines = []
        i += 1  # Skip FOR

        # Parse: FOR variable = start TO end
        if i < len(tokens):
            var_name = tokens[i]
            i += 2  # Skip variable and =

            start_value = tokens[i]
            i += 2  # Skip start and TO

            end_value = tokens[i]
            i += 1  # Skip end

            # Generate labels
            loop_label = self._generate_label("for_loop")
            end_label = self._generate_label("for_end")

            # Initialize loop variable
            var_addr = self._get_variable_address(var_name)
            lines.extend([
                f"    ; For {var_name} = {start_value} To {end_value}",
                f"    MOV P0,{start_value}",
                f"    MOV [0x{var_addr:04X}],P0",
                f"{loop_label}:",
            ])

            # Store loop info for END
            self.labels[f"end_{var_name}"] = end_label

        return lines, i

    def _compile_if(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile If statement"""
        lines = []
        i += 1  # Skip IF

        # Parse condition
        condition_lines, i = self._parse_condition(tokens, i)

        # Generate labels
        else_label = self._generate_label("if_else")
        end_label = self._generate_label("if_end")

        lines.extend(condition_lines)
        lines.extend([
            f"    JZ {else_label}",
            f"{else_label}:",
        ])

        # Skip THEN
        if i < len(tokens) and tokens[i].upper() == "THEN":
            i += 1

        return lines, i

    def _compile_input(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile Input statement"""
        lines = ["    ; Input"]
        i += 1  # Skip INPUT

        if i < len(tokens):
            var_name = tokens[i]
            var_addr = self._get_variable_address(var_name)

            lines.extend([
                f"    ; Input {var_name}",
                "    CALL read_number",
            ])
            lines.extend(self._store_variable(var_name))
            i += 1

        return lines, i

    def _compile_prompt(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile Prompt statement"""
        lines = ["    ; Prompt"]
        i += 1  # Skip PROMPT

        if i < len(tokens):
            var_name = tokens[i]
            var_addr = self._get_variable_address(var_name)

            lines.extend([
                f"    ; Prompt {var_name}",
                "    CALL read_number",
            ])
            lines.extend(self._store_variable(var_name))
            i += 1

        return lines, i

    def _compile_while(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile While loop"""
        lines = []
        i += 1  # Skip WHILE

        # Generate labels
        loop_label = self._generate_label("while_loop")
        end_label = self._generate_label("while_end")

        lines.extend([
            f"    ; While loop",
            f"{loop_label}:",
        ])

        # Parse condition
        condition_lines, i = self._parse_condition(tokens, i)
        lines.extend(condition_lines)
        lines.extend([
            f"    JZ {end_label}",
        ])

        # Store end label for WEND
        self.labels["current_while_end"] = end_label

        return lines, i

    def _compile_wend(self) -> List[str]:
        """Compile WEnd statement"""
        end_label = self.labels.get("current_while_end", "while_end")
        loop_label = end_label.replace("while_end", "while_loop")

        return [
            f"    JMP {loop_label}",
            f"{end_label}:",
        ]

    def _compile_assignment(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Compile variable assignment"""
        var_name = tokens[i]
        var_addr = self._get_variable_address(var_name)

        lines = [f"    ; {var_name} = "]
        i += 2  # Skip variable and =

        # Parse expression
        expr_lines, i = self._parse_expression(tokens, i)
        lines.extend(expr_lines)

        # Store result
        lines.extend(self._store_variable(var_name))

        return lines, i

    def _parse_condition(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Parse a condition for IF/WHILE"""
        lines = []

        # Simple comparison for now: var op value
        left = tokens[i]
        i += 1
        op = tokens[i]
        i += 1
        right = tokens[i]
        i += 1

        # Load left side
        if left.isalpha():
            lines.extend(self._load_variable(left))
        else:
            lines.append(f"    MOV P0,{left}")

        # Compare with right side
        if right.isalpha():
            lines.extend(self._load_variable(right, "P1"))
            lines.append("    CMP P0,P1")
        else:
            lines.append(f"    CMP P0,{right}")

        return lines, i

    def _parse_expression(self, tokens: List[str], i: int) -> Tuple[List[str], int]:
        """Parse a simple arithmetic expression"""
        lines = []

        # For now, support: number, variable, variable + number, variable - number
        token = tokens[i]

        if token.isdigit():
            # Number literal
            lines.append(f"    MOV P0,{token}")
            i += 1
        elif token.isalpha():
            # Variable
            lines.extend(self._load_variable(token))
            i += 1

            # Check for + or - operation
            if i < len(tokens) and tokens[i] in ['+', '-']:
                op = tokens[i]
                i += 1

                if i < len(tokens):
                    right_token = tokens[i]
                    if right_token.isdigit():
                        # Variable + number
                        if op == '+':
                            lines.append(f"    ADD P0,{right_token}")
                        else:  # op == '-'
                            lines.append(f"    SUB P0,{right_token}")
                    elif right_token.isalpha():
                        # Variable + variable
                        lines.extend(self._load_variable(right_token, "P1"))
                        if op == '+':
                            lines.append("    ADD P0,P1")
                        else:  # op == '-'
                            lines.append("    SUB P0,P1")
                    i += 1

        return lines, i

    def _store_string_in_memory(self, string: str) -> int:
        """Store a string in memory and return its address"""
        if string in self.strings:
            return self.strings[string]

        # Allocate new string (add null terminator)
        addr = 0x8000 + self.string_counter * 100  # Simple allocation
        self.strings[string] = addr
        self.string_counter += 1
        return addr

    def compile_program(self, nobasic_source: str, output_file: str):
        """Compile NoBASIC source code to assembly"""
        tokens = self._tokenize(nobasic_source)
        self._parse_tokens(tokens)

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(self.assembly_lines))

        print(f"Compiled NoBASIC program to {output_file}")

    def compile_to_lines(self, nobasic_source: str) -> list:
        """Compile NoBASIC source code to assembly lines without writing file"""
        tokens = self._tokenize(nobasic_source)
        self._parse_tokens(tokens)
        return self.assembly_lines

    def _compile_display_string(self, string: str) -> List[str]:
        """Generate code to display a string by inlining character display"""
        lines = []
        for char in string:
            ascii_val = ord(char)
            lines.extend([
                f"    ; Display '{char}'",
                f"    MOV P0,{ascii_val}",  # Character code
                "    MOV P1,7",            # White color
                "    CHAR P0,P1",          # Display character
                "    ADD VX,8",            # Move right for next character
            ])
        return lines

    def _compile_display_number(self) -> List[str]:
        """Generate code to display a number from P0 by inlining"""
        # For now, just display the raw value as a character
        # This is a simplified implementation - a full number-to-string conversion would be more complex
        return [
            "    ; Display number (simplified)",
            "    MOV P1,7",      # White color
            "    CHAR P0,P1",    # Display character in P0
            "    ADD VX,8",      # Move right
        ]

    def _load_variable(self, var_name: str, dest_register: str = "P0") -> List[str]:
        """Generate code to load a variable into a register"""
        var_addr = self._get_variable_address(var_name)
        return [
            f"    ; Load {var_name} into {dest_register}",
            f"    MOV {dest_register},[0x{var_addr:04X}]",  # Direct memory access
        ]

    def _store_variable(self, var_name: str, source_register: str = "P0") -> List[str]:
        """Generate code to store a register value into a variable"""
        var_addr = self._get_variable_address(var_name)
        return [
            f"    ; Store {source_register} into {var_name}",
            f"    MOV [0x{var_addr:04X}],{source_register}",  # Direct memory access
        ]


def main():
    if len(sys.argv) != 3:
        print("Usage: python nobasic_compiler.py <input.nob> <output.asm>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    with open(input_file, 'r', encoding='utf-8') as f:
        nobasic_source = f.read()

    compiler = NoBasicCompiler()
    compiler.compile_program(nobasic_source, output_file)


if __name__ == "__main__":
    main()
