#!/usr/bin/env python3
"""
NoBASIC Code Generator
Translates AST to Nova-16 assembly code.
"""

from typing import List
from nobasic_utils import (
    Program, Statement, Expression,
    ClrHomeStmt, DispStmt, InputStmt, AssignmentStmt, DimStmt,
    IfStmt, ForStmt, WhileStmt, DoLoopStmt, RepeatUntilStmt,
    SelectStmt, CaseClause, CallStmt, ReturnStmt, PauseStmt, BreakStmt, ContinueStmt,
    DefineStmt, GotoStmt, LabelStmt, TryCatchStmt, StructStmt, StructField, StructFieldStmt, StructInstanceStmt,
    BinaryExpr, UnaryExpr, LiteralExpr, VariableExpr,
    ArrayAccessExpr, FunctionCallExpr, ArrayLiteralExpr, StructFieldAccessExpr
)
from nobasic_errors import CodeGenError


class CodeGenerator:
    """Code generator for NoBASIC to Nova-16 assembly."""

    def __init__(self):
        self.output: List[str] = []
        self.label_counter = 0
        self.variable_addresses = {}  # Variable name -> memory address
        self.string_literals = {}     # String content -> memory address
        self.break_label = None
        self.continue_label = None

    def generate(self, program: Program) -> str:
        """
        Generate assembly code from AST.

        Args:
            program: The AST program node

        Returns:
            Generated assembly code as a string
        """
        self.output = []
        self.label_counter = 0
        self.variable_addresses = {}

        # Header
        self.output.append("; NoBASIC Program - Generated by nobasic_compiler.py")
        self.output.append("; Generated automatically - do not edit")
        self.output.append("")
        self.output.append("ORG 0x1000")
        self.output.append("")
        self.output.append("; Initialize stack pointer")
        self.output.append("MOV P8,0xF000")
        self.output.append("")
        self.output.append("; Initialize text cursor position")
        self.output.append("MOV VX,0")
        self.output.append("MOV VY,0")
        self.output.append("MOV VL,0")
        self.output.append("")
        self.output.append("; Program start")
        self.output.append("start:")

        # Generate code for statements
        for stmt in program.statements:
            self._generate_statement(stmt)

        # Program end
        self.output.append("")
        self.output.append("; Program end - infinite loop to keep display visible")
        self.output.append("halt:")
        self.output.append("JMP halt")

        # Variable storage
        self.output.append("")
        self.output.append("ORG 0x2000")
        for var in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ':
            self.output.append(f"DW 0  ; Variable {var}")

        return "\n".join(self.output)

    def _generate_statement(self, stmt: Statement):
        """Generate code for a statement."""
        if isinstance(stmt, ClrHomeStmt):
            self._generate_clrhome()
        elif isinstance(stmt, DispStmt):
            self._generate_disp(stmt)
        elif isinstance(stmt, AssignmentStmt):
            self._generate_assignment(stmt)
        elif isinstance(stmt, DimStmt):
            self._generate_dim(stmt)
        elif isinstance(stmt, IfStmt):
            self._generate_if(stmt)
        elif isinstance(stmt, ForStmt):
            self._generate_for(stmt)
        elif isinstance(stmt, WhileStmt):
            self._generate_while(stmt)
        elif isinstance(stmt, DoLoopStmt):
            self._generate_do_loop(stmt)
        elif isinstance(stmt, CallStmt):
            self._generate_call(stmt)
        elif isinstance(stmt, PauseStmt):
            self._generate_pause()
        elif isinstance(stmt, BreakStmt):
            self._generate_break()
        elif isinstance(stmt, ContinueStmt):
            self._generate_continue()
        elif isinstance(stmt, SelectStmt):
            self._generate_select(stmt)
        elif isinstance(stmt, DefineStmt):
            self._generate_define(stmt)
        elif isinstance(stmt, GotoStmt):
            self._generate_goto(stmt)
        elif isinstance(stmt, LabelStmt):
            self._generate_label(stmt)
        elif isinstance(stmt, ReturnStmt):
            self._generate_return()
        elif isinstance(stmt, TryCatchStmt):
            self._generate_try_catch(stmt)
        elif isinstance(stmt, StructStmt):
            self._generate_struct(stmt)
        elif isinstance(stmt, StructInstanceStmt):
            self._generate_struct_instance(stmt)
        # Add other statement types as needed

    def _generate_clrhome(self):
        """Generate code for ClrHome."""
        self.output.append("    ; ClrHome - clear screen (optimized)")
        self.output.append("    MOV P0,0")
        self.output.append("    MOV VM,P0")
        self.output.append("    MOV VL,P0")
        self.output.append("    MOV VX,P0")
        self.output.append("    MOV VY,P0")
        self.output.append("    SFILL P0")

    def _generate_disp(self, stmt: DispStmt):
        """Generate code for Disp."""
        self.output.append("    ; Disp")
        for expr in stmt.expressions:
            if isinstance(expr, LiteralExpr) and isinstance(expr.value, str):
                # For literal strings, check length
                if len(expr.value) <= 3:  # Short strings use individual CHAR
                    self._display_short_string(expr.value)
                else:  # Long strings use TEXT instruction
                    addr = self._get_string_literal_address(expr.value)
                    self.output.append(f"    MOV P0,{addr}")
                    self.output.append("    MOV P1,15")  # White color
                    self.output.append("    TEXT P0,P1")
            else:
                # For expressions, generate and display
                self._generate_expression(expr)
                self._display_value_in_p0()

    def _generate_assignment(self, stmt: AssignmentStmt):
        """Generate code for assignment."""
        if isinstance(stmt.target, VariableExpr):
            var_name = stmt.target.name
            self.output.append(f"    ; {var_name} = expression")
            # Generate expression
            self._generate_expression(stmt.expression)
            # Store result (simplified)
            addr = self._get_variable_address(var_name)
            self.output.append(f"    MOV [{addr}],P0")
        elif isinstance(stmt.target, StructFieldAccessExpr):
            struct_var = stmt.target.struct_var
            field_name = stmt.target.field_name
            self.output.append(f"    ; {struct_var}.{field_name} = expression")
            # Generate expression
            self._generate_expression(stmt.expression)
            # For now, assume simple offset (this needs proper struct field offset calculation)
            base_addr = self._get_variable_address(struct_var)
            # Assume field offset is 0 for now
            self.output.append(f"    MOV [{base_addr}],P0")
        else:
            self.output.append("    ; Complex assignment not implemented yet")

    def _generate_dim(self, stmt: DimStmt):
        """Generate code for DIM statement."""
        self.output.append(f"    ; DIM {stmt.array_name}({stmt.size}) - array declaration")
        # For now, just evaluate the size expression (no allocation yet)
        self._generate_expression(stmt.size)
        # TODO: Implement actual array allocation

    def _generate_if(self, stmt: IfStmt):
        """Generate code for If statement."""
        else_label = self._new_label("else")
        end_label = self._new_label("endif")

        # Condition
        self._generate_expression(stmt.condition)
        self.output.append("    JZ " + else_label)

        # Then block
        for s in stmt.then_stmts:
            self._generate_statement(s)

        self.output.append("    JMP " + end_label)
        self.output.append(else_label + ":")

        # Else block
        for s in stmt.else_stmts:
            self._generate_statement(s)

        self.output.append(end_label + ":")

    def _generate_for(self, stmt: ForStmt):
        """Generate code for For loop."""
        loop_label = self._new_label("for")
        end_label = self._new_label("next")

        # Save previous labels
        prev_break = self.break_label
        prev_continue = self.continue_label
        
        # Set current loop labels
        self.break_label = end_label
        self.continue_label = loop_label

        # Initialize variable
        self._generate_expression(stmt.start)
        var_addr = self._get_variable_address(stmt.variable)
        self.output.append(f"    MOV [{var_addr}],P0")

        self.output.append(loop_label + ":")

        # Check condition
        self.output.append(f"    MOV P0,[{var_addr}]")
        # For To loops, check if variable >= (end + 1)
        end_expr = stmt.end
        if hasattr(end_expr, 'value') and isinstance(end_expr.value, int):
            end_plus_one = LiteralExpr(end_expr.value + 1)
            self._generate_expression(end_plus_one)
        else:
            # For non-literal end, this is more complex
            self._generate_expression(end_expr)
            self.output.append("    ADD P0,1")
        self.output.append("    MOV P1,P0")
        self.output.append(f"    MOV P0,[{var_addr}]")
        self.output.append("    CMP P0,P1")
        self.output.append("    JGE " + end_label)

        # Loop body
        for s in stmt.statements:
            self._generate_statement(s)

        # Increment
        self.output.append(f"    MOV P0,[{var_addr}]")
        if stmt.step:
            self._generate_expression(stmt.step)
            self.output.append("    ADD P0,P1")
        else:
            self.output.append("    MOV P1,1")
            self.output.append("    ADD P0,P1")
        self.output.append(f"    MOV [{var_addr}],P0")

        self.output.append("    JMP " + loop_label)
        self.output.append(end_label + ":")

        # Restore previous labels
        self.break_label = prev_break
        self.continue_label = prev_continue

    def _generate_while(self, stmt: WhileStmt):
        """Generate code for While loop."""
        loop_label = self._new_label("while")
        end_label = self._new_label("wend")

        # Save previous labels
        prev_break = self.break_label
        prev_continue = self.continue_label
        
        # Set current loop labels
        self.break_label = end_label
        self.continue_label = loop_label

        self.output.append(loop_label + ":")

        # Check condition
        self._generate_expression(stmt.condition)
        self.output.append("    CMP P0,0")
        self.output.append("    JZ " + end_label)

        # Loop body
        for s in stmt.statements:
            self._generate_statement(s)

        self.output.append("    JMP " + loop_label)
        self.output.append(end_label + ":")

        # Restore previous labels
        self.break_label = prev_break
        self.continue_label = prev_continue

    def _generate_do_loop(self, stmt: DoLoopStmt):
        """Generate code for Do/Loop."""
        loop_label = self._new_label("do")
        end_label = self._new_label("loop")
        body_label = self._new_label("do_body")

        # Save previous labels
        prev_break = self.break_label
        prev_continue = self.continue_label
        
        # Set current loop labels
        self.break_label = end_label
        self.continue_label = loop_label

        if stmt.condition and stmt.loop_type == "while":
            # DO WHILE: check condition first
            self.output.append(loop_label + ":")
            self._generate_expression(stmt.condition)
            self.output.append("    CMP P0,0")
            self.output.append("    JZ " + end_label)
            self.output.append("    JMP " + body_label)
        elif stmt.condition and stmt.loop_type == "until":
            # DO UNTIL: execute body first, check at end
            self.output.append(loop_label + ":")
            self.output.append("    JMP " + body_label)
        else:
            # Unconditional DO LOOP
            self.output.append(loop_label + ":")

        self.output.append(body_label + ":")

        # Loop body
        for s in stmt.statements:
            self._generate_statement(s)

        if stmt.condition and stmt.loop_type == "while":
            # Jump back to condition check
            self.output.append("    JMP " + loop_label)
        elif stmt.condition and stmt.loop_type == "until":
            # Check condition at end
            self._generate_expression(stmt.condition)
            self.output.append("    CMP P0,0")
            self.output.append("    JZ " + loop_label)
        else:
            # Unconditional: always jump back
            self.output.append("    JMP " + loop_label)

        self.output.append(end_label + ":")

        # Restore previous labels
        self.break_label = prev_break
        self.continue_label = prev_continue

    def _generate_select(self, stmt: SelectStmt):
        """Generate code for Select Case statement."""
        end_label = self._new_label("select_end")
        
        # Generate the select expression once
        self._generate_expression(stmt.expression)
        self.output.append("    PUSH P0")  # Save the select value
        
        # Generate each case
        for i, case in enumerate(stmt.cases):
            case_label = self._new_label(f"case_{i}")
            next_case_label = self._new_label(f"case_{i}_next")
            
            # Check each value in the case
            for value in case.values:
                self.output.append("    POP P0")   # Get select value
                self.output.append("    PUSH P0")  # Save it back
                self._generate_expression(value)
                self.output.append("    MOV P1,P0")  # Case value to P1
                self.output.append("    POP P0")    # Select value back to P0
                self.output.append("    PUSH P0")   # Save select value again
                self.output.append("    CMP P0,P1")
                self.output.append("    JZ " + case_label)
            
            # If no match, go to next case
            self.output.append("    JMP " + next_case_label)
            
            # Case body
            self.output.append(case_label + ":")
            for s in case.statements:
                self._generate_statement(s)
            self.output.append("    JMP " + end_label)
            
            self.output.append(next_case_label + ":")
        
        # Else case
        if stmt.else_stmts:
            for s in stmt.else_stmts:
                self._generate_statement(s)
        
        # Clean up stack and end
        self.output.append("    POP P0")  # Clean up select value
        self.output.append(end_label + ":")

    def _generate_call(self, stmt: CallStmt):
        """Generate code for function call statement."""
        if stmt.subroutine.upper() == "PXLON":
            # PxlOn(Y, X, COLOR) - set pixel at (X,Y) to COLOR
            if len(stmt.arguments) != 3:
                raise CodeGenError(f"PxlOn requires 3 arguments, got {len(stmt.arguments)}")
            
            # Generate Y coordinate
            self._generate_expression(stmt.arguments[0])  # Y
            self.output.append("    MOV VY,P0")  # Y coordinate
            
            # Generate X coordinate
            self._generate_expression(stmt.arguments[1])  # X
            self.output.append("    MOV VX,P0")  # X coordinate
            
            # Generate color
            self._generate_expression(stmt.arguments[2])  # COLOR
            self.output.append("    MOV VL,P0")  # Color/layer
            
            self.output.append("    MOV VM,0")  # Coordinate mode
            self.output.append("    SWRITE P0") # Write pixel with color in P0
        elif stmt.subroutine.upper() == "LINE":
            # Line(X1, Y1, X2, Y2, COLOR) - draw line
            if len(stmt.arguments) != 5:
                raise CodeGenError(f"Line requires 5 arguments, got {len(stmt.arguments)}")
            
            # Set start position and color
            self._generate_expression(stmt.arguments[0])  # X1
            self.output.append("    MOV VX,P0")
            self._generate_expression(stmt.arguments[1])  # Y1  
            self.output.append("    MOV VY,P0")
            self._generate_expression(stmt.arguments[4])  # COLOR
            self.output.append("    MOV VC,P0")
            
            # Draw line to end position
            self._generate_expression(stmt.arguments[2])  # X2
            self.output.append("    PUSH P0")
            self._generate_expression(stmt.arguments[3])  # Y2
            self.output.append("    MOV P1,P0")  # Y2 to P1
            self.output.append("    POP P0")     # X2 to P0
            self.output.append("    SLINE P0,P1")
        elif stmt.subroutine.upper() == "CIRCLE":
            # Circle(X, Y, RADIUS, COLOR, FILLED) - draw circle
            if len(stmt.arguments) not in [4, 5]:
                raise CodeGenError(f"Circle requires 4 or 5 arguments, got {len(stmt.arguments)}")
            
            # Set center position and color
            self._generate_expression(stmt.arguments[0])  # X
            self.output.append("    MOV VX,P0")
            self._generate_expression(stmt.arguments[1])  # Y  
            self.output.append("    MOV VY,P0")
            self._generate_expression(stmt.arguments[3])  # COLOR
            self.output.append("    MOV VC,P0")
            
            # Draw circle
            self._generate_expression(stmt.arguments[2])  # RADIUS
            self.output.append("    PUSH P0")
            if len(stmt.arguments) == 5:
                self._generate_expression(stmt.arguments[4])  # FILLED (0 or 1)
            else:
                self.output.append("    MOV P0,0")  # Default to unfilled
            self.output.append("    MOV P1,P0")  # FILLED to P1
            self.output.append("    POP P0")     # RADIUS to P0
            self.output.append("    SCIRC P0,P1")
        elif stmt.subroutine.upper() == "RECT":
            # Rect(X, Y, Width, Height, Color) - draw rectangle
            if len(stmt.arguments) not in [4, 5]:
                raise CodeGenError(f"Rect requires 4 or 5 arguments, got {len(stmt.arguments)}")
            
            # Set position and color
            self._generate_expression(stmt.arguments[0])  # X
            self.output.append("    MOV VX,P0")
            self._generate_expression(stmt.arguments[1])  # Y  
            self.output.append("    MOV VY,P0")
            if len(stmt.arguments) == 5:
                self._generate_expression(stmt.arguments[4])  # Color
            else:
                self.output.append("    MOV P0,15")  # Default white color
            self.output.append("    MOV VL,P0")
            
            # Draw rectangle
            self._generate_expression(stmt.arguments[2])  # Width
            self.output.append("    PUSH P0")
            self._generate_expression(stmt.arguments[3])  # Height
            self.output.append("    MOV P1,P0")  # Height to P1
            self.output.append("    POP P0")     # Width to P0
            self.output.append("    SRECT P0,P1")
        elif stmt.subroutine.upper() == "FILL":
            # Fill(X, Y, Width, Height, Color) - draw filled rectangle
            if len(stmt.arguments) != 5:
                raise CodeGenError(f"Fill requires 5 arguments, got {len(stmt.arguments)}")
            
            # Set position and color
            self._generate_expression(stmt.arguments[0])  # X
            self.output.append("    MOV VX,P0")
            self._generate_expression(stmt.arguments[1])  # Y  
            self.output.append("    MOV VY,P0")
            self._generate_expression(stmt.arguments[4])  # Color
            self.output.append("    MOV VL,P0")
            
            # Draw filled rectangle
            self._generate_expression(stmt.arguments[2])  # Width
            self.output.append("    PUSH P0")
            self._generate_expression(stmt.arguments[3])  # Height
            self.output.append("    MOV P1,P0")  # Height to P1
            self.output.append("    POP P0")     # Width to P0
            self.output.append("    SFILL P0,P1")
        elif stmt.subroutine.upper() == "MEMSET":
            # MEMSET(address, value, length) - set memory
            if len(stmt.arguments) != 3:
                raise CodeGenError(f"MEMSET requires 3 arguments, got {len(stmt.arguments)}")
            # Generate arguments in reverse order for stack
            self._generate_expression(stmt.arguments[2])  # length
            self.output.append("    PUSH P0")
            self._generate_expression(stmt.arguments[1])  # value
            self.output.append("    PUSH P0")
            self._generate_expression(stmt.arguments[0])  # address
            self.output.append("    MEMSET P0,P1,P2")
            self.output.append("    ADD SP,4")  # Clean up stack
        elif stmt.subroutine.upper() == "MEMMOVE":
            # MEMMOVE(dest, src, length) - move memory
            if len(stmt.arguments) != 3:
                raise CodeGenError(f"MEMMOVE requires 3 arguments, got {len(stmt.arguments)}")
            # Generate arguments in reverse order for stack
            self._generate_expression(stmt.arguments[2])  # length
            self.output.append("    PUSH P0")
            self._generate_expression(stmt.arguments[1])  # src
            self.output.append("    PUSH P0")
            self._generate_expression(stmt.arguments[0])  # dest
            self.output.append("    MEMMOVE P0,P1,P2")
            self.output.append("    ADD SP,4")  # Clean up stack
        elif stmt.subroutine.upper() == "PXLON":
            # PxlOn(Y, X, COLOR) - set pixel (already implemented above)
            pass  # Handled above
        elif stmt.subroutine.upper() == "PXLOFF":
            # PxlOff(Y, X) - clear pixel
            if len(stmt.arguments) != 2:
                raise CodeGenError(f"PxlOff requires 2 arguments, got {len(stmt.arguments)}")
            
            # Generate coordinates
            self._generate_expression(stmt.arguments[0])  # Y
            self.output.append("    MOV VY,P0")  # Y coordinate
            self._generate_expression(stmt.arguments[1])  # X
            self.output.append("    MOV VX,P0")  # X coordinate
            
            self.output.append("    MOV VL,0")   # Color = 0 (clear)
            self.output.append("    MOV VM,0")  # Coordinate mode
            self.output.append("    SWRITE 0") # Write pixel
        elif stmt.subroutine.upper() == "PXLCHANGE":
            # PxlChange(Y, X) - toggle pixel (placeholder)
            if len(stmt.arguments) != 2:
                raise CodeGenError(f"PxlChange requires 2 arguments, got {len(stmt.arguments)}")
            # For now, just set to a different color
            self._generate_expression(stmt.arguments[0])  # Y
            self.output.append("    MOV VY,P0")  # Y coordinate
            self._generate_expression(stmt.arguments[1])  # X
            self.output.append("    MOV VX,P0")  # X coordinate
            
            self.output.append("    MOV VL,15")  # Some color
            self.output.append("    MOV VM,0")   # Coordinate mode
            self.output.append("    SWRITE 0")  # Write pixel
        elif stmt.subroutine.upper() == "PTON":
            # PtOn(Y, X, COLOR) - set pixel (alias for PxlOn)
            if len(stmt.arguments) != 3:
                raise CodeGenError(f"PtOn requires 3 arguments, got {len(stmt.arguments)}")
            
            # Generate Y coordinate
            self._generate_expression(stmt.arguments[0])  # Y
            self.output.append("    MOV VY,P0")  # Y coordinate
            
            # Generate X coordinate
            self._generate_expression(stmt.arguments[1])  # X
            self.output.append("    MOV VX,P0")  # X coordinate
            
            # Generate color
            self._generate_expression(stmt.arguments[2])  # COLOR
            self.output.append("    MOV VL,P0")  # Color/layer
            self.output.append("    MOV VM,0")  # Coordinate mode
            self.output.append("    SWRITE P0") # Write pixel with color in P0
        elif stmt.subroutine.upper() == "PTOFF":
            # PtOff(Y, X) - clear pixel (alias for PxlOff)
            if len(stmt.arguments) != 2:
                raise CodeGenError(f"PtOff requires 2 arguments, got {len(stmt.arguments)}")
            
            # Generate coordinates
            self._generate_expression(stmt.arguments[0])  # Y
            self.output.append("    MOV VY,P0")  # Y coordinate
            self._generate_expression(stmt.arguments[1])  # X
            self.output.append("    MOV VX,P0")  # X coordinate
            
            self.output.append("    MOV VL,0")   # Color = 0 (clear)
            self.output.append("    MOV VM,0")  # Coordinate mode
            self.output.append("    SWRITE 0") # Write pixel
        elif stmt.subroutine.upper() == "PTCHANGE":
            # PtChange(Y, X) - toggle pixel (alias for PxlChange)
            if len(stmt.arguments) != 2:
                raise CodeGenError(f"PtChange requires 2 arguments, got {len(stmt.arguments)}")
            # For now, just set to a different color
            self._generate_expression(stmt.arguments[0])  # Y
            self.output.append("    MOV VY,P0")  # Y coordinate
            self._generate_expression(stmt.arguments[1])  # X
            self.output.append("    MOV VX,P0")  # X coordinate
            
            self.output.append("    MOV VL,15")  # Some color
            self.output.append("    MOV VM,0")   # Coordinate mode
            self.output.append("    SWRITE 0")  # Write pixel
        elif stmt.subroutine.upper() == "PLAY":
            # PLAY - start sound playback
            # PLAY or PLAY(frequency) or PLAY(frequency, duration)
            if len(stmt.arguments) > 2:
                raise CodeGenError(f"PLAY requires 0-2 arguments, got {len(stmt.arguments)}")
            # For now, just play without setting registers
            self.output.append("    SPLAY")
        elif stmt.subroutine.upper() == "SOUND":
            # Sound(frequency, duration, volume, waveform) - play sound (placeholder)
            if len(stmt.arguments) != 4:
                raise CodeGenError(f"Sound requires 4 arguments, got {len(stmt.arguments)}")
            # Placeholder - do nothing for now
            pass
        elif stmt.subroutine.upper() == "STOP":
            # STOP - stop sound playback
            self.output.append("    SSTOP")
        else:
            # Subroutine call - jump to subroutine
            self.output.append(f"    JMP {stmt.subroutine}")
            # Note: Return will handle coming back

    def _generate_pause(self):
        """Generate code for Pause statement."""
        # For now, just halt execution (infinite loop)
        self.output.append("    ; Pause - halt execution")
        self.output.append("pause_loop:")
        self.output.append("    JMP pause_loop")

    def _generate_break(self):
        """Generate code for Break statement."""
        if self.break_label is None:
            raise CodeGenError("Break statement must be inside a loop")
        self.output.append(f"    JMP {self.break_label}")

    def _generate_continue(self):
        """Generate code for Continue statement."""
        if self.continue_label is None:
            raise CodeGenError("Continue statement must be inside a loop")
        self.output.append(f"    JMP {self.continue_label}")

    def _generate_expression(self, expr: Expression):
        """Generate code for an expression."""
        if isinstance(expr, LiteralExpr):
            if isinstance(expr.value, str):
                # String literal
                addr = self._get_string_literal_address(expr.value)
                self.output.append(f"    MOV P0,{addr}")
            else:
                # Number literal
                self.output.append(f"    MOV P0,{expr.value}")
        elif isinstance(expr, VariableExpr):
            # Variable reference
            addr = self._get_variable_address(expr.name)
            self.output.append(f"    MOV P0,[{addr}]")
        elif isinstance(expr, ArrayAccessExpr):
            # Array access
            addr = self._get_variable_address(expr.array)
            self._generate_expression(expr.index)
            self.output.append(f"    MOV P1,{addr}")  # Base address
            self.output.append("    ADD P1,P0")       # Add index (assuming 2 bytes per element)
            self.output.append("    ADD P1,P0")       # Add index again for 2-byte elements
            self.output.append("    MOV P0,[P1]")     # Load value
        elif isinstance(expr, StructFieldAccessExpr):
            # Struct field access - for now, assume simple offset calculation
            # TODO: Implement proper struct field offset calculation
            self.output.append(f"    ; Struct field access: {expr.struct_var}.{expr.field_name}")
            # For now, just load from a fixed offset (this needs proper implementation)
            base_addr = self._get_variable_address(expr.struct_var)
            # Assume field offset is 0 for now (X field)
            self.output.append(f"    MOV P0,[{base_addr}]")
        elif isinstance(expr, FunctionCallExpr):
            self._generate_function_call(expr)
        elif isinstance(expr, ArrayLiteralExpr):
            self._generate_array_literal(expr)
        elif isinstance(expr, BinaryExpr):
            self._generate_binary_expression(expr)
        elif isinstance(expr, UnaryExpr):
            self._generate_unary_expression(expr)
        else:
            raise CodeGenError(f"Unsupported expression type: {type(expr)}")

    def _generate_binary_expression(self, expr: BinaryExpr):
        """Generate code for binary expression."""
        # Generate right operand first (for stack-based evaluation)
        self._generate_expression(expr.right)
        self.output.append("    PUSH P0")
        
        # Generate left operand
        self._generate_expression(expr.left)
        
        # Apply operator
        op = expr.operator.upper()
        if op == "+":
            self.output.append("    POP P1")
            self.output.append("    ADD P0,P1")
        elif op == "-":
            self.output.append("    POP P1")
            self.output.append("    SUB P0,P1")
        elif op == "*":
            self.output.append("    POP P1")
            self.output.append("    MUL P0,P1")
        elif op == "/":
            self.output.append("    POP P1")
            self.output.append("    DIV P0,P1")
        elif op == "^":
            self.output.append("    POP P1")
            self.output.append("    POWR P0,P1")
        elif op == "=":
            self.output.append("    POP P1")
            self.output.append("    CMP P0,P1")
            self.output.append("    MOV P0,0")  # Assume false
            self.output.append("    JNZ cmp_done_" + str(self.label_counter))
            self.output.append("    MOV P0,1")  # True
            self.output.append("cmp_done_" + str(self.label_counter) + ":")
            self.label_counter += 1
        elif op == "<>":
            self.output.append("    POP P1")
            self.output.append("    CMP P0,P1")
            self.output.append("    MOV P0,0")  # Assume false
            self.output.append("    JZ cmp_done_" + str(self.label_counter))
            self.output.append("    MOV P0,1")  # True
            self.output.append("cmp_done_" + str(self.label_counter) + ":")
            self.label_counter += 1
        elif op == "!=":
            self.output.append("    POP P1")
            self.output.append("    CMP P0,P1")
            self.output.append("    MOV P0,0")  # Assume false
            self.output.append("    JZ cmp_done_" + str(self.label_counter))
            self.output.append("    MOV P0,1")  # True
            self.output.append("cmp_done_" + str(self.label_counter) + ":")
            self.label_counter += 1
        elif op == "<":
            self.output.append("    POP P1")
            self.output.append("    CMP P0,P1")
            self.output.append("    MOV P0,0")  # Assume false
            self.output.append("    JLT cmp_done_" + str(self.label_counter))
            self.output.append("    MOV P0,1")  # True
            self.output.append("cmp_done_" + str(self.label_counter) + ":")
            self.label_counter += 1
        elif op == ">":
            self.output.append("    POP P1")
            self.output.append("    CMP P0,P1")
            self.output.append("    MOV P0,0")  # Assume false
            self.output.append("    JGT cmp_done_" + str(self.label_counter))
            self.output.append("    MOV P0,1")  # True
            self.output.append("cmp_done_" + str(self.label_counter) + ":")
            self.label_counter += 1
        elif op == "<=":
            self.output.append("    POP P1")
            self.output.append("    CMP P0,P1")
            self.output.append("    MOV P0,0")  # Assume false
            self.output.append("    JLE cmp_done_" + str(self.label_counter))
            self.output.append("    MOV P0,1")  # True
            self.output.append("cmp_done_" + str(self.label_counter) + ":")
            self.label_counter += 1
        elif op == ">=":
            self.output.append("    POP P1")
            self.output.append("    CMP P0,P1")
            self.output.append("    MOV P0,0")  # Assume false
            self.output.append("    JGE cmp_done_" + str(self.label_counter))
            self.output.append("    MOV P0,1")  # True
            self.output.append("cmp_done_" + str(self.label_counter) + ":")
            self.label_counter += 1
        elif op == "AND":
            self.output.append("    POP P1")
            self.output.append("    AND P0,P1")
        elif op == "OR":
            self.output.append("    POP P1")
            self.output.append("    OR P0,P1")
        elif op == "XOR":
            self.output.append("    POP P1")
            self.output.append("    XOR P0,P1")
        elif op == "&":
            # String concatenation
            self.output.append("    POP P1")  # Second string
            # P0 has first string, P1 has second string
            # TODO: Implement string concatenation
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P2,{temp_addr}")
            self.output.append("    STRCPY P2,P0")  # Copy first string
            self.output.append("    STRCAT P2,P1")  # Concatenate second string
            self.output.append(f"    MOV P0,{temp_addr}")
        elif op == "MOD":
            self.output.append("    POP P1")
            self.output.append("    MOD P0,P1")
        elif op == "SHL":
            self.output.append("    POP P1")
            self.output.append("    SHL P0,P1")
        elif op == "SHR":
            self.output.append("    POP P1")
            self.output.append("    SHR P0,P1")
        else:
            raise CodeGenError(f"Unsupported binary operator: {op}")

    def _generate_unary_expression(self, expr: UnaryExpr):
        """Generate code for unary expression."""
        self._generate_expression(expr.operand)
        
        op = expr.operator.upper()
        if op == "-":
            self.output.append("    NEG P0")
        elif op == "NOT":
            self.output.append("    NOT P0")
        else:
            raise CodeGenError(f"Unsupported unary operator: {op}")

    def _generate_function_call(self, expr: FunctionCallExpr):
        """Generate code for function call expression."""
        # Handle built-in functions
        func_name = expr.name.upper()
        
        if func_name == "LEN":
            # LEN(string) - string length
            if len(expr.arguments) != 1:
                raise CodeGenError(f"LEN requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            self.output.append("    STRLEN P0")  # Result in R0
            self.output.append("    MOV P0,R0")
        elif func_name == "VAL":
            # VAL(string) - convert string to number
            if len(expr.arguments) != 1:
                raise CodeGenError(f"VAL requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            # TODO: Implement string to number conversion
            self.output.append("    ; VAL() not fully implemented")
        elif func_name == "ASC":
            # ASC(string) - ASCII value of first character
            if len(expr.arguments) != 1:
                raise CodeGenError(f"ASC requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            self.output.append("    MOV P0,[P0]")  # Get first character
        elif func_name == "CHR":
            # CHR(code) - character from ASCII code
            if len(expr.arguments) != 1:
                raise CodeGenError(f"CHR requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            # P0 already contains the character code
        elif func_name == "UPPER":
            # UPPER(string) - convert to uppercase
            if len(expr.arguments) != 1:
                raise CodeGenError(f"UPPER requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P1,{temp_addr}")
            self.output.append("    STRUPR P1,P0")
            self.output.append(f"    MOV P0,{temp_addr}")
        elif func_name == "LOWER":
            # LOWER(string) - convert to lowercase
            if len(expr.arguments) != 1:
                raise CodeGenError(f"LOWER requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P1,{temp_addr}")
            self.output.append("    STRLWR P1,P0")
            self.output.append(f"    MOV P0,{temp_addr}")
        elif func_name == "TRIM":
            # TRIM(string) - remove leading/trailing whitespace
            if len(expr.arguments) != 1:
                raise CodeGenError(f"TRIM requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            # TODO: Implement TRIM function
            self.output.append("    ; TRIM() not implemented")
        elif func_name == "LEFT":
            # LEFT(string, count) - left substring
            if len(expr.arguments) != 2:
                raise CodeGenError(f"LEFT requires 2 arguments, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])  # string
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # count
            self.output.append("    MOV P2,P0")  # count to P2
            self.output.append("    POP P0")     # string address back to P0
            
            # Copy left substring to temp buffer
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P1,{temp_addr}")  # destination
            
            # Manual left substring
            left_loop = f"left_loop_{self.label_counter}"
            left_end = f"left_end_{self.label_counter}"
            self.label_counter += 1
            
            self.output.append(f"    MOV P3,0")  # index
            self.output.append(f"{left_loop}:")
            self.output.append("    CMP P3,P2")
            self.output.append(f"    JGE {left_end}")
            self.output.append("    MOV P4,[P0+P3]")  # get char from source
            self.output.append("    MOV [P1+P3],P4")  # store to destination
            self.output.append("    INC P3")
            self.output.append(f"    JMP {left_loop}")
            self.output.append(f"{left_end}:")
            self.output.append("    MOV [P1+P3],0")  # null terminate
            self.output.append(f"    MOV P0,{temp_addr}")
        elif func_name == "RIGHT":
            # RIGHT(string, count) - right substring
            if len(expr.arguments) != 2:
                raise CodeGenError(f"RIGHT requires 2 arguments, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])  # string
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # count
            self.output.append("    MOV P2,P0")  # count to P2
            self.output.append("    POP P0")     # string address back to P0
            
            # Get string length first
            self.output.append("    STRLEN P0")  # length in R0
            self.output.append("    MOV P3,R0")  # length to P3
            
            # Copy right substring to temp buffer
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P1,{temp_addr}")  # destination
            
            # Manual right substring
            right_loop = f"right_loop_{self.label_counter}"
            right_end = f"right_end_{self.label_counter}"
            self.label_counter += 1
            
            self.output.append(f"    MOV P4,0")  # destination index
            self.output.append(f"    SUB P3,P2")  # start position = length - count
            self.output.append(f"{right_loop}:")
            self.output.append("    CMP P4,P2")
            self.output.append(f"    JGE {right_end}")
            self.output.append("    MOV P5,[P0+P3+P4]")  # get char from source
            self.output.append("    MOV [P1+P4],P5")     # store to destination
            self.output.append("    INC P4")
            self.output.append(f"    JMP {right_loop}")
            self.output.append(f"{right_end}:")
            self.output.append("    MOV [P1+P4],0")  # null terminate
            self.output.append(f"    MOV P0,{temp_addr}")
        elif func_name == "MID":
            # MID(string, start, count) - middle substring
            if len(expr.arguments) != 3:
                raise CodeGenError(f"MID requires 3 arguments, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])  # string
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # start (0-based)
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[2])  # count
            self.output.append("    MOV P3,P0")  # count to P3
            self.output.append("    POP P2")     # start to P2
            self.output.append("    POP P0")     # string address to P0
            
            # Copy middle substring to temp buffer
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P1,{temp_addr}")  # destination
            
            # Manual middle substring
            mid_loop = f"mid_loop_{self.label_counter}"
            mid_end = f"mid_end_{self.label_counter}"
            self.label_counter += 1
            
            self.output.append(f"    MOV P4,0")  # destination index
            self.output.append(f"{mid_loop}:")
            self.output.append("    CMP P4,P3")
            self.output.append(f"    JGE {mid_end}")
            self.output.append("    MOV P5,[P0+P2+P4]")  # get char from source
            self.output.append("    MOV [P1+P4],P5")     # store to destination
            self.output.append("    INC P4")
            self.output.append(f"    JMP {mid_loop}")
            self.output.append(f"{mid_end}:")
            self.output.append("    MOV [P1+P4],0")  # null terminate
            self.output.append(f"    MOV P0,{temp_addr}")
        elif func_name == "INSTR":
            # INSTR(haystack, needle) - find substring position
            if len(expr.arguments) != 2:
                raise CodeGenError(f"INSTR requires 2 arguments, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])  # haystack
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # needle
            self.output.append("    MOV P1,P0")  # needle to P1
            self.output.append("    POP P0")     # haystack to P0
            self.output.append("    STRFIND P0,P1")  # result in R0
            self.output.append("    MOV P0,R0")  # result to P0 (1-based position or 0 if not found)
        elif expr.name.upper() == "MEMSET":
            # MEMSET(address, value, length) - set memory
            if len(expr.arguments) != 3:
                raise CodeGenError(f"MEMSET requires 3 arguments, got {len(expr.arguments)}")
            # Generate arguments in reverse order for stack
            self._generate_expression(expr.arguments[2])  # length
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # value
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[0])  # address
            self.output.append("    MEMSET P0,P1,P2")
            self.output.append("    ADD SP,4")  # Clean up stack
        elif expr.name.upper() == "MEMCPY":
            # MEMCPY(dest, src, length) - copy memory
            if len(expr.arguments) != 3:
                raise CodeGenError(f"MEMCPY requires 3 arguments, got {len(expr.arguments)}")
            # Generate arguments in reverse order for stack
            self._generate_expression(expr.arguments[2])  # length
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # src
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[0])  # dest
            self.output.append("    MEMCPY P0,P1,P2")
            self.output.append("    ADD SP,4")  # Clean up stack
            self.output.append("    MOV P0,0")  # Return 0
        elif expr.name.upper() == "MEMTEST":
            # MEMTEST(addr1, addr2, length) - compare memory regions
            if len(expr.arguments) != 3:
                raise CodeGenError(f"MEMTEST requires 3 arguments, got {len(expr.arguments)}")
            # Generate arguments in reverse order for stack
            self._generate_expression(expr.arguments[2])  # length
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # addr2
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[0])  # addr1
            self.output.append("    MEMCMP P0,P1,P2")  # Compare and result in P0
            self.output.append("    ADD SP,4")  # Clean up stack
        elif expr.name.upper() == "MEMMOVE":
            # MEMMOVE(dest, src, length) - move memory
            if len(expr.arguments) != 3:
                raise CodeGenError(f"MEMMOVE requires 3 arguments, got {len(expr.arguments)}")
            # Generate arguments in reverse order for stack
            self._generate_expression(expr.arguments[2])  # length
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # src
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[0])  # dest
            self.output.append("    MEMMOVE P0,P1,P2")
            self.output.append("    ADD SP,4")  # Clean up stack
            self.output.append("    MOV P0,0")  # Return 0
        elif expr.name.upper() == "TRIM":
            # TRIM(string) - remove whitespace
            if len(expr.arguments) != 1:
                raise CodeGenError(f"TRIM requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            
            # Manual trim implementation
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P1,{temp_addr}")  # destination
            
            # Find start (skip leading whitespace)
            trim_find_start = f"trim_find_start_{self.label_counter}"
            trim_copy = f"trim_copy_{self.label_counter}"
            trim_find_end = f"trim_find_end_{self.label_counter}"
            trim_done = f"trim_done_{self.label_counter}"
            self.label_counter += 1
            
            self.output.append(f"    MOV P2,0")  # source index
            self.output.append(f"{trim_find_start}:")
            self.output.append("    MOV P3,[P0+P2]")  # get char
            self.output.append("    CMP P3,0")        # end of string?
            self.output.append(f"    JZ {trim_done}")
            self.output.append("    CMP P3,32")       # space?
            self.output.append(f"    JNE {trim_copy}")
            self.output.append("    CMP P3,9")        # tab?
            self.output.append(f"    JNE {trim_copy}")
            self.output.append("    CMP P3,10")       # newline?
            self.output.append(f"    JNE {trim_copy}")
            self.output.append("    CMP P3,13")       # carriage return?
            self.output.append(f"    JNE {trim_copy}")
            self.output.append("    INC P2")          # skip whitespace
            self.output.append(f"    JMP {trim_find_start}")
            
            self.output.append(f"{trim_copy}:")
            self.output.append(f"    MOV P4,0")  # destination index
            
            # Copy until end, then back up to remove trailing whitespace
            trim_copy_loop = f"trim_copy_loop_{self.label_counter}"
            self.label_counter += 1
            self.output.append(f"{trim_copy_loop}:")
            self.output.append("    MOV P3,[P0+P2]")  # get char
            self.output.append("    CMP P3,0")        # end of string?
            self.output.append(f"    JZ {trim_find_end}")
            self.output.append("    MOV [P1+P4],P3")  # copy char
            self.output.append("    INC P2")
            self.output.append("    INC P4")
            self.output.append(f"    JMP {trim_copy_loop}")
            
            self.output.append(f"{trim_find_end}:")
            # Remove trailing whitespace
            self.output.append("    DEC P4")  # back up one
            trim_trim_end = f"trim_trim_end_{self.label_counter}"
            self.label_counter += 1
            self.output.append(f"{trim_trim_end}:")
            self.output.append("    CMP P4,0")
            self.output.append(f"    JL {trim_done}")  # went too far back
            self.output.append("    MOV P3,[P1+P4]")   # get char from end
            self.output.append("    CMP P3,32")        # space?
            self.output.append(f"    JNE {trim_done}")
            self.output.append("    CMP P3,9")         # tab?
            self.output.append(f"    JNE {trim_done}")
            self.output.append("    CMP P3,10")        # newline?
            self.output.append(f"    JNE {trim_done}")
            self.output.append("    CMP P3,13")        # carriage return?
            self.output.append(f"    JNE {trim_done}")
            self.output.append("    DEC P4")           # remove trailing whitespace
            self.output.append(f"    JMP {trim_trim_end}")
            
            self.output.append(f"{trim_done}:")
            self.output.append("    INC P4")           # point to after last char
            self.output.append("    MOV [P1+P4],0")    # null terminate
            self.output.append(f"    MOV P0,{temp_addr}")
        elif expr.name.upper() == "REPLACE":
            # REPLACE(string, old, new) - replace substring
            if len(expr.arguments) != 3:
                raise CodeGenError(f"REPLACE requires 3 arguments, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])  # string
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # old
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[2])  # new
            self.output.append("    MOV P3,P0")  # new to P3
            self.output.append("    POP P2")     # old to P2
            self.output.append("    POP P0")     # string to P0
            
            # For now, simple implementation - just return original string
            # TODO: Implement full string replacement
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P1,{temp_addr}")
            self.output.append("    STRCPY P1,P0")  # Copy original
            self.output.append(f"    MOV P0,{temp_addr}")
        elif expr.name.upper() == "SPLIT":
            # SPLIT(string, delimiter) - split string into array
            if len(expr.arguments) != 2:
                raise CodeGenError(f"SPLIT requires 2 arguments, got {len(expr.arguments)}")
            # For now, return 0 (placeholder - should return array)
            self.output.append("    MOV P0,0")
        elif expr.name.upper() == "JOIN":
            # JOIN(array, delimiter, count) - join array elements
            if len(expr.arguments) not in [2, 3]:
                raise CodeGenError(f"JOIN requires 2 or 3 arguments, got {len(expr.arguments)}")
            # For now, return empty string (placeholder)
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P0,{temp_addr}")
            self.output.append("    MOV [P0],0")  # Empty string
        elif func_name == "COLOR":
            # COLOR(ramp, shade) - create color value
            if len(expr.arguments) != 2:
                raise CodeGenError(f"COLOR requires 2 arguments, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])  # ramp
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # shade
            self.output.append("    MOV P1,P0")  # shade to P1
            self.output.append("    POP P0")     # ramp to P0
            self.output.append("    SHL P0,4")   # ramp * 16
            self.output.append("    OR P0,P1")   # add shade
        elif func_name == "RAMP":
            # RAMP(color) - extract ramp from color
            if len(expr.arguments) != 1:
                raise CodeGenError(f"RAMP requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            self.output.append("    SHR P0,4")   # color >> 4
        elif func_name == "SHADE":
            # SHADE(color) - extract shade from color
            if len(expr.arguments) != 1:
                raise CodeGenError(f"SHADE requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            self.output.append("    AND P0,15")  # color & 15
        elif func_name == "STR":
            # STR(number) - convert number to string
            if len(expr.arguments) != 1:
                raise CodeGenError(f"STR requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            # TODO: Implement number to string conversion
            # For now, just return a placeholder string
            temp_addr = f"0x{0x4000 + self.label_counter:04X}"
            self.label_counter += 1
            self.output.append(f"    MOV P1,{temp_addr}")
            self.output.append("    ; STR() conversion not fully implemented")
            self.output.append("    MOV [P1],'0'")  # Placeholder
            self.output.append("    MOV [P1+1],0")  # Null terminator
            self.output.append(f"    MOV P0,{temp_addr}")
        elif func_name == "INT":
            # INT(string) - convert string to integer
            if len(expr.arguments) != 1:
                raise CodeGenError(f"INT requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            # TODO: Implement string to number conversion
            self.output.append("    ; INT() conversion not implemented")
            self.output.append("    MOV P0,0")  # Placeholder
        elif func_name == "KEYIN":
            # KEYIN() - read key from keyboard
            if len(expr.arguments) != 0:
                raise CodeGenError(f"KEYIN requires 0 arguments, got {len(expr.arguments)}")
            self.output.append("    KEYIN P0")
        elif func_name == "KEYSTAT":
            # KEYSTAT() - check if key is available
            if len(expr.arguments) != 0:
                raise CodeGenError(f"KEYSTAT requires 0 arguments, got {len(expr.arguments)}")
            self.output.append("    KEYSTAT P0")
        elif func_name == "MIN":
            # MIN(a, b) - minimum of two values
            if len(expr.arguments) != 2:
                raise CodeGenError(f"MIN requires 2 arguments, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])
            self.output.append("    MOV P1,P0")
            self.output.append("    POP P0")
            self.output.append("    CMP P0,P1")
            self.output.append("    JLE min_done_" + str(self.label_counter))
            self.output.append("    MOV P0,P1")
            self.output.append("min_done_" + str(self.label_counter) + ":")
            self.label_counter += 1
        elif func_name == "MAX":
            # MAX(a, b) - maximum of two values
            if len(expr.arguments) != 2:
                raise CodeGenError(f"MAX requires 2 arguments, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])
            self.output.append("    MOV P1,P0")
            self.output.append("    POP P0")
            self.output.append("    CMP P0,P1")
            self.output.append("    JGE max_done_" + str(self.label_counter))
            self.output.append("    MOV P0,P1")
            self.output.append("max_done_" + str(self.label_counter) + ":")
            self.label_counter += 1
        elif func_name == "POW":
            # POW(base, exponent) - exponentiation
            if len(expr.arguments) != 2:
                raise CodeGenError(f"POW requires 2 arguments, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])  # base
            self.output.append("    PUSH P0")
            self._generate_expression(expr.arguments[1])  # exponent
            self.output.append("    MOV P1,P0")  # exponent to P1
            self.output.append("    POP P0")     # base to P0
            self.output.append("    POWR P0,P1") # P0 = P0 ^ P1
        elif func_name == "ABS":
            # ABS(value) - absolute value
            if len(expr.arguments) != 1:
                raise CodeGenError(f"ABS requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            # Check if negative (sign bit set)
            self.output.append("    MOV P1,P0")  # copy value
            self.output.append("    SHR P1,15")  # get sign bit
            self.output.append("    CMP P1,1")   # check if negative
            abs_label = f"abs_done_{self.label_counter}"
            self.label_counter += 1
            self.output.append(f"    JNZ {abs_label}")
            self.output.append("    NEG P0")     # negate if negative
            self.output.append(f"{abs_label}:")
        elif func_name == "RND":
            # RND() or RND(max) - random number
            if len(expr.arguments) == 0:
                # RND() - return 0-255
                self.output.append("    ; RND() not fully implemented")
                self.output.append("    MOV P0,42")  # Placeholder random value
            elif len(expr.arguments) == 1:
                # RND(max) - return 0 to max-1
                self._generate_expression(expr.arguments[0])  # max value
                # For now, just return a value < max (placeholder)
                self.output.append("    ; RND(max) not fully implemented")
                self.output.append("    MOV P0,5")  # Placeholder value < 10
            else:
                raise CodeGenError(f"RND requires 0 or 1 arguments, got {len(expr.arguments)}")
        elif func_name == "SQRT":
            # SQRT(value) - square root
            if len(expr.arguments) != 1:
                raise CodeGenError(f"SQRT requires 1 argument, got {len(expr.arguments)}")
            self._generate_expression(expr.arguments[0])
            # TODO: Implement square root
            self.output.append("    ; SQRT() not implemented")
            # For now, just return the input (placeholder)
        else:
            # Generic function call (not implemented)
            raise CodeGenError(f"Unknown function: {expr.name}")

    def _generate_array_literal(self, expr: ArrayLiteralExpr):
        """Generate code for array literals."""
        # For now, just return 0 (placeholder)
        # TODO: Implement proper array allocation and initialization
        self.output.append("    MOV P0,0")

    def _generate_define(self, stmt: DefineStmt):
        """Generate code for Define statement."""
        # For now, just generate a label for the subroutine
        self.output.append(f"{stmt.name}:")
        for sub_stmt in stmt.statements:
            self._generate_statement(sub_stmt)
        # Return is handled by the ReturnStmt

    def _generate_goto(self, stmt: GotoStmt):
        """Generate code for Goto statement."""
        self.output.append(f"    JMP {stmt.label}")

    def _generate_label(self, stmt: LabelStmt):
        """Generate code for Label statement."""
        self.output.append(f"{stmt.name}:")

    def _generate_return(self):
        """Generate code for Return statement."""
        self.output.append("    RET")

    def _generate_try_catch(self, stmt: TryCatchStmt):
        """Generate code for Try/Catch statement."""
        # For now, just generate the try block
        # TODO: Implement actual error handling when runtime errors are supported
        self.output.append("    ; Try block")
        for try_stmt in stmt.try_stmts:
            self._generate_statement(try_stmt)
        # Skip catch block for now
        self.output.append("    ; Catch block (not implemented)")

    def _generate_struct(self, stmt: StructStmt):
        """Generate code for Struct definition."""
        self.output.append(f"    ; Struct {stmt.name}")
        for field in stmt.fields:
            self.output.append(f"    ;   {field.name}: {field.field_type}")
        # Struct definitions don't generate runtime code, just type information
        # Field access will be handled by StructFieldStmt

    def _generate_struct_instance(self, stmt: StructInstanceStmt):
        """Generate code for struct instance declaration."""
        self.output.append(f"    ; DIM {stmt.var_name} AS {stmt.struct_name}")
        # For now, just allocate space for the struct (assume 4 bytes for 2 fields)
        # TODO: Calculate actual size based on struct definition
        # This would require looking up the struct definition and calculating field offsets
        addr = self._get_variable_address(stmt.var_name)
        self.output.append(f"    MOV [{addr}],0")  # Placeholder for struct instance

    def _get_variable_address(self, name: str) -> str:
        """Get memory address for a variable."""
        if name not in self.variable_addresses:
            # Assign addresses starting from 0x2000
            addr = 0x2000 + len(self.variable_addresses) * 2
            self.variable_addresses[name] = f"0x{addr:04X}"
        return self.variable_addresses[name]

    def _get_string_literal_address(self, content: str) -> str:
        """Get or allocate address for a string literal."""
        if content not in self.string_literals:
            # Allocate string in data section (starting at 0x3000)
            addr = 0x3000 + len(self.string_literals) * 256  # 256 bytes per string
            self.string_literals[content] = f"0x{addr:04X}"
            
            # Add string data to output
            self.output.append(f"")
            self.output.append(f"; String literal: {repr(content)}")
            self.output.append(f"ORG 0x{addr:04X}")
            for i, char in enumerate(content):
                self.output.append(f"    DB {ord(char)}")
            self.output.append(f"    DB 0  ; null terminator")
        
        return self.string_literals[content]

    def _new_label(self, prefix: str) -> str:
        """Generate a new unique label."""
        self.label_counter += 1
        return f"{prefix}_{self.label_counter}"
    
    def _display_value_in_p0(self):
        """Display the value in P0 (assumed to be a string address)."""
        display_loop = f"display_loop_{self.label_counter}"
        display_end = f"display_end_{self.label_counter}"
        self.label_counter += 1
        
        self.output.append(f"    ; Display string at address in P0")
        self.output.append(f"    MOV P1,P0")  # String address to P1
        self.output.append(f"{display_loop}:")
        self.output.append("    MOV P0,[P1]")  # Get character
        self.output.append("    CMP P0,0")     # Check for null terminator
        self.output.append(f"    JZ {display_end}")
        self.output.append("    MOV P2,15")    # White color
        self.output.append("    CHAR P0,P2")   # Display character
        self.output.append("    INC P1")       # Next character
        self.output.append(f"    JMP {display_loop}")
        self.output.append(f"{display_end}:")

    def _display_short_string(self, text: str):
        """Display a short string using individual CHAR instructions."""
        for char in text:
            ascii_code = ord(char)
            self.output.append(f"    MOV P0,{ascii_code}")
            self.output.append("    MOV P1,15")  # White color
            self.output.append("    CHAR P0,P1")