; Generated by the Astrid Compiler for Nova-16
ORG 0x1000
start:
MOV SP, 0xFFFF ; Set stack pointer to high memory
MOV FP, 0xFFFF ; Also init frame pointer
CALL func_main
HLT
; Function: main
func_main:
ENTER 4
; var f = ...
; Float literal 1.5 -> Q8.8 384
MOV P0, 384
NEG P0
MOV [0xC000], P0
; var g = ...
; Float literal 0.25 -> Q8.8 64
MOV P1, 64
MOV [0xC002], P1
; If statement
MOV P2, [0xC000]
PUSH P2
MOV P4, [0xC002]
POP P2
; Float (Q8.8) comparison - promote operands
; Signed comparison (two's complement)
CMP P2, P4
JLT cmp_true_2
MOV P2, 0
JMP cmp_end_3
cmp_true_2:
MOV P2, 1
cmp_end_3:
CMP P2, 0
JZ if_end_0
; Function return
MOV P5, 222
MOV P0, P5
MOV R0, P5
MOV SP, FP
POP FP
RET
if_end_0:
; Function return
MOV P6, 9
MOV P0, P6
MOV R0, P6
MOV SP, FP
POP FP
RET