; Generated by the Astrid Compiler for Nova-16
ORG 0x1000
start:
MOV SP, 0xFFFF ; Set stack pointer to high memory
MOV FP, 0xFFFF ; Also init frame pointer
CALL func_main
HLT
; Function: main
func_main:
ENTER 4
; var a = ...
MOV P0, -1
MOV [0xC000], P0
; var b = ...
MOV P1, 5
MOV [0xC002], P1
; If statement
MOV P2, [0xC002]
PUSH P2
MOV P4, -2
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JGT cmp_true_2
MOV P2, 0
JMP cmp_end_3
cmp_true_2:
MOV P2, 1
cmp_end_3:
CMP P2, 0
JZ if_end_0
; If statement
MOV P5, [0xC000]
PUSH P5
MOV P6, 0
POP P5
; Signed comparison (two's complement)
CMP P5, P6
JLT cmp_true_6
MOV P5, 0
JMP cmp_end_7
cmp_true_6:
MOV P5, 1
cmp_end_7:
CMP P5, 0
JZ if_end_4
; Function return
MOV P7, 111
MOV P0, P7
MOV R0, P7
MOV SP, FP
POP FP
RET
if_end_4:
if_end_0:
; Function return
MOV P0, 9
MOV R0, P0
MOV SP, FP
POP FP
RET