; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV VM,0
    MOV VL,0
    MOV VX,0
    MOV VY,0
    MOV P0,0
    SFILL P0
    ; A = 
    MOV P0,42
    ; Store P0 into A
    MOV [0x2000],P0
    ; B = 
    MOV P0,24
    ; Store P0 into B
    MOV [0x2002],P0
    ; Disp
    MOV VX,0
    MOV VY,0
    MOV VL,0
    ; Display 'A'
    MOV P0,65
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display '='
    MOV P0,61
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ADD VY,8
    MOV VX,0
    ; Load A into P0
    MOV P0,[0x2000]
    ; Display number (simplified)
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Disp
    MOV VX,0
    MOV VY,8
    MOV VL,0
    ; Display 'B'
    MOV P0,66
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display '='
    MOV P0,61
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ADD VY,8
    MOV VX,0
    ; Load B into P0
    MOV P0,[0x2002]
    ; Display number (simplified)
    MOV P1,7
    CHAR P0,P1
    ADD VX,8

; Program end - infinite loop to keep display visible
halt:
JMP halt
ORG 0x2000
DW 0  ; Variable A
ORG 0x2002
DW 0  ; Variable B

ORG 0x1000