; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,0
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display 'H'
    MOV P0,72
    MOV P1,15
    CHAR P0,P1
    ; Display 'E'
    MOV P0,69
    MOV P1,15
    CHAR P0,P1
    ; Display 'L'
    MOV P0,76
    MOV P1,15
    CHAR P0,P1
    ; Display 'L'
    MOV P0,76
    MOV P1,15
    CHAR P0,P1
    ; Display 'O'
    MOV P0,79
    MOV P1,15
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    ; Display 'W'
    MOV P0,87
    MOV P1,15
    CHAR P0,P1
    ; Display 'O'
    MOV P0,79
    MOV P1,15
    CHAR P0,P1
    ; Display 'R'
    MOV P0,82
    MOV P1,15
    CHAR P0,P1
    ; Display 'L'
    MOV P0,76
    MOV P1,15
    CHAR P0,P1
    ; Display 'D'
    MOV P0,68
    MOV P1,15
    CHAR P0,P1
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,8
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display 'T'
    MOV P0,84
    MOV P1,15
    CHAR P0,P1
    ; Display 'E'
    MOV P0,69
    MOV P1,15
    CHAR P0,P1
    ; Display 'S'
    MOV P0,83
    MOV P1,15
    CHAR P0,P1
    ; Display 'T'
    MOV P0,84
    MOV P1,15
    CHAR P0,P1
    ; Display 'I'
    MOV P0,73
    MOV P1,15
    CHAR P0,P1
    ; Display 'N'
    MOV P0,78
    MOV P1,15
    CHAR P0,P1
    ; Display 'G'
    MOV P0,71
    MOV P1,15
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    ; Display 'D'
    MOV P0,68
    MOV P1,15
    CHAR P0,P1
    ; Display 'I'
    MOV P0,73
    MOV P1,15
    CHAR P0,P1
    ; Display 'S'
    MOV P0,83
    MOV P1,15
    CHAR P0,P1
    ; Display 'P'
    MOV P0,80
    MOV P1,15
    CHAR P0,P1
    ; Display 'L'
    MOV P0,76
    MOV P1,15
    CHAR P0,P1
    ; Display 'A'
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    ; Display 'Y'
    MOV P0,89
    MOV P1,15
    CHAR P0,P1

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x8000

; String concatenation subroutine
str_concat:
    ; P1 = left string address
    ; Top of stack = right string address
    ; Returns result address in P0
    POP P2
    POP P3
    PUSH P2
    
    ; Allocate space for result string
    MOV P0,0x6000
    MOV P4,P0
    
    ; Copy left string
str_cat_copy_left:
    MOV P5,[P1]
    CMP P5,0
    JZ str_cat_copy_right
    MOV [P4],P5
    INC P1
    INC P4
    JMP str_cat_copy_left
    
str_cat_copy_right:
    MOV P5,[P3]
    CMP P5,0
    JZ str_cat_done
    MOV [P4],P5
    INC P3
    INC P4
    JMP str_cat_copy_right
    
str_cat_done:
    MOV [P4],0
    RET