; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV P0,0
    MOV [0xF102],P0
    MOV [0xF103],P0
    MOV [0xF100],P0
    MOV [0xF101],P0
    SFILL P0
    ; Disp
    MOV P0,0
    MOV [0xF100],P0
    MOV P0,0
    MOV [0xF101],P0
    MOV P0,0
    MOV [0xF103],P0
    ; Display 'S'
    MOV P0,83
    MOV P1,7
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ; Display 'b'
    MOV P0,98
    MOV P1,7
    CHAR P0,P1
    ; Display 'r'
    MOV P0,114
    MOV P1,7
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display 'i'
    MOV P0,105
    MOV P1,7
    CHAR P0,P1
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ; Display 'T'
    MOV P0,84
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Define subroutine DrawStar
sub_DrawStar:
    ; Line
    MOV P0,100
    MOV P1,50
    MOV P2,120
    MOV P3,90
    MOV P4,7
    ; Draw line from (P0,P1) to (P2,P3)
    SLINE P0,P1,P2,P3,P4
    ; Line
    MOV P4,120
    MOV P3,90
    MOV P2,80
    MOV P1,70
    MOV P0,7
    ; Draw line from (P4,P3) to (P2,P1)
    SLINE P4,P3,P2,P1,P0
    ; Line
    MOV P0,80
    MOV P1,70
    MOV P2,140
    MOV P3,70
    MOV P4,7
    ; Draw line from (P0,P1) to (P2,P3)
    SLINE P0,P1,P2,P3,P4
    ; Line
    MOV P4,140
    MOV P3,70
    MOV P2,100
    MOV P1,50
    MOV P0,7
    ; Draw line from (P4,P3) to (P2,P1)
    SLINE P4,P3,P2,P1,P0
    ; Line
    MOV P0,100
    MOV P1,50
    MOV P2,100
    MOV P3,110
    MOV P4,7
    ; Draw line from (P0,P1) to (P2,P3)
    SLINE P0,P1,P2,P3,P4
    ; Return from subroutine
    RET
    ; Define subroutine PlayMelody
sub_PlayMelody:
    ; Sound
    MOV P4,261
    MOV P3,200
    MOV P2,100
    MOV P1,0
    ; Sound freq=P4, duration=P3, vol=P2, wave=P1
    MOV SA,0x2000
    MOV SF,P4
    MOV SV,P2
    MOV SW,P1
    SPLAY
    ; Wait for duration
    MOV P2,P3
sound_wait_loop:
    DEC P2
    JNZ sound_wait_loop
    SSTOP
    ; Sound
    MOV P1,293
    MOV P2,200
    MOV P3,100
    MOV P4,0
    ; Sound freq=P1, duration=P2, vol=P3, wave=P4
    MOV SA,0x2000
    MOV SF,P1
    MOV SV,P3
    MOV SW,P4
    SPLAY
    ; Wait for duration
    MOV P2,P2
sound_wait_loop:
    DEC P2
    JNZ sound_wait_loop
    SSTOP
    ; Sound
    MOV P4,329
    MOV P3,200
    MOV P2,100
    MOV P1,0
    ; Sound freq=P4, duration=P3, vol=P2, wave=P1
    MOV SA,0x2000
    MOV SF,P4
    MOV SV,P2
    MOV SW,P1
    SPLAY
    ; Wait for duration
    MOV P2,P3
sound_wait_loop:
    DEC P2
    JNZ sound_wait_loop
    SSTOP
    ; Sound
    MOV P1,349
    MOV P2,200
    MOV P3,100
    MOV P4,0
    ; Sound freq=P1, duration=P2, vol=P3, wave=P4
    MOV SA,0x2000
    MOV SF,P1
    MOV SV,P3
    MOV SW,P4
    SPLAY
    ; Wait for duration
    MOV P2,P2
sound_wait_loop:
    DEC P2
    JNZ sound_wait_loop
    SSTOP
    ; Sound
    MOV P4,392
    MOV P3,200
    MOV P2,100
    MOV P1,0
    ; Sound freq=P4, duration=P3, vol=P2, wave=P1
    MOV SA,0x2000
    MOV SF,P4
    MOV SV,P2
    MOV SW,P1
    SPLAY
    ; Wait for duration
    MOV P2,P3
sound_wait_loop:
    DEC P2
    JNZ sound_wait_loop
    SSTOP
    ; Return from subroutine
    RET
    ; Call subroutine DrawStar
    CALL sub_DrawStar
    ; Call subroutine PlayMelody
    CALL sub_PlayMelody
    ; Disp
    MOV P0,0
    MOV [0xF100],P0
    MOV P0,8
    MOV [0xF101],P0
    MOV P0,0
    MOV [0xF103],P0
    ; Display 'S'
    MOV P0,83
    MOV P1,7
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ; Display 'b'
    MOV P0,98
    MOV P1,7
    CHAR P0,P1
    ; Display 'r'
    MOV P0,114
    MOV P1,7
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display 'i'
    MOV P0,105
    MOV P1,7
    CHAR P0,P1
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ; Display 'c'
    MOV P0,99
    MOV P1,7
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ; Display 'm'
    MOV P0,109
    MOV P1,7
    CHAR P0,P1
    ; Display 'p'
    MOV P0,112
    MOV P1,7
    CHAR P0,P1
    ; Display 'l'
    MOV P0,108
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display 'd'
    MOV P0,100
    MOV P1,7
    CHAR P0,P1
    ; Pause - wait for key press
pause_loop:
    KEYSTAT P0
    CMP P0,0
    JZ pause_loop
    KEYIN P0
    ; End - terminate program
    JMP halt

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x1000