; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; Disp
    ; Display 'Testing TRUE/FALSE constants'
    MOV P0,84
    MOV P1,15
    CHAR P0,P1
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,105
    MOV P1,15
    CHAR P0,P1
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    MOV P0,103
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,84
    MOV P1,15
    CHAR P0,P1
    MOV P0,82
    MOV P1,15
    CHAR P0,P1
    MOV P0,85
    MOV P1,15
    CHAR P0,P1
    MOV P0,69
    MOV P1,15
    CHAR P0,P1
    MOV P0,47
    MOV P1,15
    CHAR P0,P1
    MOV P0,70
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,76
    MOV P1,15
    CHAR P0,P1
    MOV P0,83
    MOV P1,15
    CHAR P0,P1
    MOV P0,69
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,99
    MOV P1,15
    CHAR P0,P1
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,97
    MOV P1,15
    CHAR P0,P1
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; A = expression
    MOV P0,1
    MOV [0x2000],P0
    ; B = expression
    MOV P0,0
    MOV [0x2002],P0
    MOV P0,[0x2000]
    JZ else_1
    ; Disp
    ; Display 'TRUE works!'
    MOV P0,84
    MOV P1,15
    CHAR P0,P1
    MOV P0,82
    MOV P1,15
    CHAR P0,P1
    MOV P0,85
    MOV P1,15
    CHAR P0,P1
    MOV P0,69
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,119
    MOV P1,15
    CHAR P0,P1
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    MOV P0,114
    MOV P1,15
    CHAR P0,P1
    MOV P0,107
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,33
    MOV P1,15
    CHAR P0,P1
    JMP endif_2
else_1:
endif_2:
    MOV P0,[0x2002]
    PUSH P0
    MOV P0,0
    MOV P1,P0
    POP P0
    JZ else_3
    ; Disp
    ; Display 'FALSE works!'
    MOV P0,70
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,76
    MOV P1,15
    CHAR P0,P1
    MOV P0,83
    MOV P1,15
    CHAR P0,P1
    MOV P0,69
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,119
    MOV P1,15
    CHAR P0,P1
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    MOV P0,114
    MOV P1,15
    CHAR P0,P1
    MOV P0,107
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,33
    MOV P1,15
    CHAR P0,P1
    JMP endif_4
else_3:
endif_4:
    ; Disp
    ; Display 'Boolean constants test completed'
    MOV P0,66
    MOV P1,15
    CHAR P0,P1
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    MOV P0,108
    MOV P1,15
    CHAR P0,P1
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    MOV P0,97
    MOV P1,15
    CHAR P0,P1
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,99
    MOV P1,15
    CHAR P0,P1
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,97
    MOV P1,15
    CHAR P0,P1
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,99
    MOV P1,15
    CHAR P0,P1
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    MOV P0,109
    MOV P1,15
    CHAR P0,P1
    MOV P0,112
    MOV P1,15
    CHAR P0,P1
    MOV P0,108
    MOV P1,15
    CHAR P0,P1
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    MOV P0,100
    MOV P1,15
    CHAR P0,P1

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z