; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV VM,0
    MOV VL,0
    MOV VX,0
    MOV VY,0
    MOV P0,0
    SFILL P0
    ; Disp
    MOV VX,0
    MOV VY,0
    MOV VL,0
    ; Display 'L'
    MOV P0,76
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'I'
    MOV P0,73
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'N'
    MOV P0,78
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'E'
    MOV P0,69
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display '1'
    MOV P0,49
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Disp
    MOV VX,0
    MOV VY,8
    MOV VL,0
    ; Display 'L'
    MOV P0,76
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'I'
    MOV P0,73
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'N'
    MOV P0,78
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'E'
    MOV P0,69
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display '2'
    MOV P0,50
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Disp
    MOV VX,0
    MOV VY,16
    MOV VL,0
    ; Display 'L'
    MOV P0,76
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'I'
    MOV P0,73
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'N'
    MOV P0,78
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'E'
    MOV P0,69
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display '3'
    MOV P0,51
    MOV P1,7
    CHAR P0,P1
    ADD VX,8

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x1000