; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; A = 
    MOV P0,42
    ; Store P0 into A
    MOV [0x2000],P0
    ; B = 
    MOV P0,1000
    ; Store P0 into B
    MOV [0x2002],P0
    ; C = 
    ; Load A into P0
    MOV P0,[0x2000]
    ; Load B into P1
    MOV P1,[0x2002]
    ADD P0,P1
    ; Store P0 into C
    MOV [0x2004],P0
    ; L1 = 
    MOV P0,10
    ; Store to L1(0)
    LEA P2,[12288 + 0*2]
    MOV [P2],P0
    ; L1 = 
    MOV P0,20
    ; Store to L1(1)
    LEA P2,[12288 + 1*2]
    MOV [P2],P0
    ; L1 = 
    MOV P0,0
    ; Load L1(P0) into P1
    LEA P1,[12288 + P0*2]
    MOV P1,[P1]
    MOV P2,1
    ; Load L1(P2) into P3
    LEA P3,[12288 + P2*2]
    MOV P3,[P3]
    ADD P1,P3
    ; Store to L1(2)
    LEA P2,[12288 + 2*2]
    MOV [P2],P2
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,0
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display 'A'
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    ; Display 'l'
    MOV P0,108
    MOV P1,15
    CHAR P0,P1
    ; Display 'l'
    MOV P0,108
    MOV P1,15
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    ; Display 'a'
    MOV P0,97
    MOV P1,15
    CHAR P0,P1
    ; Display 'd'
    MOV P0,100
    MOV P1,15
    CHAR P0,P1
    ; Display 'd'
    MOV P0,100
    MOV P1,15
    CHAR P0,P1
    ; Display 'r'
    MOV P0,114
    MOV P1,15
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; Display 'i'
    MOV P0,105
    MOV P1,15
    CHAR P0,P1
    ; Display 'n'
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    ; Display 'g'
    MOV P0,103
    MOV P1,15
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    ; Display 'm'
    MOV P0,109
    MOV P1,15
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    ; Display 'd'
    MOV P0,100
    MOV P1,15
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    ; Display 'd'
    MOV P0,100
    MOV P1,15
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,15
    CHAR P0,P1
    ; Display 'c'
    MOV P0,99
    MOV P1,15
    CHAR P0,P1
    ; Display 'c'
    MOV P0,99
    MOV P1,15
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; Display 'f'
    MOV P0,102
    MOV P1,15
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,15
    CHAR P0,P1
    ; Display 'l'
    MOV P0,108
    MOV P1,15
    CHAR P0,P1
    ; Display 'l'
    MOV P0,108
    MOV P1,15
    CHAR P0,P1
    ; Display 'y'
    MOV P0,121
    MOV P1,15
    CHAR P0,P1

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x8000

; String concatenation subroutine
str_concat:
    ; P1 = left string address
    ; Top of stack = right string address
    ; Returns result address in P0
    POP P2
    POP P3
    PUSH P2
    
    ; Allocate space for result string
    MOV P0,0x6000
    MOV P4,P0
    
    ; Copy left string
str_cat_copy_left:
    MOV P5,[P1]
    CMP P5,0
    JZ str_cat_copy_right
    MOV [P4],P5
    INC P1
    INC P4
    JMP str_cat_copy_left
    
str_cat_copy_right:
    MOV P5,[P3]
    CMP P5,0
    JZ str_cat_done
    MOV [P4],P5
    INC P3
    INC P4
    JMP str_cat_copy_right
    
str_cat_done:
    MOV [P4],0
    RET