; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV P0,0
    MOV [0xF102],P0
    MOV [0xF103],P0
    MOV [0xF100],P0
    MOV [0xF101],P0
    SFILL P0
    ; Disp
    MOV P0,0
    MOV [0xF100],P0
    MOV P0,0
    MOV [0xF101],P0
    MOV P0,0
    MOV [0xF103],P0
    ; Display 'S'
    MOV P0,83
    MOV P1,7
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ; Display 'd'
    MOV P0,100
    MOV P1,7
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ; Display 'T'
    MOV P0,84
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ; Display 'S'
    MOV P0,83
    MOV P1,7
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ; Display 'i'
    MOV P0,105
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Play - start sound playback
    SPLAY
    ; Pause - wait for key press
pause_loop:
    KEYSTAT P0
    CMP P0,0
    JZ pause_loop
    KEYIN P0
    ; Sound
    MOV P0,261
    MOV P1,500
    MOV P2,100
    MOV P3,0
    ; Sound freq=P0, duration=P1, vol=P2, wave=P3
    MOV SA,0x2000
    MOV SF,P0
    MOV SV,P2
    MOV SW,P3
    SPLAY
    ; Wait for duration
    MOV P2,P1
sound_wait_loop:
    DEC P2
    JNZ sound_wait_loop
    SSTOP
    ; Pause - wait for key press
pause_loop:
    KEYSTAT P0
    CMP P0,0
    JZ pause_loop
    KEYIN P0
    ; Sound
    MOV P3,293
    MOV P2,500
    MOV P1,120
    MOV P0,1
    ; Sound freq=P3, duration=P2, vol=P1, wave=P0
    MOV SA,0x2000
    MOV SF,P3
    MOV SV,P1
    MOV SW,P0
    SPLAY
    ; Wait for duration
    MOV P2,P2
sound_wait_loop:
    DEC P2
    JNZ sound_wait_loop
    SSTOP
    ; Pause - wait for key press
pause_loop:
    KEYSTAT P0
    CMP P0,0
    JZ pause_loop
    KEYIN P0
    ; Sound
    MOV P0,329
    MOV P1,500
    MOV P2,140
    MOV P3,2
    ; Sound freq=P0, duration=P1, vol=P2, wave=P3
    MOV SA,0x2000
    MOV SF,P0
    MOV SV,P2
    MOV SW,P3
    SPLAY
    ; Wait for duration
    MOV P2,P1
sound_wait_loop:
    DEC P2
    JNZ sound_wait_loop
    SSTOP
    ; Pause - wait for key press
pause_loop:
    KEYSTAT P0
    CMP P0,0
    JZ pause_loop
    KEYIN P0
    ; Stop - stop sound playback
    SSTOP
    ; Disp
    MOV P0,0
    MOV [0xF100],P0
    MOV P0,8
    MOV [0xF101],P0
    MOV P0,0
    MOV [0xF103],P0
    ; Display 'S'
    MOV P0,83
    MOV P1,7
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ; Display 'd'
    MOV P0,100
    MOV P1,7
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ; Display 'c'
    MOV P0,99
    MOV P1,7
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ; Display 'm'
    MOV P0,109
    MOV P1,7
    CHAR P0,P1
    ; Display 'p'
    MOV P0,112
    MOV P1,7
    CHAR P0,P1
    ; Display 'l'
    MOV P0,108
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ; Display 'd'
    MOV P0,100
    MOV P1,7
    CHAR P0,P1
    ; End - terminate program
    JMP halt

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x1000