; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; DIM TEST_ARRAY(LiteralExpr(value=10)) - array declaration
    MOV P0,10
    MOV P0,0
    MOV [0x2000],P0
for_1:
    MOV P0,[0x2000]
    MOV P0,10
    MOV P1,P0
    MOV P0,[0x2000]
    CMP P0,P1
    JGE next_2
    ; Complex assignment not implemented yet
    MOV P0,[0x2000]
    MOV P1,1
    ADD P0,P1
    MOV [0x2000],P0
    JMP for_1
next_2:
    ; Complex assignment not implemented yet
    ; A = expression
    MOV [0x2002],P0
    ; X = expression
    MOV P0,10
    PUSH P0
    MOV P0,20
    MOV P1,P0
    POP P0
    CMP P0,P1
    JLT min_done_2
    MOV P0,P1
min_done_2:
    MOV [0x2004],P0
    ; Y = expression
    MOV P0,10
    PUSH P0
    MOV P0,20
    MOV P1,P0
    POP P0
    CMP P0,P1
    JGT max_done_3
    MOV P0,P1
max_done_3:
    MOV [0x2006],P0
    ; S1 = expression
    MOV [0x2008],P0
    ; S2 = expression
    MOV [0x200A],P0
    JMP MEMSWAP
    ; Disp
    ; Display 'ARRAY[5] = '
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,82
    MOV P1,15
    CHAR P0,P1
    MOV P0,82
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,89
    MOV P1,15
    CHAR P0,P1
    MOV P0,91
    MOV P1,15
    CHAR P0,P1
    MOV P0,53
    MOV P1,15
    CHAR P0,P1
    MOV P0,93
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    ; Disp
    ; Display 'L1[5] = '
    MOV P0,76
    MOV P1,15
    CHAR P0,P1
    MOV P0,49
    MOV P1,15
    CHAR P0,P1
    MOV P0,91
    MOV P1,15
    CHAR P0,P1
    MOV P0,53
    MOV P1,15
    CHAR P0,P1
    MOV P0,93
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2002]
    ; Disp
    ; Display 'MIN(10,20) = '
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,73
    MOV P1,15
    CHAR P0,P1
    MOV P0,78
    MOV P1,15
    CHAR P0,P1
    MOV P0,40
    MOV P1,15
    CHAR P0,P1
    MOV P0,49
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,44
    MOV P1,15
    CHAR P0,P1
    MOV P0,50
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,41
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2004]
    ; Disp
    ; Display 'MAX(10,20) = '
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,88
    MOV P1,15
    CHAR P0,P1
    MOV P0,40
    MOV P1,15
    CHAR P0,P1
    MOV P0,49
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,44
    MOV P1,15
    CHAR P0,P1
    MOV P0,50
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,41
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2006]

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z