; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; Disp
    ; Display 'Testing MIN/MAX functions'
    MOV P0,84
    MOV P1,15
    CHAR P0,P1
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,105
    MOV P1,15
    CHAR P0,P1
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    MOV P0,103
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,73
    MOV P1,15
    CHAR P0,P1
    MOV P0,78
    MOV P1,15
    CHAR P0,P1
    MOV P0,47
    MOV P1,15
    CHAR P0,P1
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,88
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,102
    MOV P1,15
    CHAR P0,P1
    MOV P0,117
    MOV P1,15
    CHAR P0,P1
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    MOV P0,99
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,105
    MOV P1,15
    CHAR P0,P1
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; A = expression
    MOV P0,10
    PUSH P0
    MOV P0,20
    MOV P1,P0
    POP P0
    CMP P0,P1
    JLT min_done_0
    MOV P0,P1
min_done_0:
    MOV [0x2000],P0
    ; Disp
    ; Display 'MIN(10, 20) = '
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,73
    MOV P1,15
    CHAR P0,P1
    MOV P0,78
    MOV P1,15
    CHAR P0,P1
    MOV P0,40
    MOV P1,15
    CHAR P0,P1
    MOV P0,49
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,44
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,50
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,41
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2000]
    ; B = expression
    MOV P0,50
    PUSH P0
    MOV P0,25
    MOV P1,P0
    POP P0
    CMP P0,P1
    JLT min_done_1
    MOV P0,P1
min_done_1:
    MOV [0x2002],P0
    ; Disp
    ; Display 'MIN(50, 25) = '
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,73
    MOV P1,15
    CHAR P0,P1
    MOV P0,78
    MOV P1,15
    CHAR P0,P1
    MOV P0,40
    MOV P1,15
    CHAR P0,P1
    MOV P0,53
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,44
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,50
    MOV P1,15
    CHAR P0,P1
    MOV P0,53
    MOV P1,15
    CHAR P0,P1
    MOV P0,41
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2002]
    ; C = expression
    MOV P0,10
    PUSH P0
    MOV P0,20
    MOV P1,P0
    POP P0
    CMP P0,P1
    JGT max_done_2
    MOV P0,P1
max_done_2:
    MOV [0x2004],P0
    ; Disp
    ; Display 'MAX(10, 20) = '
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,88
    MOV P1,15
    CHAR P0,P1
    MOV P0,40
    MOV P1,15
    CHAR P0,P1
    MOV P0,49
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,44
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,50
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,41
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2004]
    ; D = expression
    MOV P0,50
    PUSH P0
    MOV P0,25
    MOV P1,P0
    POP P0
    CMP P0,P1
    JGT max_done_3
    MOV P0,P1
max_done_3:
    MOV [0x2006],P0
    ; Disp
    ; Display 'MAX(50, 25) = '
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,88
    MOV P1,15
    CHAR P0,P1
    MOV P0,40
    MOV P1,15
    CHAR P0,P1
    MOV P0,53
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,44
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,50
    MOV P1,15
    CHAR P0,P1
    MOV P0,53
    MOV P1,15
    CHAR P0,P1
    MOV P0,41
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2006]
    ; X = expression
    MOV P0,15
    MOV [0x2008],P0
    ; Y = expression
    MOV P0,30
    MOV [0x200A],P0
    ; E = expression
    MOV P0,[0x2008]
    PUSH P0
    MOV P0,5
    MOV P1,P0
    POP P0
    ADD P0,P1
    PUSH P0
    MOV P0,[0x200A]
    PUSH P0
    MOV P0,10
    MOV P1,P0
    POP P0
    SUB P0,P1
    MOV P1,P0
    POP P0
    CMP P0,P1
    JLT min_done_4
    MOV P0,P1
min_done_4:
    MOV [0x200C],P0
    ; Disp
    ; Display 'MIN(X+5, Y-10) = '
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,73
    MOV P1,15
    CHAR P0,P1
    MOV P0,78
    MOV P1,15
    CHAR P0,P1
    MOV P0,40
    MOV P1,15
    CHAR P0,P1
    MOV P0,88
    MOV P1,15
    CHAR P0,P1
    MOV P0,43
    MOV P1,15
    CHAR P0,P1
    MOV P0,53
    MOV P1,15
    CHAR P0,P1
    MOV P0,44
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,89
    MOV P1,15
    CHAR P0,P1
    MOV P0,45
    MOV P1,15
    CHAR P0,P1
    MOV P0,49
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,41
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x200C]
    ; F = expression
    MOV P0,[0x2008]
    PUSH P0
    MOV P0,2
    MOV P1,P0
    POP P0
    MUL P0,P1
    PUSH P0
    MOV P0,[0x200A]
    PUSH P0
    MOV P0,2
    MOV P1,P0
    POP P0
    DIV P0,P1
    MOV P1,P0
    POP P0
    CMP P0,P1
    JGT max_done_5
    MOV P0,P1
max_done_5:
    MOV [0x200E],P0
    ; Disp
    ; Display 'MAX(X*2, Y/2) = '
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,88
    MOV P1,15
    CHAR P0,P1
    MOV P0,40
    MOV P1,15
    CHAR P0,P1
    MOV P0,88
    MOV P1,15
    CHAR P0,P1
    MOV P0,42
    MOV P1,15
    CHAR P0,P1
    MOV P0,50
    MOV P1,15
    CHAR P0,P1
    MOV P0,44
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,89
    MOV P1,15
    CHAR P0,P1
    MOV P0,47
    MOV P1,15
    CHAR P0,P1
    MOV P0,50
    MOV P1,15
    CHAR P0,P1
    MOV P0,41
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x200E]
    ; Disp
    ; Display 'MIN/MAX tests complete'
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,73
    MOV P1,15
    CHAR P0,P1
    MOV P0,78
    MOV P1,15
    CHAR P0,P1
    MOV P0,47
    MOV P1,15
    CHAR P0,P1
    MOV P0,77
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,88
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,99
    MOV P1,15
    CHAR P0,P1
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    MOV P0,109
    MOV P1,15
    CHAR P0,P1
    MOV P0,112
    MOV P1,15
    CHAR P0,P1
    MOV P0,108
    MOV P1,15
    CHAR P0,P1
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    ; Pause - halt execution
pause_loop:
    JMP pause_loop

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z