; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV VM,0
    MOV VL,0
    MOV VX,0
    MOV VY,0
    MOV P0,0
    SFILL P0
    ; Prompt
    ; Prompt A
    ; Read input string and convert with STOI
    PUSH P1
    PUSH P2
    MOV P1,0x6000
    MOV P2,0
prompt_loop:
    KEYSTAT P0
    CMP P0,0
    JZ prompt_loop
    KEYIN P0
    ; Check for Enter (13)
    CMP P0,13
    JZ prompt_convert
    ; Store character in buffer
    MOV [P1+P2],P0
    INC P2
    JMP prompt_loop
prompt_convert:
    ; Null terminate string
    MOV [P1+P2],0
    ; Convert string to integer using STOI
    STOI P0,P1
    POP P2
    POP P1
    ; Store P0 into A
    MOV [0x2000],P0
    ; Disp
    MOV VX,0
    MOV VY,0
    MOV VL,0
    ; Display 'Y'
    MOV P0,89
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'r'
    MOV P0,114
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'd'
    MOV P0,100
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ':'
    MOV P0,58
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ADD VY,8
    MOV VX,0
    ; Load A into P0
    MOV P0,[0x2000]
    ; Display number (using ITOS)
    ; Save registers
    PUSH P0
    PUSH P1
    PUSH P2
    ; Convert number to string using ITOS
    MOV P1,0x6000
    ITOS P1,P0
    ; Display the string
    MOV P2,0
dn_display_loop:
    MOV P0,[P1+P2]
    CMP P0,0
    JZ dn_done
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    INC P2
    JMP dn_display_loop
dn_done:
    ; Restore registers
    POP P2
    POP P1
    POP P0

; Program end - infinite loop to keep display visible
halt:
JMP halt
ORG 0x2000
DW 0  ; Variable A

ORG 0x1000