; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; Disp

; String literal: 'Testing sprites and layers'
ORG 0x3000
    DB 84
    DB 101
    DB 115
    DB 116
    DB 105
    DB 110
    DB 103
    DB 32
    DB 115
    DB 112
    DB 114
    DB 105
    DB 116
    DB 101
    DB 115
    DB 32
    DB 97
    DB 110
    DB 100
    DB 32
    DB 108
    DB 97
    DB 121
    DB 101
    DB 114
    DB 115
    DB 0  ; null terminator
    MOV P0,0x3000
    ; Display string at address in P0
    MOV P1,P0
display_loop_0:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_0
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_0
display_end_0:
    ; VL = expression
    MOV P0,0
    MOV [0x2000],P0
    MOV P0,0
    MOV VX,P0
    MOV P0,0
    MOV VY,P0
    MOV P0,[0x2002]
    MOV VL,P0
    MOV P0,256
    PUSH P0
    MOV P0,256
    MOV P1,P0
    POP P0
    SRECT P0,P1
    ; VL = expression
    MOV P0,1
    MOV [0x2000],P0
    ; Disp

; String literal: 'Layer 1 operations'
ORG 0x3100
    DB 76
    DB 97
    DB 121
    DB 101
    DB 114
    DB 32
    DB 49
    DB 32
    DB 111
    DB 112
    DB 101
    DB 114
    DB 97
    DB 116
    DB 105
    DB 111
    DB 110
    DB 115
    DB 0  ; null terminator
    MOV P0,0x3100
    ; Display string at address in P0
    MOV P1,P0
display_loop_1:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_1
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_1
display_end_1:
    MOV P0,50
    MOV VY,P0
    MOV P0,50
    MOV VX,P0
    MOV P0,[0x2004]
    MOV VL,P0
    MOV VM,0
    SWRITE P0
    MOV P0,60
    MOV VX,P0
    MOV P0,60
    MOV VY,P0
    MOV P0,[0x2006]
    MOV VL,P0
    MOV P0,40
    PUSH P0
    MOV P0,30
    MOV P1,P0
    POP P0
    SRECT P0,P1
    ; VL = expression
    MOV P0,2
    MOV [0x2000],P0
    ; Disp

; String literal: 'Layer 2 operations'
ORG 0x3200
    DB 76
    DB 97
    DB 121
    DB 101
    DB 114
    DB 32
    DB 50
    DB 32
    DB 111
    DB 112
    DB 101
    DB 114
    DB 97
    DB 116
    DB 105
    DB 111
    DB 110
    DB 115
    DB 0  ; null terminator
    MOV P0,0x3200
    ; Display string at address in P0
    MOV P1,P0
display_loop_2:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_2
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_2
display_end_2:
    MOV P0,100
    MOV VY,P0
    MOV P0,100
    MOV VX,P0
    MOV P0,[0x2008]
    MOV VL,P0
    MOV VM,0
    SWRITE P0
    MOV P0,110
    MOV VX,P0
    MOV P0,110
    MOV VY,P0
    MOV P0,[0x200A]
    MOV VL,P0
    MOV P0,40
    PUSH P0
    MOV P0,30
    MOV P1,P0
    POP P0
    SRECT P0,P1
    ; VL = expression
    MOV P0,3
    MOV [0x2000],P0
    ; Disp

; String literal: 'Layer 3 operations'
ORG 0x3300
    DB 76
    DB 97
    DB 121
    DB 101
    DB 114
    DB 32
    DB 51
    DB 32
    DB 111
    DB 112
    DB 101
    DB 114
    DB 97
    DB 116
    DB 105
    DB 111
    DB 110
    DB 115
    DB 0  ; null terminator
    MOV P0,0x3300
    ; Display string at address in P0
    MOV P1,P0
display_loop_3:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_3
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_3
display_end_3:
    MOV P0,150
    MOV VY,P0
    MOV P0,150
    MOV VX,P0
    MOV P0,[0x200C]
    MOV VL,P0
    MOV VM,0
    SWRITE P0
    MOV P0,160
    MOV VX,P0
    MOV P0,160
    MOV VY,P0
    MOV P0,[0x200E]
    MOV VL,P0
    MOV P0,40
    PUSH P0
    MOV P0,30
    MOV P1,P0
    POP P0
    SRECT P0,P1
    ; Disp

; String literal: 'Sprite control blocks:'
ORG 0x3400
    DB 83
    DB 112
    DB 114
    DB 105
    DB 116
    DB 101
    DB 32
    DB 99
    DB 111
    DB 110
    DB 116
    DB 114
    DB 111
    DB 108
    DB 32
    DB 98
    DB 108
    DB 111
    DB 99
    DB 107
    DB 115
    DB 58
    DB 0  ; null terminator
    MOV P0,0x3400
    ; Display string at address in P0
    MOV P1,P0
display_loop_4:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_4
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_4
display_end_4:
    ; Disp

; String literal: 'Sprite 0: 0xF000'
ORG 0x3500
    DB 83
    DB 112
    DB 114
    DB 105
    DB 116
    DB 101
    DB 32
    DB 48
    DB 58
    DB 32
    DB 48
    DB 120
    DB 70
    DB 48
    DB 48
    DB 48
    DB 0  ; null terminator
    MOV P0,0x3500
    ; Display string at address in P0
    MOV P1,P0
display_loop_5:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_5
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_5
display_end_5:
    ; Disp

; String literal: 'Sprite 1: 0xF010'
ORG 0x3600
    DB 83
    DB 112
    DB 114
    DB 105
    DB 116
    DB 101
    DB 32
    DB 49
    DB 58
    DB 32
    DB 48
    DB 120
    DB 70
    DB 48
    DB 49
    DB 48
    DB 0  ; null terminator
    MOV P0,0x3600
    ; Display string at address in P0
    MOV P1,P0
display_loop_6:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_6
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_6
display_end_6:
    ; Disp

; String literal: 'Sprite 15: 0xF0F0'
ORG 0x3700
    DB 83
    DB 112
    DB 114
    DB 105
    DB 116
    DB 101
    DB 32
    DB 49
    DB 53
    DB 58
    DB 32
    DB 48
    DB 120
    DB 70
    DB 48
    DB 70
    DB 48
    DB 0  ; null terminator
    MOV P0,0x3700
    ; Display string at address in P0
    MOV P1,P0
display_loop_7:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_7
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_7
display_end_7:
    ; VM = expression
    MOV P0,0
    MOV [0x2010],P0
    MOV P0,200
    MOV VY,P0
    MOV P0,200
    MOV VX,P0
    MOV P0,[0x2012]
    MOV VL,P0
    MOV VM,0
    SWRITE P0
    ; VM = expression
    MOV P0,1
    MOV [0x2010],P0
    ; VX = expression
    MOV P0,220
    MOV [0x2014],P0
    ; VY = expression
    MOV P0,220
    MOV [0x2016],P0
    ; VC = expression
    MOV P0,[0x2012]
    MOV [0x2018],P0
    ; Disp

; String literal: 'Sprites and layers test complete'
ORG 0x3800
    DB 83
    DB 112
    DB 114
    DB 105
    DB 116
    DB 101
    DB 115
    DB 32
    DB 97
    DB 110
    DB 100
    DB 32
    DB 108
    DB 97
    DB 121
    DB 101
    DB 114
    DB 115
    DB 32
    DB 116
    DB 101
    DB 115
    DB 116
    DB 32
    DB 99
    DB 111
    DB 109
    DB 112
    DB 108
    DB 101
    DB 116
    DB 101
    DB 0  ; null terminator
    MOV P0,0x3800
    ; Display string at address in P0
    MOV P1,P0
display_loop_8:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_8
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_8
display_end_8:

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z