; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; A = expression
    MOV P0,5
    MOV [0x2000],P0
    ; B = expression
    MOV P0,10
    MOV [0x2002],P0
    ; C = expression
    MOV P0,2
    PUSH P0
    MOV P0,[0x2002]
    POP P1
    MUL P0,P1
    PUSH P0
    MOV P0,[0x2000]
    POP P1
    ADD P0,P1
    MOV [0x2004],P0
    ; Disp

; String literal: 'Result:'
ORG 0x3000
    DB 82
    DB 101
    DB 115
    DB 117
    DB 108
    DB 116
    DB 58
    DB 0  ; null terminator
    MOV P0,0x3000
    ; Display string at address in P0
    MOV P1,P0
display_loop_0:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_0
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_0
display_end_0:
    MOV P0,[0x2004]
    ; Display string at address in P0
    MOV P1,P0
display_loop_1:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_1
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_1
display_end_1:

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z