; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; Disp

; String literal: 'Memory Operations Test'
ORG 0x3000
    DB 77
    DB 101
    DB 109
    DB 111
    DB 114
    DB 121
    DB 32
    DB 79
    DB 112
    DB 101
    DB 114
    DB 97
    DB 116
    DB 105
    DB 111
    DB 110
    DB 115
    DB 32
    DB 84
    DB 101
    DB 115
    DB 116
    DB 0  ; null terminator
    MOV P0,0x3000
    ; Display string at address in P0
    MOV P1,P0
display_loop_0:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_0
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_0
display_end_0:
    ; BASE_ADDR = expression
    MOV P0,12288
    MOV [0x2000],P0
    ; TEST_SIZE = expression
    MOV P0,100
    MOV [0x2002],P0
    ; DEST_ADDR = expression
    MOV P0,16384
    MOV [0x2004],P0
    ; I = expression
    MOV P0,0
    MOV [0x2006],P0
    ; VALUE = expression
    MOV P0,0
    MOV [0x2008],P0
    ; ORIGINAL = expression
    MOV P0,0
    MOV [0x200A],P0
    ; COPY = expression
    MOV P0,0
    MOV [0x200C],P0
    ; ERRORS = expression
    MOV P0,0
    MOV [0x200E],P0
    ; Disp

; String literal: 'Filling memory with pattern'
ORG 0x3100
    DB 70
    DB 105
    DB 108
    DB 108
    DB 105
    DB 110
    DB 103
    DB 32
    DB 109
    DB 101
    DB 109
    DB 111
    DB 114
    DB 121
    DB 32
    DB 119
    DB 105
    DB 116
    DB 104
    DB 32
    DB 112
    DB 97
    DB 116
    DB 116
    DB 101
    DB 114
    DB 110
    DB 0  ; null terminator
    MOV P0,0x3100
    ; Display string at address in P0
    MOV P1,P0
display_loop_1:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_1
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_1
display_end_1:
    MOV P0,0
    MOV [0x2006],P0
for_3:
    MOV P0,[0x2006]
    MOV P0,1
    PUSH P0
    MOV P0,[0x2002]
    POP P1
    SUB P0,P1
    ADD P0,1
    MOV P1,P0
    MOV P0,[0x2006]
    CMP P0,P1
    JGE next_4
    ; VALUE = expression
    MOV P0,256
    PUSH P0
    MOV P0,[0x2006]
    POP P1
    MOD P0,P1
    MOV [0x2008],P0
    MOV P0,1
    PUSH P0
    MOV P0,[0x2008]
    PUSH P0
    MOV P0,[0x2006]
    PUSH P0
    MOV P0,[0x2000]
    POP P1
    ADD P0,P1
    MEMSET P0,P1,P2
    ADD SP,4
    MOV P0,[0x2006]
    MOV P1,1
    ADD P0,P1
    MOV [0x2006],P0
    JMP for_3
next_4:
    JMP MEMCPY
    ; Disp

; String literal: 'Verifying memory copy'
ORG 0x3200
    DB 86
    DB 101
    DB 114
    DB 105
    DB 102
    DB 121
    DB 105
    DB 110
    DB 103
    DB 32
    DB 109
    DB 101
    DB 109
    DB 111
    DB 114
    DB 121
    DB 32
    DB 99
    DB 111
    DB 112
    DB 121
    DB 0  ; null terminator
    MOV P0,0x3200
    ; Display string at address in P0
    MOV P1,P0
display_loop_4:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_4
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_4
display_end_4:
    ; ERRORS = expression
    MOV P0,0
    MOV [0x200E],P0
    MOV P0,0
    MOV [0x2006],P0
for_6:
    MOV P0,[0x2006]
    MOV P0,1
    PUSH P0
    MOV P0,[0x2002]
    POP P1
    SUB P0,P1
    ADD P0,1
    MOV P1,P0
    MOV P0,[0x2006]
    CMP P0,P1
    JGE next_7
    ; ORIGINAL = expression
    MOV P0,1
    PUSH P0
    MOV P0,[0x2006]
    PUSH P0
    MOV P0,[0x2000]
    POP P1
    ADD P0,P1
    PUSH P0
    MOV P0,[0x2006]
    PUSH P0
    MOV P0,[0x2000]
    POP P1
    ADD P0,P1
    MEMCMP P0,P1,P2
    ADD SP,4
    MOV [0x200A],P0
    ; COPY = expression
    MOV P0,1
    PUSH P0
    MOV P0,[0x2006]
    PUSH P0
    MOV P0,[0x2004]
    POP P1
    ADD P0,P1
    PUSH P0
    MOV P0,[0x2006]
    PUSH P0
    MOV P0,[0x2004]
    POP P1
    ADD P0,P1
    MEMCMP P0,P1,P2
    ADD SP,4
    MOV [0x200C],P0
    MOV P0,[0x200C]
    PUSH P0
    MOV P0,[0x200A]
    POP P1
    CMP P0,P1
    MOV P0,0
    JZ cmp_done_9
    MOV P0,1
cmp_done_9:
    JZ else_8
    ; ERRORS = expression
    MOV P0,1
    PUSH P0
    MOV P0,[0x200E]
    POP P1
    ADD P0,P1
    MOV [0x200E],P0
    JMP endif_9
else_8:
endif_9:
    MOV P0,[0x2006]
    MOV P1,1
    ADD P0,P1
    MOV [0x2006],P0
    JMP for_6
next_7:
    MOV P0,0
    PUSH P0
    MOV P0,[0x200E]
    POP P1
    CMP P0,P1
    MOV P0,0
    JNZ cmp_done_12
    MOV P0,1
cmp_done_12:
    JZ else_11
    ; Disp

; String literal: 'Memory copy successful!'
ORG 0x3300
    DB 77
    DB 101
    DB 109
    DB 111
    DB 114
    DB 121
    DB 32
    DB 99
    DB 111
    DB 112
    DB 121
    DB 32
    DB 115
    DB 117
    DB 99
    DB 99
    DB 101
    DB 115
    DB 115
    DB 102
    DB 117
    DB 108
    DB 33
    DB 0  ; null terminator
    MOV P0,0x3300
    ; Display string at address in P0
    MOV P1,P0
display_loop_13:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_13
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_13
display_end_13:
    JMP endif_12
else_11:
    ; Disp

; String literal: 'Memory copy errors:'
ORG 0x3400
    DB 77
    DB 101
    DB 109
    DB 111
    DB 114
    DB 121
    DB 32
    DB 99
    DB 111
    DB 112
    DB 121
    DB 32
    DB 101
    DB 114
    DB 114
    DB 111
    DB 114
    DB 115
    DB 58
    DB 0  ; null terminator
    MOV P0,0x3400
    ; Display string at address in P0
    MOV P1,P0
display_loop_14:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_14
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_14
display_end_14:
    MOV P0,[0x200E]
    ; Display string at address in P0
    MOV P1,P0
display_loop_15:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_15
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_15
display_end_15:
endif_12:
    MOV P0,10
    PUSH P0
    MOV P0,[0x2002]
    POP P1
    SUB P0,P1
    PUSH P0
    MOV P0,[0x2000]
    PUSH P0
    MOV P0,10
    PUSH P0
    MOV P0,[0x2000]
    POP P1
    ADD P0,P1
    MEMMOVE P0,P1,P2
    ADD SP,4
    ; Disp

; String literal: 'Memory operations test complete!'
ORG 0x3500
    DB 77
    DB 101
    DB 109
    DB 111
    DB 114
    DB 121
    DB 32
    DB 111
    DB 112
    DB 101
    DB 114
    DB 97
    DB 116
    DB 105
    DB 111
    DB 110
    DB 115
    DB 32
    DB 116
    DB 101
    DB 115
    DB 116
    DB 32
    DB 99
    DB 111
    DB 109
    DB 112
    DB 108
    DB 101
    DB 116
    DB 101
    DB 33
    DB 0  ; null terminator
    MOV P0,0x3500
    ; Display string at address in P0
    MOV P1,P0
display_loop_16:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_16
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_16
display_end_16:
    ; Pause - halt execution
pause_loop:
    JMP pause_loop

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z