; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; A = expression
    MOV P0,10
    MOV [0x2000],P0
    ; B = expression
    MOV P0,5
    MOV [0x2002],P0
    MOV P0,[0x2002]
    PUSH P0
    MOV P0,[0x2000]
    POP P1
    CMP P0,P1
    MOV P0,0
    JGT cmp_done_2
    MOV P0,1
cmp_done_2:
    JZ else_1
    ; Disp

; String literal: 'A is greater'
ORG 0x3000
    DB 65
    DB 32
    DB 105
    DB 115
    DB 32
    DB 103
    DB 114
    DB 101
    DB 97
    DB 116
    DB 101
    DB 114
    DB 0  ; null terminator
    MOV P0,0x3000
    ; Display string at address in P0
    MOV P1,P0
display_loop_3:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_3
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_3
display_end_3:
    JMP endif_2
else_1:
    ; Disp

; String literal: 'B is greater or equal'
ORG 0x3100
    DB 66
    DB 32
    DB 105
    DB 115
    DB 32
    DB 103
    DB 114
    DB 101
    DB 97
    DB 116
    DB 101
    DB 114
    DB 32
    DB 111
    DB 114
    DB 32
    DB 101
    DB 113
    DB 117
    DB 97
    DB 108
    DB 0  ; null terminator
    MOV P0,0x3100
    ; Display string at address in P0
    MOV P1,P0
display_loop_4:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_4
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_4
display_end_4:
endif_2:
    ; C = expression
    MOV P0,3
    MOV [0x2004],P0
    MOV P0,5
    PUSH P0
    MOV P0,[0x2004]
    POP P1
    CMP P0,P1
    MOV P0,0
    JLT cmp_done_7
    MOV P0,1
cmp_done_7:
    JZ else_6
    ; Disp

; String literal: 'C is small'
ORG 0x3200
    DB 67
    DB 32
    DB 105
    DB 115
    DB 32
    DB 115
    DB 109
    DB 97
    DB 108
    DB 108
    DB 0  ; null terminator
    MOV P0,0x3200
    ; Display string at address in P0
    MOV P1,P0
display_loop_8:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_8
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_8
display_end_8:
    JMP endif_7
else_6:
    ; Disp

; String literal: 'C is large'
ORG 0x3300
    DB 67
    DB 32
    DB 105
    DB 115
    DB 32
    DB 108
    DB 97
    DB 114
    DB 103
    DB 101
    DB 0  ; null terminator
    MOV P0,0x3300
    ; Display string at address in P0
    MOV P1,P0
display_loop_9:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_9
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_9
display_end_9:
endif_7:
    ; Disp

; String literal: 'Test complete'
ORG 0x3400
    DB 84
    DB 101
    DB 115
    DB 116
    DB 32
    DB 99
    DB 111
    DB 109
    DB 112
    DB 108
    DB 101
    DB 116
    DB 101
    DB 0  ; null terminator
    MOV P0,0x3400
    ; Display string at address in P0
    MOV P1,P0
display_loop_10:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_10
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_10
display_end_10:

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z