; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV VM,0
    MOV VL,0
    MOV VX,0
    MOV VY,0
    MOV P0,0
    SFILL P0
    ; Disp
    MOV VX,0
    MOV VY,0
    MOV VL,0
    ; Display 'P'
    MOV P0,80
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'r'
    MOV P0,114
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'a'
    MOV P0,97
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'y'
    MOV P0,121
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'k'
    MOV P0,107
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'y'
    MOV P0,121
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'c'
    MOV P0,99
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'i'
    MOV P0,105
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Pause - wait for key press
pause_loop:
    KEYSTAT P0
    CMP P0,0
    JZ pause_loop
    KEYIN P0
    ; Disp
    MOV VX,0
    MOV VY,8
    MOV VL,0
    ; Display 'G'
    MOV P0,71
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'i'
    MOV P0,105
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'g'
    MOV P0,103
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'l'
    MOV P0,108
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'a'
    MOV P0,97
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'b'
    MOV P0,98
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'l'
    MOV P0,108
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Goto test_label
    JMP test_label
    ; Lbl skip_this
skip_this:
    ; Disp
    MOV VX,0
    MOV VY,16
    MOV VL,0
    ; Display 'T'
    MOV P0,84
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'h'
    MOV P0,104
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'i'
    MOV P0,105
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'h'
    MOV P0,104
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'l'
    MOV P0,108
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'd'
    MOV P0,100
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'b'
    MOV P0,98
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 's'
    MOV P0,115
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'k'
    MOV P0,107
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'i'
    MOV P0,105
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'p'
    MOV P0,112
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'p'
    MOV P0,112
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'd'
    MOV P0,100
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Lbl test_label
test_label:
    ; Disp
    MOV VX,0
    MOV VY,24
    MOV VL,0
    ; Display 'M'
    MOV P0,77
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'a'
    MOV P0,97
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'd'
    MOV P0,100
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'i'
    MOV P0,105
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'h'
    MOV P0,104
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'l'
    MOV P0,108
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'a'
    MOV P0,97
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'b'
    MOV P0,98
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'l'
    MOV P0,108
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display '!'
    MOV P0,33
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; End - terminate program
    JMP halt

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x1000