; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; A = expression
    MOV P0,5
    PUSH P0
    MOV P0,10
    MOV P1,P0
    POP P0
    ADD P0,P1
    MOV [0x2000],P0
    ; Disp
    ; Display 'A = 5 + 10 = '
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,53
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,43
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,49
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2000]
    ; B = expression
    MOV P0,[0x2000]
    PUSH P0
    MOV P0,0
    MOV P1,P0
    POP P0
    MUL P0,P1
    MOV [0x2002],P0
    ; Disp
    ; Display 'B = A * 0 = '
    MOV P0,66
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,42
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2002]
    ; C = expression
    MOV P0,[0x2000]
    PUSH P0
    MOV P0,1
    MOV P1,P0
    POP P0
    MUL P0,P1
    MOV [0x2004],P0
    ; Disp
    ; Display 'C = A * 1 = '
    MOV P0,67
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,42
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,49
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2004]
    ; D = expression
    MOV P0,[0x2000]
    PUSH P0
    MOV P0,0
    MOV P1,P0
    POP P0
    ADD P0,P1
    MOV [0x2006],P0
    ; Disp
    ; Display 'D = A + 0 = '
    MOV P0,68
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,65
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,43
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,48
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,61
    MOV P1,15
    CHAR P0,P1
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    MOV P0,[0x2006]

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z