; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Program start
start:
    ; ClrHome
    MOV VM,0
    MOV VL,0
    MOV VX,0
    MOV VY,0
    MOV P0,0
    SFILL P0
    ; Disp
    MOV VX,0
    MOV VY,0
    MOV VL,0
    ; Display 'H'
    MOV P0,72
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'E'
    MOV P0,69
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'L'
    MOV P0,76
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'L'
    MOV P0,76
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'O'
    MOV P0,79
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'W'
    MOV P0,87
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'O'
    MOV P0,79
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'R'
    MOV P0,82
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'L'
    MOV P0,76
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'D'
    MOV P0,68
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Disp
    MOV VX,0
    MOV VY,0
    MOV VL,0
    ; Display 'T'
    MOV P0,84
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'E'
    MOV P0,69
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'S'
    MOV P0,83
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'T'
    MOV P0,84
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'I'
    MOV P0,73
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'N'
    MOV P0,78
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'G'
    MOV P0,71
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'D'
    MOV P0,68
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'I'
    MOV P0,73
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'S'
    MOV P0,83
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'P'
    MOV P0,80
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'L'
    MOV P0,76
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'A'
    MOV P0,65
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'Y'
    MOV P0,89
    MOV P1,7
    CHAR P0,P1
    ADD VX,8

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x1000