; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV VM,0
    MOV VL,0
    MOV VX,0
    MOV VY,0
    MOV P0,0
    SFILL P0
    ; A = 
    MOV P0,42
    ; Store P0 into A
    MOV [0x2000],P0
    ; B = 
    MOV P0,24
    ; Store P0 into B
    MOV [0x2002],P0
    ; Disp
    MOV VX,0
    MOV VY,0
    MOV VL,0
    ; Display 'A'
    MOV P0,65
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display '='
    MOV P0,61
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ADD VY,8
    MOV VX,0
    ; Load A into P0
    MOV P0,[0x2000]
    ; Display number (temporary - raw ASCII)
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Disp
    MOV VX,0
    MOV VY,8
    MOV VL,0
    ; Display 'B'
    MOV P0,66
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display '='
    MOV P0,61
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ADD VY,8
    MOV VX,0
    ; Load B into P0
    MOV P0,[0x2002]
    ; Display number (temporary - raw ASCII)
    MOV P1,7
    CHAR P0,P1
    ADD VX,8

; Program end - infinite loop to keep display visible
halt:
JMP halt

; ===== SUBROUTINES =====

; Number to string conversion
; Input: P0 = number to convert
; Output: string buffer at 0x8000
number_to_string:
    PUSH P1
    PUSH P2
    PUSH P3
    MOV P1,0x8000
    MOV P2,P0
    MOV P3,0
    ; Handle zero case
    CMP P2,0
    JNZ nts_not_zero
    MOV [P1],48
    INC P1
    MOV [P1],0
    JMP nts_done
nts_not_zero:
    ; Handle negative numbers
    CMP P2,0
    JNS nts_positive
    MOV [P1],45
    INC P1
    NEG P2
nts_positive:
    ; Convert to digits (reverse order)
nts_loop:
    MOV P0,P2
    MOD P0,10
    ADD P0,48
    PUSH P0
    INC P3
    DIV P2,10
    CMP P2,0
    JNZ nts_loop
    ; Pop digits in reverse order
nts_reverse:
    POP P0
    MOV [P1],P0
    INC P1
    DEC P3
    CMP P3,0
    JNZ nts_reverse
    MOV [P1],0
nts_done:
    POP P3
    POP P2
    POP P1
    RET

; Display string from buffer
; Input: string at 0x8000
display_string:
    PUSH P0
    PUSH P1
    PUSH P2
    MOV P1,0x8000
ds_loop:
    MOV P0,[P1]
    CMP P0,0
    JZ ds_done
    MOV P2,7
    CHAR P0,P2
    ADD VX,8
    INC P1
    JMP ds_loop
ds_done:
    POP P2
    POP P1
    POP P0
    RET

; Read number from keyboard
; Output: P0 = entered number
read_number:
    PUSH P1
    PUSH P2
    PUSH P3
    MOV P0,0
    MOV P1,0
rn_loop:
    KEYSTAT P2
    CMP P2,0
    JZ rn_loop
    KEYIN P2
    ; Check for Enter (13)
    CMP P2,13
    JZ rn_done
    ; Check for minus sign
    CMP P2,45
    JNZ rn_not_minus
    CMP P1,0
    JNZ rn_loop
    MOV P1,1
    JMP rn_loop
rn_not_minus:
    ; Check if digit
    CMP P2,48
    JC rn_loop
    CMP P2,57
    JNC rn_loop
    ; Valid digit, add to result
    SUB P2,48
    MOV P3,P0
    MUL P3,10
    ADD P0,P3
    ADD P0,P2
    JMP rn_loop
rn_done:
    ; Apply sign if negative
    CMP P1,0
    JZ rn_positive
    NEG P0
rn_positive:
    POP P3
    POP P2
    POP P1
    RET
ORG 0x2000
DW 0  ; Variable A
ORG 0x2002
DW 0  ; Variable B

ORG 0x1000