; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; Disp

; String literal: 'Testing RIGHT, MID, INSTR functions'
ORG 0x3000
    DB 84
    DB 101
    DB 115
    DB 116
    DB 105
    DB 110
    DB 103
    DB 32
    DB 82
    DB 73
    DB 71
    DB 72
    DB 84
    DB 44
    DB 32
    DB 77
    DB 73
    DB 68
    DB 44
    DB 32
    DB 73
    DB 78
    DB 83
    DB 84
    DB 82
    DB 32
    DB 102
    DB 117
    DB 110
    DB 99
    DB 116
    DB 105
    DB 111
    DB 110
    DB 115
    DB 0  ; null terminator
    MOV P0,0x3000
    ; Display string at address in P0
    MOV P1,P0
display_loop_0:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_0
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_0
display_end_0:
    ; Str1 = expression

; String literal: 'Hello World'
ORG 0x3100
    DB 72
    DB 101
    DB 108
    DB 108
    DB 111
    DB 32
    DB 87
    DB 111
    DB 114
    DB 108
    DB 100
    DB 0  ; null terminator
    MOV P0,0x3100
    MOV [0x2000],P0
    ; Str2 = expression
    MOV P0,[0x2000]
    PUSH P0
    MOV P0,5
    MOV P2,P0
    POP P0
    STRLEN P0
    MOV P3,R0
    MOV P1,0x4001
    MOV P4,0
    SUB P3,P2
right_loop_2:
    CMP P4,P2
    JGE right_end_2
    MOV P5,[P0+P3+P4]
    MOV [P1+P4],P5
    INC P4
    JMP right_loop_2
right_end_2:
    MOV [P1+P4],0
    MOV P0,0x4001
    MOV [0x2002],P0
    ; Disp

; String literal: "RIGHT('Hello World', 5):"
ORG 0x3200
    DB 82
    DB 73
    DB 71
    DB 72
    DB 84
    DB 40
    DB 39
    DB 72
    DB 101
    DB 108
    DB 108
    DB 111
    DB 32
    DB 87
    DB 111
    DB 114
    DB 108
    DB 100
    DB 39
    DB 44
    DB 32
    DB 53
    DB 41
    DB 58
    DB 0  ; null terminator
    MOV P0,0x3200
    ; Display string at address in P0
    MOV P1,P0
display_loop_3:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_3
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_3
display_end_3:
    MOV P0,[0x2002]
    ; Display string at address in P0
    MOV P1,P0
display_loop_4:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_4
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_4
display_end_4:
    ; Str3 = expression
    MOV P0,[0x2000]
    PUSH P0
    MOV P0,6
    PUSH P0
    MOV P0,5
    MOV P3,P0
    POP P2
    POP P0
    MOV P1,0x4005
    MOV P4,0
mid_loop_6:
    CMP P4,P3
    JGE mid_end_6
    MOV P5,[P0+P2+P4]
    MOV [P1+P4],P5
    INC P4
    JMP mid_loop_6
mid_end_6:
    MOV [P1+P4],0
    MOV P0,0x4005
    MOV [0x2004],P0
    ; Disp

; String literal: "MID('Hello World', 6, 5):"
ORG 0x3300
    DB 77
    DB 73
    DB 68
    DB 40
    DB 39
    DB 72
    DB 101
    DB 108
    DB 108
    DB 111
    DB 32
    DB 87
    DB 111
    DB 114
    DB 108
    DB 100
    DB 39
    DB 44
    DB 32
    DB 54
    DB 44
    DB 32
    DB 53
    DB 41
    DB 58
    DB 0  ; null terminator
    MOV P0,0x3300
    ; Display string at address in P0
    MOV P1,P0
display_loop_7:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_7
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_7
display_end_7:
    MOV P0,[0x2004]
    ; Display string at address in P0
    MOV P1,P0
display_loop_8:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_8
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_8
display_end_8:
    ; Pos = expression
    MOV P0,[0x2000]
    PUSH P0

; String literal: 'World'
ORG 0x3400
    DB 87
    DB 111
    DB 114
    DB 108
    DB 100
    DB 0  ; null terminator
    MOV P0,0x3400
    MOV P1,P0
    POP P0
    STRFIND P0,P1
    MOV P0,R0
    MOV [0x2006],P0
    ; Disp

; String literal: "INSTR('Hello World', 'World'):"
ORG 0x3500
    DB 73
    DB 78
    DB 83
    DB 84
    DB 82
    DB 40
    DB 39
    DB 72
    DB 101
    DB 108
    DB 108
    DB 111
    DB 32
    DB 87
    DB 111
    DB 114
    DB 108
    DB 100
    DB 39
    DB 44
    DB 32
    DB 39
    DB 87
    DB 111
    DB 114
    DB 108
    DB 100
    DB 39
    DB 41
    DB 58
    DB 0  ; null terminator
    MOV P0,0x3500
    ; Display string at address in P0
    MOV P1,P0
display_loop_9:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_9
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_9
display_end_9:
    MOV P0,[0x2006]
    ; Display string at address in P0
    MOV P1,P0
display_loop_10:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_10
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_10
display_end_10:
    ; Pos2 = expression
    MOV P0,[0x2000]
    PUSH P0

; String literal: 'xyz'
ORG 0x3600
    DB 120
    DB 121
    DB 122
    DB 0  ; null terminator
    MOV P0,0x3600
    MOV P1,P0
    POP P0
    STRFIND P0,P1
    MOV P0,R0
    MOV [0x2008],P0
    ; Disp

; String literal: "INSTR('Hello World', 'xyz'):"
ORG 0x3700
    DB 73
    DB 78
    DB 83
    DB 84
    DB 82
    DB 40
    DB 39
    DB 72
    DB 101
    DB 108
    DB 108
    DB 111
    DB 32
    DB 87
    DB 111
    DB 114
    DB 108
    DB 100
    DB 39
    DB 44
    DB 32
    DB 39
    DB 120
    DB 121
    DB 122
    DB 39
    DB 41
    DB 58
    DB 0  ; null terminator
    MOV P0,0x3700
    ; Display string at address in P0
    MOV P1,P0
display_loop_11:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_11
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_11
display_end_11:
    MOV P0,[0x2008]
    ; Display string at address in P0
    MOV P1,P0
display_loop_12:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_12
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_12
display_end_12:
    ; Disp

; String literal: 'String functions test complete'
ORG 0x3800
    DB 83
    DB 116
    DB 114
    DB 105
    DB 110
    DB 103
    DB 32
    DB 102
    DB 117
    DB 110
    DB 99
    DB 116
    DB 105
    DB 111
    DB 110
    DB 115
    DB 32
    DB 116
    DB 101
    DB 115
    DB 116
    DB 32
    DB 99
    DB 111
    DB 109
    DB 112
    DB 108
    DB 101
    DB 116
    DB 101
    DB 0  ; null terminator
    MOV P0,0x3800
    ; Display string at address in P0
    MOV P1,P0
display_loop_13:
    MOV P0,[P1]
    CMP P0,0
    JZ display_end_13
    MOV P2,15
    CHAR P0,P2
    INC P1
    JMP display_loop_13
display_end_13:

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z