; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,0
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display 'W'
    MOV P0,87
    MOV P1,15
    CHAR P0,P1
    ; Display 'h'
    MOV P0,104
    MOV P1,15
    CHAR P0,P1
    ; Display 'i'
    MOV P0,105
    MOV P1,15
    CHAR P0,P1
    ; Display 'l'
    MOV P0,108
    MOV P1,15
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    ; Display 'L'
    MOV P0,76
    MOV P1,15
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    ; Display 'p'
    MOV P0,112
    MOV P1,15
    CHAR P0,P1
    ; Display ' '
    MOV P0,32
    MOV P1,15
    CHAR P0,P1
    ; Display 'T'
    MOV P0,84
    MOV P1,15
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    ; Display 's'
    MOV P0,115
    MOV P1,15
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    ; I = 
    MOV P0,0
    ; Store P0 into I
    MOV [0x2000],P0
    ; While loop
while_loop_1:
    ; Load I into P0
    MOV P0,[0x2000]
    CMP P0,5
    JZ while_end_2
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,8
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display 'C'
    MOV P0,67
    MOV P1,15
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    ; Display 'u'
    MOV P0,117
    MOV P1,15
    CHAR P0,P1
    ; Display 'n'
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    ; Display 't'
    MOV P0,116
    MOV P1,15
    CHAR P0,P1
    ; Display ':'
    MOV P0,58
    MOV P1,15
    CHAR P0,P1
    MOV P0,VY
    ADD P0,8
    MOV VY,P0
    MOV P0,0
    MOV VX,P0
    ; Load I into P0
    MOV P0,[0x2000]
    ; Display value (number or string)
    MOV P1,P0
    CMP P0,0x4000
    JC display_as_number
    CMP P0,0x8000
    JNC display_as_number
    ; Display as string
    MOV P2,P0
display_str_loop:
    MOV P0,[P2]
    CMP P0,0
    JZ display_value_done
    CMP P0,10
    JZ display_str_newline
    MOV P3,15
    CHAR P0,P3
    INC P2
    JMP display_str_loop
display_str_newline:
    MOV P0,VY
    ADD P0,8
    MOV VY,P0
    MOV P0,0
    MOV VX,P0
    INC P2
    JMP display_str_loop
display_as_number:
    MOV P0,P1
    ; Display as number
    MOV P1,0x6000
    ITOS P1,P0
    MOV P2,P1
display_num_loop:
    MOV P0,[P2]
    CMP P0,0
    JZ display_value_done
    MOV P3,15
    CHAR P0,P3
    INC P2
    JMP display_num_loop
display_value_done:
    ; I = 
    ; Load I into P0
    MOV P0,[0x2000]
    MOV P1,1
    ADD P0,P1
    ; Store P0 into I
    MOV [0x2000],P0
    JMP while_loop_1
while_end_2:
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,24
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display 'D'
    MOV P0,68
    MOV P1,15
    CHAR P0,P1
    ; Display 'o'
    MOV P0,111
    MOV P1,15
    CHAR P0,P1
    ; Display 'n'
    MOV P0,110
    MOV P1,15
    CHAR P0,P1
    ; Display 'e'
    MOV P0,101
    MOV P1,15
    CHAR P0,P1
    ; Display '!'
    MOV P0,33
    MOV P1,15
    CHAR P0,P1

; Program end - infinite loop to keep display visible
halt:
JMP halt
ORG 0x2000
DW 0  ; Variable I

ORG 0x1000

; String concatenation subroutine
str_concat:
    ; P1 = left string address
    ; Top of stack = right string address
    ; Returns result address in P0
    POP P2
    POP P3
    PUSH P2
    
    ; Allocate space for result string
    MOV P0,0x6000
    MOV P4,P0
    
    ; Copy left string
str_cat_copy_left:
    MOV P5,[P1]
    CMP P5,0
    JZ str_cat_copy_right
    MOV [P4],P5
    INC P1
    INC P4
    JMP str_cat_copy_left
    
str_cat_copy_right:
    MOV P5,[P3]
    CMP P5,0
    JZ str_cat_done
    MOV [P4],P5
    INC P3
    INC P4
    JMP str_cat_copy_right
    
str_cat_done:
    MOV [P4],0
    RET