; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    MOV P0,10
    MOV VX,P0
    MOV P0,10
    MOV VY,P0
    MOV P0,[0x2000]
    MOV VL,P0
    MOV P0,100
    PUSH P0
    MOV P0,50
    MOV P1,P0
    POP P0
    SFILL P0,P1
    MOV P0,110
    MOV VX,P0
    MOV P0,10
    MOV VY,P0
    MOV P0,[0x2002]
    MOV VL,P0
    MOV P0,200
    PUSH P0
    MOV P0,50
    MOV P1,P0
    POP P0
    SFILL P0,P1
    MOV P0,150
    MOV VX,P0
    MOV P0,100
    MOV VY,P0
    MOV P0,[0x2004]
    MOV VC,P0
    MOV P0,30
    PUSH P0
    MOV P0,1
    MOV P1,P0
    POP P0
    SCIRC P0,P1
    MOV P0,50
    MOV VX,P0
    MOV P0,150
    MOV VY,P0
    MOV P0,[0x2006]
    MOV VC,P0
    MOV P0,200
    PUSH P0
    MOV P0,150
    MOV P1,P0
    POP P0
    SLINE P0,P1

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x2000
DW 0  ; Variable A
DW 0  ; Variable B
DW 0  ; Variable C
DW 0  ; Variable D
DW 0  ; Variable E
DW 0  ; Variable F
DW 0  ; Variable G
DW 0  ; Variable H
DW 0  ; Variable I
DW 0  ; Variable J
DW 0  ; Variable K
DW 0  ; Variable L
DW 0  ; Variable M
DW 0  ; Variable N
DW 0  ; Variable O
DW 0  ; Variable P
DW 0  ; Variable Q
DW 0  ; Variable R
DW 0  ; Variable S
DW 0  ; Variable T
DW 0  ; Variable U
DW 0  ; Variable V
DW 0  ; Variable W
DW 0  ; Variable X
DW 0  ; Variable Y
DW 0  ; Variable Z