; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,0
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display string 'Testing PXLON with colors:' using TEXT
    MOV P0,0x4000
    MOV P1,15
    TEXT P0,P1
    ; For I = 0 To 15
    MOV P0,0
    MOV [0x2010],P0
for_loop_1:
    ; COLOR_VAL = 
    ; Load I into P0
    MOV P0,[0x2010]
    MOV P1,8
    ; COLOR(P0, P1)
    SHL P0,4
    OR P0,P1
    ; Store P0 into COLOR_VAL
    MOV [0x2034],P0
    ; Pxl-On
    ; Load I into P0
    MOV P0,[0x2010]
    MUL P0,8
    MOV P1,10
    ; Load COLOR_VAL into P2
    MOV P2,[0x2034]
    ; Pxl-On at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P2
    SWRITE P0
    ; Next I
    MOV P0,[0x2010]
    INC P0
    MOV [0x2010],P0
    CMP P0,15
    JLE for_loop_1
for_end_2:
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,8
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display string 'Testing PXLOFF:' using TEXT
    MOV P0,0x4100
    MOV P1,15
    TEXT P0,P1
    ; Pxl-On
    MOV P2,50
    MOV P1,30
    MOV P0,20
    ; Pxl-On at (P2,P1)
    MOV VX,P2
    MOV VY,P1
    MOV P0,P0
    SWRITE P0
    ; Pxl-Off
    MOV P0,50
    MOV P1,30
    ; Turn off pixel at (P0,P1)
    MOV [0xF100],P0
    MOV [0xF101],P1
    MOV P0,0
    SWRITE P0
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,16
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display string 'Testing PXLCHANGE:' using TEXT
    MOV P0,0x4200
    MOV P1,15
    TEXT P0,P1
    ; Pxl-On
    MOV P1,60
    MOV P0,30
    MOV P2,36
    ; Pxl-On at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P2
    SWRITE P0
    ; Pxl-Change
    MOV P2,60
    MOV P0,30
    ; Toggle pixel at (P2,P0)
    MOV VX,P2
    MOV VY,P0
    SREAD P0
    XOR P0,15
    SWRITE P0
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,24
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display string 'Testing LINE with colors:' using TEXT
    MOV P0,0x4300
    MOV P1,15
    TEXT P0,P1
    ; Line
    MOV P0,10
    MOV P2,50
    MOV P1,100
    MOV P3,50
    MOV P4,52
    ; Draw line from (P0,P2) to (P1,P3)
    SLINE P0,P2,P1,P3,P4
    ; Line
    MOV P4,10
    MOV P3,60
    MOV P1,100
    MOV P2,60
    MOV P0,68
    ; Draw line from (P4,P3) to (P1,P2)
    SLINE P4,P3,P1,P2,P0
    ; Line
    MOV P0,10
    MOV P2,70
    MOV P1,100
    MOV P3,70
    MOV P4,84
    ; Draw line from (P0,P2) to (P1,P3)
    SLINE P0,P2,P1,P3,P4
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,32
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display string 'Testing CIRCLE with colors:' using TEXT
    MOV P0,0x4400
    MOV P1,15
    TEXT P0,P1
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,40
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display string 'Testing filled CIRCLE:' using TEXT
    MOV P0,0x4500
    MOV P1,15
    TEXT P0,P1
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,48
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display string 'Testing diagonal LINE:' using TEXT
    MOV P0,0x4600
    MOV P1,15
    TEXT P0,P1
    ; Line
    MOV P4,200
    MOV P3,50
    MOV P1,250
    MOV P2,100
    MOV P0,148
    ; Draw line from (P4,P3) to (P1,P2)
    SLINE P4,P3,P1,P2,P0
    ; Line
    MOV P0,200
    MOV P2,100
    MOV P1,250
    MOV P3,50
    MOV P4,164
    ; Draw line from (P0,P2) to (P1,P3)
    SLINE P0,P2,P1,P3,P4
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,56
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display string 'Testing color gradients:' using TEXT
    MOV P0,0x4700
    MOV P1,15
    TEXT P0,P1
    ; For X = 0 To 50
    MOV P0,0
    MOV [0x202E],P0
for_loop_3:
    ; GRADIENT_COLOR = 
    MOV P4,0
    ; Load X into P3
    MOV P3,0
    ; COLOR(P4, P3)
    SHL P4,4
    OR P4,P3
    ; Store P4 into GRADIENT_COLOR
    MOV [0x2036],P4
    ; Pxl-On
    MOV P4,100
    ; Load X into P3
    MOV P3,[0x202E]
    ADD P4,P3
    MOV P3,150
    ; Load GRADIENT_COLOR into P1
    MOV P1,[0x2036]
    ; Pxl-On at (P4,P3)
    MOV VX,P4
    MOV VY,P3
    MOV P0,P1
    SWRITE P0
    ; Next X
    MOV P0,[0x202E]
    INC P0
    MOV [0x202E],P0
    CMP P0,50
    JLE for_loop_3
for_end_4:
    ; For Y = 0 To 20
    MOV P0,0
    MOV [0x2030],P0
for_loop_5:
    ; RAINBOW_COLOR = 
    ; Load Y into P1
    MOV P1,0
    MOV P3,12
    ; COLOR(P1, P3)
    SHL P1,4
    OR P1,P3
    ; Store P1 into RAINBOW_COLOR
    MOV [0x2038],P1
    ; Line
    MOV P1,160
    MOV P3,170
    ; Load Y into P4
    MOV P4,[0x2030]
    ADD P3,P4
    MOV P4,200
    MOV P2,170
    ; Load Y into P0
    MOV P0,[0x2030]
    ADD P2,P0
    ; Load RAINBOW_COLOR into P0
    MOV P0,[0x2038]
    ; Draw line from (P1,P3) to (P4,P2)
    SLINE P1,P3,P4,P2,P0
    ; Next Y
    MOV P0,[0x2030]
    INC P0
    MOV [0x2030],P0
    CMP P0,20
    JLE for_loop_5
for_end_6:
    ; Disp
    MOV P0,0
    MOV VX,P0
    MOV P0,64
    MOV VY,P0
    MOV P0,0
    MOV VL,P0
    ; Display string 'Testing color operations:' using TEXT
    MOV P0,0x4800
    MOV P1,15
    TEXT P0,P1
    ; BASE_COLOR = 
    MOV P0,36
    ; Store P0 into BASE_COLOR
    MOV [0x203A],P0
    ; Pxl-On
    MOV P0,10
    MOV P2,200
    ; Load BASE_COLOR into P4
    MOV P4,[0x203A]
    ; Pxl-On at (P0,P2)
    MOV VX,P0
    MOV VY,P2
    MOV P0,P4
    SWRITE P0
    ; Pxl-On
    MOV P4,20
    MOV P2,200
    ; Load BASE_COLOR into P0
    MOV P0,[0x203A]
    ; RAMP(P0)
    SHR P0,4
    ; Load BASE_COLOR into P3
    MOV P3,[0x203A]
    ; SHADE(P3)
    AND P3,15
    ADD P3,2
    ; COLOR(P0, P3)
    SHL P0,4
    OR P0,P3
    ; Pxl-On at (P4,P2)
    MOV VX,P4
    MOV VY,P2
    MOV P0,P0
    SWRITE P0
    ; Pxl-On
    MOV P0,30
    MOV P2,200
    ; Load BASE_COLOR into P4
    MOV P4,[0x203A]
    ; RAMP(P4)
    SHR P4,4
    ADD P4,1
    ; Load BASE_COLOR into P3
    MOV P3,[0x203A]
    ; SHADE(P3)
    AND P3,15
    ; COLOR(P4, P3)
    SHL P4,4
    OR P4,P3
    ; Pxl-On at (P0,P2)
    MOV VX,P0
    MOV VY,P2
    MOV P0,P4
    SWRITE P0
    ; Pause - wait for key press
pause_loop:
    KEYSTAT P0
    CMP P0,0
    JZ pause_loop
    KEYIN P0

; Program end - infinite loop to keep display visible
halt:
JMP halt
ORG 0x2000
DW 0  ; Variable A
ORG 0x2002
DW 0  ; Variable B
ORG 0x2004
DW 0  ; Variable C
ORG 0x2006
DW 0  ; Variable D
ORG 0x2008
DW 0  ; Variable E
ORG 0x200A
DW 0  ; Variable F
ORG 0x200C
DW 0  ; Variable G
ORG 0x200E
DW 0  ; Variable H
ORG 0x2010
DW 0  ; Variable I
ORG 0x2012
DW 0  ; Variable J
ORG 0x2014
DW 0  ; Variable K
ORG 0x2016
DW 0  ; Variable L
ORG 0x2018
DW 0  ; Variable M
ORG 0x201A
DW 0  ; Variable N
ORG 0x201C
DW 0  ; Variable O
ORG 0x201E
DW 0  ; Variable P
ORG 0x2020
DW 0  ; Variable Q
ORG 0x2022
DW 0  ; Variable R
ORG 0x2024
DW 0  ; Variable S
ORG 0x2026
DW 0  ; Variable T
ORG 0x2028
DW 0  ; Variable U
ORG 0x202A
DW 0  ; Variable V
ORG 0x202C
DW 0  ; Variable W
ORG 0x202E
DW 0  ; Variable X
ORG 0x2030
DW 0  ; Variable Y
ORG 0x2032
DW 0  ; Variable Z
ORG 0x2034
DW 0  ; Variable COLOR_VAL
ORG 0x2036
DW 0  ; Variable GRADIENT_COLOR
ORG 0x2038
DW 0  ; Variable RAINBOW_COLOR
ORG 0x203A
DW 0  ; Variable BASE_COLOR
ORG 0x4000
DB 84
DB 101
DB 115
DB 116
DB 105
DB 110
DB 103
DB 32
DB 80
DB 88
DB 76
DB 79
DB 78
DB 32
DB 119
DB 105
DB 116
DB 104
DB 32
DB 99
DB 111
DB 108
DB 111
DB 114
DB 115
DB 58
DB 0  ; Null terminator
ORG 0x4100
DB 84
DB 101
DB 115
DB 116
DB 105
DB 110
DB 103
DB 32
DB 80
DB 88
DB 76
DB 79
DB 70
DB 70
DB 58
DB 0  ; Null terminator
ORG 0x4200
DB 84
DB 101
DB 115
DB 116
DB 105
DB 110
DB 103
DB 32
DB 80
DB 88
DB 76
DB 67
DB 72
DB 65
DB 78
DB 71
DB 69
DB 58
DB 0  ; Null terminator
ORG 0x4300
DB 84
DB 101
DB 115
DB 116
DB 105
DB 110
DB 103
DB 32
DB 76
DB 73
DB 78
DB 69
DB 32
DB 119
DB 105
DB 116
DB 104
DB 32
DB 99
DB 111
DB 108
DB 111
DB 114
DB 115
DB 58
DB 0  ; Null terminator
ORG 0x4400
DB 84
DB 101
DB 115
DB 116
DB 105
DB 110
DB 103
DB 32
DB 67
DB 73
DB 82
DB 67
DB 76
DB 69
DB 32
DB 119
DB 105
DB 116
DB 104
DB 32
DB 99
DB 111
DB 108
DB 111
DB 114
DB 115
DB 58
DB 0  ; Null terminator
ORG 0x4500
DB 84
DB 101
DB 115
DB 116
DB 105
DB 110
DB 103
DB 32
DB 102
DB 105
DB 108
DB 108
DB 101
DB 100
DB 32
DB 67
DB 73
DB 82
DB 67
DB 76
DB 69
DB 58
DB 0  ; Null terminator
ORG 0x4600
DB 84
DB 101
DB 115
DB 116
DB 105
DB 110
DB 103
DB 32
DB 100
DB 105
DB 97
DB 103
DB 111
DB 110
DB 97
DB 108
DB 32
DB 76
DB 73
DB 78
DB 69
DB 58
DB 0  ; Null terminator
ORG 0x4700
DB 84
DB 101
DB 115
DB 116
DB 105
DB 110
DB 103
DB 32
DB 99
DB 111
DB 108
DB 111
DB 114
DB 32
DB 103
DB 114
DB 97
DB 100
DB 105
DB 101
DB 110
DB 116
DB 115
DB 58
DB 0  ; Null terminator
ORG 0x4800
DB 84
DB 101
DB 115
DB 116
DB 105
DB 110
DB 103
DB 32
DB 99
DB 111
DB 108
DB 111
DB 114
DB 32
DB 111
DB 112
DB 101
DB 114
DB 97
DB 116
DB 105
DB 111
DB 110
DB 115
DB 58
DB 0  ; Null terminator

ORG 0x8000

; String concatenation subroutine
str_concat:
    ; P1 = left string address
    ; Top of stack = right string address
    ; Returns result address in P0
    POP P2
    POP P3
    PUSH P2
    
    ; Allocate space for result string
    MOV P0,0x6000
    STRCPY P0,P1
    STRCAT P0,P3
    RET

; LEFT(string, count) - extract left count characters
left_substr:
    ; P0 = result buffer, P1 = source string, P2 = count
    MOV P3,P0
    MOV P4,0
left_loop:
    CMP P4,P2
    JZ left_done
    MOV P5,[P1]
    CMP P5,0
    JZ left_done
    MOV [P3],P5
    INC P1
    INC P3
    INC P4
    JMP left_loop
left_done:
    MOV [P3],0
    RET

; RIGHT(string, count) - extract right count characters
right_substr:
    ; P0 = result buffer, P1 = source string, P2 = count
    MOV P3,P1
    MOV P4,0
right_len_loop:
    MOV P5,[P3]
    CMP P5,0
    JZ right_len_done
    INC P3
    INC P4
    JMP right_len_loop
right_len_done:
    ; P4 now contains string length
    ; Calculate start position: max(0, length - count)
    CMP P4,P2
    JC right_use_all
    MOV P3,P4
    SUB P3,P2
    JMP right_copy
right_use_all:
    MOV P3,0
right_copy:
    ADD P1,P3
    MOV P3,P0
right_copy_loop:
    MOV P5,[P1]
    CMP P5,0
    JZ right_copy_done
    MOV [P3],P5
    INC P1
    INC P3
    JMP right_copy_loop
right_copy_done:
    MOV [P3],0
    RET

; MID(string, start, count) - extract substring
mid_substr:
    ; P0 = result buffer, P1 = source string, P2 = start position, P3 = count
    ADD P1,P2
    MOV P4,P0
    MOV P5,0
mid_loop:
    CMP P5,P3
    JZ mid_done
    MOV P6,[P1]
    CMP P6,0
    JZ mid_done
    MOV [P4],P6
    INC P1
    INC P4
    INC P5
    JMP mid_loop
mid_done:
    MOV [P4],0
    RET