; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome - clear screen (optimized)
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; For ( = , To ,
    MOV P0,,
    MOV [0x2034],P0
for_loop_1:
    ; Load I into P0
    MOV P0,[0x2010]
    CMP P0,5
    JZ if_end_3
if_end_3:

; Program end - infinite loop to keep display visible
halt:
JMP halt

ORG 0x8000

; String concatenation subroutine
str_concat:
    ; P1 = left string address
    ; Top of stack = right string address
    ; Returns result address in P0
    POP P2
    POP P3
    PUSH P2
    
    ; Allocate space for result string
    MOV P0,0x6000
    MOV P4,P0
    
    ; Copy left string
str_cat_copy_left:
    MOV P5,[P1]
    CMP P5,0
    JZ str_cat_copy_right
    MOV [P4],P5
    INC P1
    INC P4
    JMP str_cat_copy_left
    
str_cat_copy_right:
    MOV P5,[P3]
    CMP P5,0
    JZ str_cat_done
    MOV [P4],P5
    INC P3
    INC P4
    JMP str_cat_copy_right
    
str_cat_done:
    MOV [P4],0
    RET