; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV P0,0
    MOV VM,P0
    MOV VL,P0
    MOV VX,P0
    MOV VY,P0
    SFILL P0
    ; Y = 
    MOV P0,0
    ; Store P0 into Y
    MOV [0x2000],P0
    ; X = 
    MOV P0,0
    ; Store P0 into X
    MOV [0x2002],P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,0
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P2
    SWRITE P0
    ; PXLON
    ; Load X into P2
    MOV P2,[0x2002]
    MOV P0,1
    ADD P2,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P3,4
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P3
    SWRITE P0
    ; PXLON
    ; Load X into P3
    MOV P3,[0x2002]
    MOV P0,2
    ADD P3,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P4,8
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P4
    SWRITE P0
    ; PXLON
    ; Load X into P4
    MOV P4,[0x2002]
    MOV P0,3
    ADD P4,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P5,12
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P5
    SWRITE P0
    ; PXLON
    ; Load X into P5
    MOV P5,[0x2002]
    MOV P0,4
    ADD P5,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P6,15
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P6
    SWRITE P0
    ; Y = 
    ; Load Y into P6
    MOV P6,[0x2000]
    MOV P0,1
    ADD P6,P1
    ; Store P0 into Y
    MOV [0x2000],P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P7,16
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P7
    SWRITE P0
    ; PXLON
    ; Load X into P7
    MOV P7,[0x2002]
    MOV P0,1
    ADD P7,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,20
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,24
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,244
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,32
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,36
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,40
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,228
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,48
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,52
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,56
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,212
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,64
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,68
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,72
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,76
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,80
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,84
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,88
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,92
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,96
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,100
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,104
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,108
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,112
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,116
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,120
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,124
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,128
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,132
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,136
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,140
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,144
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,148
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,152
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,156
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,160
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,164
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,168
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,172
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,176
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,180
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,184
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,188
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,192
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,196
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,200
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,204
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,208
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,212
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,216
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,220
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,224
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,228
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,232
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,236
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Y = 
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,1
    ADD P1,P0
    ; Store P1 into Y
    MOV [0x2000],P1
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,240
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,1
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,244
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; PXLON
    ; Load X into P1
    MOV P1,[0x2002]
    MOV P2,2
    ADD P1,P0
    ; Load Y into P0
    MOV P0,[0x2000]
    MOV P2,248
    ; PXLON at (P1,P0)
    MOV VX,P1
    MOV VY,P0
    MOV P0,P0
    SWRITE P0
    ; PXLON
    ; Load X into P0
    MOV P0,[0x2002]
    MOV P2,3
    ADD P0,P1
    ; Load Y into P1
    MOV P1,[0x2000]
    MOV P2,252
    ; PXLON at (P0,P1)
    MOV VX,P0
    MOV VY,P1
    MOV P0,P1
    SWRITE P0
    ; Pause - wait for key press
pause_loop:
    KEYSTAT P0
    CMP P0,0
    JZ pause_loop
    KEYIN P0

; Program end - infinite loop to keep display visible
halt:
JMP halt
ORG 0x2000
DW 0  ; Variable Y
ORG 0x2002
DW 0  ; Variable X

ORG 0x1000