; NoBASIC Program - Generated by nobasic_compiler.py
; Generated automatically - do not edit

ORG 0x1000

; Initialize stack pointer
MOV P8,0xF000

; Initialize text cursor position
MOV VX,0
MOV VY,0
MOV VL,0

; Program start
start:
    ; ClrHome
    MOV VM,0
    MOV VL,0
    MOV VX,0
    MOV VY,0
    MOV P0,0
    SFILL P0
    ; Prompt
    ; Prompt A
    CALL read_number
    ; Store P0 into A
    MOV [0x2000],P0
    ; Disp
    MOV VX,0
    MOV VY,0
    MOV VL,0
    ; Display 'Y'
    MOV P0,89
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'o'
    MOV P0,111
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'u'
    MOV P0,117
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ' '
    MOV P0,32
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'n'
    MOV P0,110
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 't'
    MOV P0,116
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'r'
    MOV P0,114
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'e'
    MOV P0,101
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display 'd'
    MOV P0,100
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ; Display ':'
    MOV P0,58
    MOV P1,7
    CHAR P0,P1
    ADD VX,8
    ADD VY,8
    MOV VX,0
    ; Load A into P0
    MOV P0,[0x2000]
    ; Display number (simplified)
    MOV P1,7
    CHAR P0,P1
    ADD VX,8

; Program end - infinite loop to keep display visible
halt:
JMP halt
ORG 0x2000
DW 0  ; Variable A

ORG 0x1000