; Generated by the Astrid Compiler for Nova-16
ORG 0x1000
start:
    MOV SP, 0xFF00 ; Set stack pointer to high memory
    MOV FP, 0xFF00 ; Also init frame pointer
    CALL func_main
    HLT

; Function: main
func_main:
    ENTER 0
; Call to set_mode
        MOV R0, 1
        PUSH R0
        CALL builtin_set_vmode
        ; Args already consumed by callee (stdlib calling convention)
        MOV R1, R0
; Call to set_layer
        MOV R2, 0
        PUSH R2
        CALL builtin_set_layer
        ; Args already consumed by callee (stdlib calling convention)
        MOV R3, R0
; Call to set_pos
        MOV R4, 5
        PUSH R4
        MOV R5, 5
        PUSH R5
        CALL builtin_set_pos
        ; Args already consumed by callee (stdlib calling convention)
        MOV R6, R0
; Call to write_screen
        MOV R7, 0x1F
        PUSH R7
        CALL builtin_write_screen
        ; Args already consumed by callee (stdlib calling convention)
        MOV R8, R0
; Implicit return for void function
    MOV SP, FP
    POP FP
    RET

; Built-in Function Implementations
builtin_set_vmode:
        POP P0
        POP R1
        MOV VM, R1
        PUSH P0
        RET
builtin_set_layer:
        POP P0
        POP R1
        MOV VL, R1
        PUSH P0
        RET
builtin_set_pos:
        POP P0
        POP R1
        POP R2
        MOV VX, R2
        MOV VY, R1
        PUSH P0
        RET
builtin_write_screen:
        POP P0
        POP R1
        SWRITE R1
        PUSH P0
        RET
builtin_read_screen:
        SREAD R0
        RET
builtin_scroll_x:
        POP P0
        POP R1
        SROLX R1
        PUSH P0
        RET
builtin_scroll_y:
        POP P0
        POP R1
        SROLY R1
        PUSH P0
        RET
builtin_set_pointers:
        POP P0
        POP R1
        POP R2
        MOV P2, R2
        MOV P1, R1
        MOV P0, P2
        PUSH P0
        RET
builtin_write_text:
        POP P0
        POP R1
        POP R2
        TEXT R2, R1
        PUSH P0
        RET
builtin_set_font:
        POP P0
        POP R1
        PUSH P0
        RET
builtin_sound_play:
        POP P0
        POP R1
        POP R2
        POP R3
        SPLAY R3, R2, R1
        PUSH P0
        RET
builtin_sound_stop:
        POP P0
        POP R1
        SPLAY R1, 0, 0
        PUSH P0
        RET
builtin_set_timer:
        POP P0
        POP R1
        POP R2
        POP R3
        POP R4
        MOV TT, R4
        MOV TM, R3
        MOV TS, R2
        MOV TC, R1
        PUSH P0
        RET
builtin_sti:
        STI
        RET
builtin_cli:
        CLI
        RET
builtin_iret:
        IRET
        RET
builtin_random:
        RND R0
        RET
builtin_random_range:
        POP P0
        POP R1
        POP R2
        RNDR R0, R2, R1
        PUSH P0
        RET
builtin_halt:
        HLT
        RET