; Generated by the Astrid Compiler for Nova-16
ORG 0x1000
start:
MOV SP, 0xFF00 ; Set stack pointer to high memory
MOV FP, 0xFF00 ; Also init frame pointer
CALL func_main
HLT
ORG 0x0100
DW func_timer_interrupt
ORG 0x0120
; Function: setup
func_setup:
ENTER 0
; Call to set_vmode
MOV P0, 1
PUSH P0
CALL builtin_set_vmode
; Args consumed by callee
MOV P1, R0
; Call to set_pos
MOV P2, 0
PUSH P2
MOV P4, 0
PUSH P4
CALL builtin_set_pos
; Args consumed by callee
MOV P5, R0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: draw_stars
func_draw_stars:
ENTER 14
; var start = ...
MOV P6, 0
MOV [0xC088], P6
; var finish = ...
MOV P7, 65535
MOV [0xC08A], P7
; Call to set_layer
MOV P0, [FP+4]
PUSH P0
CALL builtin_set_layer
; Args consumed by callee
MOV P1, R0
; For loop
; Assignment to p
MOV P2, [0xC088]
MOV [0xC080], P2
for_start_0:
MOV P4, [0xC080]
PUSH P4
MOV P5, [0xC08A]
POP P4
CMP P5, P4
JNC cmp_true_3
MOV P4, 0
JMP cmp_end_4
cmp_true_3:
MOV P4, 1
cmp_end_4:
CMP P4, 0
JZ for_end_1
; var rnd = ...
; Call to random
CALL builtin_random
MOV P6, P0
MOV [0xC08C], P6
; Assignment to x
; Optimized high-byte access: (val >> 8) & 0xFF
MOV P7, [0xC08C]
MOV P0, P7:
MOV [0xC082], P0
; Assignment to y
MOV P1, 255
PUSH P1
MOV P2, [0xC08C]
POP P1
AND P1, P2
MOV [0xC084], P1
; Assignment to color
; Call to random_range
MOV P4, [FP+10]
PUSH P4
MOV P5, [FP+8]
PUSH P5
CALL builtin_random_range
; Args consumed by callee
MOV P6, P0
MOV [0xC086], P6
; Call to set_pos
MOV P7, [0xC084]
PUSH P7
MOV P0, [0xC082]
PUSH P0
CALL builtin_set_pos
; Args consumed by callee
MOV P1, R0
; Call to write_screen
MOV P2, [0xC086]
PUSH P2
CALL builtin_write_screen
; Args consumed by callee
MOV P4, R0
for_continue_2:
; Wrap-check: save p before update
MOV P5, [0xC080]
PUSH P5
; Assignment to p
MOV P6, [0xC080]
MOV P7, [FP+6]
ADD P6, P7
MOV [0xC080], P6
; Wrap-check: compare p new vs old
POP P0
MOV P1, [0xC080]
CMP P1, P0
JC for_end_1
JMP for_start_0
for_end_1:
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: draw_text
func_draw_text:
ENTER 0
; Call to set_layer
MOV P2, 5
PUSH P2
CALL builtin_set_layer
; Args consumed by callee
MOV P4, R0
; Call to set_vmode
MOV P5, 0
PUSH P5
CALL builtin_set_vmode
; Args consumed by callee
MOV P6, R0
; Call to set_pos
MOV P7, 123
PUSH P7
MOV P0, 101
PUSH P0
CALL builtin_set_pos
; Args consumed by callee
MOV P1, R0
; Call to write_text
MOV P2, 21
PUSH P2
MOV P4, str_5
PUSH P4
CALL builtin_write_text
; Args consumed by callee
MOV P5, R0
; Call to set_pos
MOV P6, 124
PUSH P6
MOV P7, 100
PUSH P7
CALL builtin_set_pos
; Args consumed by callee
MOV P0, R0
; Call to write_text
MOV P1, 31
PUSH P1
MOV P2, str_5
PUSH P2
CALL builtin_write_text
; Args consumed by callee
MOV P4, R0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: main
func_main:
ENTER 0
; Call to setup
CALL func_setup
MOV P5, P0
; Call to draw_stars
MOV P6, 6
PUSH P6
MOV P7, 0
PUSH P7
MOV P0, 32
PUSH P0
MOV P1, 1
PUSH P1
CALL func_draw_stars
; Args consumed by callee
MOV P2, P0
; Call to draw_stars
MOV P4, 10
PUSH P4
MOV P5, 7
PUSH P5
MOV P6, 128
PUSH P6
MOV P7, 2
PUSH P7
CALL func_draw_stars
; Args consumed by callee
; Call to draw_stars
MOV P1, 15
PUSH P1
MOV P2, 11
PUSH P2
MOV P4, 256
PUSH P4
MOV P5, 3
PUSH P5
CALL func_draw_stars
; Args consumed by callee
MOV P6, P0
; Call to draw_text
CALL func_draw_text
MOV P7, P0
; Call to sti
CALL builtin_sti
MOV P0, R0
; Call to set_timer
MOV P1, 3
PUSH P1
MOV P2, 80
PUSH P2
MOV P4, 255
PUSH P4
MOV P5, 0
PUSH P5
CALL builtin_set_timer
; Args consumed by callee
MOV P6, R0
; While loop
while_start_6:
MOV P7, 1
CMP P7, 0
JZ while_end_7
JMP while_start_6
while_end_7:
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: timer_interrupt
func_timer_interrupt:
SUB SP, 2 ; Allocate locals
; For loop
; var layer = ...
MOV P0, 1
MOV [SP+0], P0
for_start_8:
MOV P1, [SP+0]
MOV P2, 3
CMP P2, P1
JNC cmp_true_11
MOV P1, 0
JMP cmp_end_12
cmp_true_11:
MOV P1, 1
cmp_end_12:
CMP P1, 0
JZ for_end_9
; Call to set_layer
MOV P4, [SP+0]
PUSH P4
CALL builtin_set_layer
; Args consumed by callee
MOV P5, R0
; If statement
MOV P6, 1
MOV P7, [SP+0]
CMP P6, P7
JZ cmp_true_15
MOV P6, 0
JMP cmp_end_16
cmp_true_15:
MOV P6, 1
cmp_end_16:
CMP P6, 0
JZ if_end_13
; Call to scroll_x
MOV P0, [SP+0]
PUSH P0
CALL builtin_scroll_x
; Args consumed by callee
MOV P1, R0
if_end_13:
; If statement
MOV P2, 2
MOV P4, [SP+0]
CMP P2, P4
JZ cmp_true_19
MOV P2, 0
JMP cmp_end_20
cmp_true_19:
MOV P2, 1
cmp_end_20:
CMP P2, 0
JZ if_end_17
; Call to scroll_x
MOV P5, [SP+0]
PUSH P5
CALL builtin_scroll_x
; Args consumed by callee
MOV P6, R0
; Call to scroll_x
MOV P7, [SP+0]
PUSH P7
CALL builtin_scroll_x
; Args consumed by callee
MOV P0, R0
if_end_17:
; If statement
MOV P1, 3
MOV P2, [SP+0]
CMP P1, P2
JZ cmp_true_23
MOV P1, 0
JMP cmp_end_24
cmp_true_23:
MOV P1, 1
cmp_end_24:
CMP P1, 0
JZ if_end_21
; Call to scroll_x
MOV P4, [SP+0]
PUSH P4
CALL builtin_scroll_x
; Args consumed by callee
MOV P5, R0
; Call to scroll_x
MOV P6, [SP+0]
PUSH P6
CALL builtin_scroll_x
; Args consumed by callee
MOV P7, R0
; Call to scroll_x
MOV P0, [SP+0]
PUSH P0
CALL builtin_scroll_x
; Args consumed by callee
MOV P1, R0
if_end_21:
for_continue_10:
MOV P2, [SP+0]
MOV P4, P2
INC P2
MOV [SP+0], P2
JMP for_start_8
for_end_9:
ADD SP, 2 ; Deallocate locals before IRET
IRET
;
; Data Section
;
str_5: DEFSTR "StarField"
; Built-in Function Implementations
builtin_set_vmode:
POP P0
POP P1
MOV VM, P1
PUSH P0
RET
builtin_set_layer:
POP P0
POP P1
MOV VL, P1
PUSH P0
RET
builtin_set_pos:
POP P0
POP P1
POP P2
MOV VX, P1
MOV VY, P2
PUSH P0
RET
builtin_write_screen:
POP P0
POP P1
SWRITE P1
PUSH P0
RET
builtin_scroll_x:
POP P0
POP P1
SROL 0, P1
PUSH P0
RET
builtin_write_text:
POP P0
POP P1
POP P2
MOV VC, P2
TEXT P1
PUSH P0
RET
builtin_set_timer:
POP P0
POP P1
POP P2
POP P3
POP P4
; Args pushed in reversed source order: stack top->bottom after POP P0 is
; [arg0=TT, arg1=TM, arg2=TS, arg3=TC]. So POP P1=TT, P2=TM, P3=TS, P4=TC.
MOV TT, P1
MOV TM, P2
MOV TS, P3
MOV TC, P4
PUSH P0
RET
builtin_sti:
STI
RET
builtin_random:
RND P0
RET
builtin_random_range:
; Save return address in P3 (not P0, since RNDR will write its result to P0).
; Stack: [ret_addr, color_max, color_min] (top = last pushed = color_min)
; builtins with P0 as destination use P3 for the return address (see
; builtin_set_pointers for the same pattern).
POP P3
POP P1
POP P2
RNDR P0, P1, P2
PUSH P3
RET