CMD EQU 0x0000
OUTPUT EQU 0x0200
INVALID_MSG EQU 0x0300
WRITTEN_MSG EQU 0x0320

ORG 0x1000
SETUP:
    MOV VC, 0x2F
    MOV VX, 0
    MOV VY, 0
    MOV VM, 0
    MOV VL, 0
    MOV R2, 0
    STI
    KEYCTRL 1

MAIN:
    CHAR 62
MAIN_LOOP:
    JMP MAIN_LOOP

KEYCHECK:
    KEYSTAT R0
    CMP R0, 0
    JNZ KCMD
KEYDONE:
    IRET

KCMD:
    KEYIN R1
    CMP R1, 10
    JZ CMDENTER
    CHAR R1
    MOV P0, CMD
    ADD P0, R2
    MOV [P0], R1
    INC R2
    JMP KEYDONE
CMDENTER:
    INC R2
    MOV P0, CMD
    ADD P0, R2
    MOV [P0], 0
    CALL PARSE_CMD
    MOV R2, 0
    JMP KEYDONE

PARSE_CMD:
    MOV P3, CMD
SKIP_SPACES:
    CMP [P3], ' '
    JNZ SKIP_DONE
    INC P3
    JMP SKIP_SPACES
SKIP_DONE:
    MOV R4, [P3]
    INC P3
SKIP_SPACES2:
    CMP [P3], ' '
    JNZ SKIP_DONE2
    INC P3
    JMP SKIP_SPACES2
SKIP_DONE2:
    CMP R4, 'R'
    JZ CMD_READ
    CMP R4, 'r'
    JZ CMD_READ
    CMP R4, 'W'
    JZ CMD_WRITE
    CMP R4, 'w'
    JZ CMD_WRITE
    JMP INVALID_CMD
PARSE_END:
    RET

PARSE_HEX:
    MOV P4, P3
    MOV P0, 0
PARSE_LOOP:
    MOV R6, [P4]
    CMP R6, 0
    JZ PARSE_HEX_END
    CMP R6, ' '
    JZ PARSE_HEX_END
    CMP R6, '0'
    JLT INVALID_DIGIT
    CMP R6, '9'
    JLE DIGIT
    CMP R6, 'A'
    JLT INVALID_DIGIT
    CMP R6, 'F'
    JLE UPPER
    CMP R6, 'a'
    JLT INVALID_DIGIT
    CMP R6, 'f'
    JLE LOWER
INVALID_DIGIT:
    JMP PARSE_HEX_END
DIGIT:
    SUB R6, '0'
    JMP ADD_DIGIT
UPPER:
    SUB R6, 'A'
    ADD R6, 10
    JMP ADD_DIGIT
LOWER:
    SUB R6, 'a'
    ADD R6, 10
ADD_DIGIT:
    SHL P0, 4
    ADD P0, R6
    INC P4
    JMP PARSE_LOOP
PARSE_HEX_END:
    RET

BYTE_TO_HEX:
    MOV P5, OUTPUT
    MOV [P5], '0'
    INC P5
    MOV [P5], 'x'
    INC P5
    ; high nibble
    MOV R6, R5
    SHR R6, 4
    CALL NIBBLE_TO_CHAR
    MOV [P5], R6
    INC P5
    ; low nibble
    MOV R6, R5
    AND R6, 0x0F
    CALL NIBBLE_TO_CHAR
    MOV [P5], R6
    INC P5
    MOV [P5], 0
    RET

NIBBLE_TO_CHAR:
    CMP R6, 10
    JLT DIGIT2
    ADD R6, 'A'-10
    RET
DIGIT2:
    ADD R6, '0'
    RET

CMD_READ:
    CALL PARSE_HEX
    CMP P4, P3
    JZ NO_ADDR
    MOV P1, P0
    JMP HAVE_ADDR
NO_ADDR:
    MOV P1, 0
HAVE_ADDR:
    MOV R5, [P1]
    CALL BYTE_TO_HEX
    MOV VX, 0
    MOV VY, 20
    MOV VC, 0x3F
    TEXT OUTPUT
    JMP PARSE_END

CMD_WRITE:
    CALL PARSE_HEX
    CMP P4, P3
    JZ INVALID_CMD
    MOV P1, P0  ; addr
SKIP_SPACES3:
    CMP [P3], ' '
    JNZ SKIP_DONE3
    INC P3
    JMP SKIP_SPACES3
SKIP_DONE3:
    CALL PARSE_HEX
    CMP P4, P3
    JZ INVALID_CMD
    MOV P2, P0  ; value
    MOV [P1], P2
    ; display written
    MOV VX, 0
    MOV VY, 20
    MOV VC, 0x3F
    TEXT WRITTEN_MSG
    JMP PARSE_END

INVALID_CMD:
    MOV VX, 0
    MOV VY, 20
    MOV VC, 0x3F
    TEXT INVALID_MSG
    JMP PARSE_END

ORG 0x0108
    DW KEYCHECK

INVALID_MSG: DB "Invalid command", 0
WRITTEN_MSG: DB "Written", 0