; Generated by the Astrid Compiler for Nova-16
ORG 0x1000
start:
MOV SP, 0xFFFF ; Set stack pointer to high memory
MOV FP, 0xFFFF ; Also init frame pointer
CALL func_main
HLT
; Function: main
func_main:
ENTER 4
; var a = ...
MOV P0, 65535
MOV [0xC000], P0
; var b = ...
MOV P1, 65535
MOV [0xC002], P1
; Call to set_pos
MOV P2, 0
PUSH P2
MOV P4, 0
PUSH P4
CALL builtin_set_pos
; Args consumed by callee
MOV P5, R0
; Call to write_text
MOV P6, 31
PUSH P6
; Type cast: (string) expr
MOV P7, [0xC000]
ITOS P0, P7
PUSH P0
CALL builtin_write_text
; Args consumed by callee
MOV P1, R0
; Call to set_pos
MOV P2, 8
PUSH P2
MOV P4, 0
PUSH P4
CALL builtin_set_pos
; Args consumed by callee
MOV P5, R0
; Call to write_text
MOV P6, 31
PUSH P6
; Type cast: (string) expr
MOV P7, [0xC002]
CMP P7, 0
JZ utoa_zero_0
MOV P1, P7
MOV P2, 0xA100
utoa_loop_1:
CMP P1, 0
JZ utoa_done_2
MOV P4, P1
MOV P5, 10
DIV P4, P5
MOV P5, P3
ADD P5, 48
MOV R0, P5
MOV [P2], R0
MOV P1, P4
INC P2
JMP utoa_loop_1
utoa_done_2:
DEC P2
MOV P1, 0xA000
utoa_rev_3:
CMP P2, 0xA100
JC utoa_finish_4
MOV R0, [P2]
MOV [P1], R0
INC P1
DEC P2
JMP utoa_rev_3
utoa_finish_4:
MOV [P1], 0
MOV P0, 0xA000
JMP utoa_finish_4_end
utoa_zero_0:
MOV [0xA000], 48
MOV [0xA001], 0
MOV P0, 0xA000
utoa_finish_4_end:
PUSH P0
CALL builtin_write_text
; Args consumed by callee
MOV P6, R0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Built-in Function Implementations
builtin_set_pos:
POP P0
POP P1
POP P2
MOV VX, P1
MOV VY, P2
PUSH P0
RET
builtin_write_text:
POP P0
POP P1
POP P2
MOV VC, P2
TEXT P1
PUSH P0
RET