; Generated by the Astrid Compiler for Nova-16
ORG 0x1000
start:
MOV SP, 0xFFFF ; Set stack pointer to high memory
MOV FP, 0xFFFF ; Also init frame pointer
CALL func_main
HLT
; Function: main
func_main:
ENTER 8
; var x = ...
MOV P0, 0
MOV [0xC000], P0
; var y = ...
MOV P1, 0
MOV [0xC002], P1
; var color = ...
MOV P2, 0
MOV [0xC004], P2
; var counter = ...
MOV P4, 0
MOV [0xC006], P4
; While loop
while_start_0:
MOV P5, 255
PUSH P5
MOV P6, [0xC002]
POP P5
CMP P5, P6
JNZ cmp_true_2
MOV P5, 0
JMP cmp_end_3
cmp_true_2:
MOV P5, 1
cmp_end_3:
CMP P5, 0
JZ while_end_1
MOV P7, [0xC000]
MOV P0, P7
INC P7
MOV [0xC000], P7
; If statement
MOV P1, 255
PUSH P1
MOV P2, [0xC000]
POP P1
CMP P1, P2
JZ cmp_true_6
MOV P1, 0
JMP cmp_end_7
cmp_true_6:
MOV P1, 1
cmp_end_7:
CMP P1, 0
JZ if_end_4
; Assignment to x
MOV P4, 0
MOV [0xC000], P4
MOV P5, [0xC002]
MOV P6, P5
INC P5
MOV [0xC002], P5
; If statement
MOV P7, [0xC002]
PUSH P7
MOV P0, 8
POP P7
MOD P7, P0
PUSH P7
MOV P1, 0
POP P7
CMP P7, P1
JZ cmp_true_10
MOV P7, 0
JMP cmp_end_11
cmp_true_10:
MOV P7, 1
cmp_end_11:
CMP P7, 0
JZ if_end_8
; Call to roll_x
MOV P2, 1
PUSH P2
MOV P4, 0
PUSH P4
CALL builtin_roll_x_2
; Args consumed by callee
MOV P5, R0
if_end_8:
if_end_4:
MOV P6, [0xC004]
MOV P7, P6
INC P6
MOV [0xC004], P6
; If statement
MOV P0, 255
PUSH P0
MOV P1, [0xC004]
POP P0
CMP P0, P1
JZ cmp_true_14
MOV P0, 0
JMP cmp_end_15
cmp_true_14:
MOV P0, 1
cmp_end_15:
CMP P0, 0
JZ if_end_12
; Assignment to color
MOV P2, 0
MOV [0xC004], P2
if_end_12:
; Call to set_pos
MOV P4, [0xC002]
PUSH P4
MOV P5, [0xC000]
PUSH P5
CALL builtin_set_pos
; Args consumed by callee
MOV P6, R0
; Call to write_screen
MOV P7, [0xC004]
PUSH P7
CALL builtin_write_screen
; Args consumed by callee
MOV P0, R0
JMP while_start_0
while_end_1:
; Call to set_layer
MOV P1, 5
PUSH P1
CALL builtin_set_layer
; Args consumed by callee
MOV P2, R0
; Call to set_pos
MOV P4, 124
PUSH P4
MOV P5, 72
PUSH P5
CALL builtin_set_pos
; Args consumed by callee
MOV P6, R0
; Call to write_text
MOV P7, 95
PUSH P7
MOV P0, str_16
PUSH P0
CALL builtin_write_text
; Args consumed by callee
MOV P1, R0
; While loop
while_start_17:
MOV P2, 1
CMP P2, 0
JZ while_end_18
MOV P4, [0xC006]
MOV P5, P4
INC P4
MOV [0xC006], P4
; If statement
MOV P6, [0xC006]
PUSH P6
MOV P7, 5120
POP P6
MOD P6, P7
PUSH P6
MOV P0, 0
POP P6
CMP P6, P0
JZ cmp_true_21
MOV P6, 0
JMP cmp_end_22
cmp_true_21:
MOV P6, 1
cmp_end_22:
CMP P6, 0
JZ if_end_19
; Call to roll_x
MOV P1, 1
PUSH P1
MOV P2, 0
PUSH P2
CALL builtin_roll_x_2
; Args consumed by callee
MOV P4, R0
; Assignment to counter
MOV P5, 0
MOV [0xC006], P5
if_end_19:
JMP while_start_17
while_end_18:
; Implicit return for void function
MOV SP, FP
POP FP
RET
;
; Data Section
;
str_16: DEFSTR "De Nova Stella"
; Built-in Function Implementations
builtin_set_layer:
POP P0
POP P1
MOV VL, P1
PUSH P0
RET
builtin_set_pos:
POP P0
POP P1
POP P2
MOV VX, P1
MOV VY, P2
PUSH P0
RET
builtin_write_screen:
POP P0
POP P1
SWRITE P1
PUSH P0
RET
builtin_roll_x_2:
; Args: layer, dir; preserves VL
POP P0
POP P1
POP P2
MOV P5, VL
MOV VL, P1
CMP P2, 0
JZ builtin_roll_x_2_fwd
SROL 0, -1
JMP builtin_roll_x_2_end
builtin_roll_x_2_fwd:
SROL 0, 1
builtin_roll_x_2_end:
MOV VL, P5
PUSH P0
RET
builtin_write_text:
POP P0
POP P1
POP P2
MOV VC, P2
TEXT P1
PUSH P0
RET