; Generated by the Astrid Compiler for Nova-16
ORG 0x1000
start:
MOV SP, 0xFFFF ; Set stack pointer to high memory
MOV FP, 0xFFFF ; Also init frame pointer
CALL func_main
HLT
; Function: cam_asr4
func_cam_asr4:
ENTER 0
; If statement
MOV P0, [FP+4]
PUSH P0
MOV P1, 0
POP P0
; Signed comparison (two's complement)
CMP P0, P1
JLT cmp_true_2
MOV P0, 0
JMP cmp_end_3
cmp_true_2:
MOV P0, 1
cmp_end_3:
CMP P0, 0
JZ if_end_0
; Function return
MOV P2, [FP+4]
NEG P2
; Unrolled shift SHR by 4
SHR P2, 1
SHR P2, 1
SHR P2, 1
SHR P2, 1
NEG P2
MOV P0, P2
MOV R0, P2
MOV SP, FP
POP FP
RET
if_end_0:
; Function return
MOV P4, [FP+4]
; Unrolled shift SHR by 4
SHR P4, 1
SHR P4, 1
SHR P4, 1
SHR P4, 1
MOV P0, P4
MOV R0, P4
MOV SP, FP
POP FP
RET
; Function: cam_asr5
func_cam_asr5:
ENTER 0
; If statement
MOV P5, [FP+4]
PUSH P5
MOV P6, 0
POP P5
; Signed comparison (two's complement)
CMP P5, P6
JLT cmp_true_6
MOV P5, 0
JMP cmp_end_7
cmp_true_6:
MOV P5, 1
cmp_end_7:
CMP P5, 0
JZ if_end_4
; Function return
MOV P7, [FP+4]
NEG P7
; Unrolled shift SHR by 5
SHR P7, 1
SHR P7, 1
SHR P7, 1
SHR P7, 1
SHR P7, 1
NEG P7
MOV P0, P7
MOV R0, P7
MOV SP, FP
POP FP
RET
if_end_4:
; Function return
MOV P0, [FP+4]
; Unrolled shift SHR by 5
SHR P0, 1
SHR P0, 1
SHR P0, 1
SHR P0, 1
SHR P0, 1
MOV R0, P0
MOV SP, FP
POP FP
RET
; Function: cam_qmul
func_cam_qmul:
ENTER 6
; var sign = ...
MOV P1, 1
MOV [0xC100], P1
; If statement
MOV P2, [FP+4]
PUSH P2
MOV P4, 0
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JLT cmp_true_10
MOV P2, 0
JMP cmp_end_11
cmp_true_10:
MOV P2, 1
cmp_end_11:
CMP P2, 0
JZ if_end_8
; Assignment to sign
MOV P5, [0xC100]
NEG P5
MOV [0xC100], P5
; Assignment to a
MOV P6, [FP+4]
NEG P6
MOV [FP+4], P6
if_end_8:
; If statement
MOV P7, [FP+6]
PUSH P7
MOV P0, 0
POP P7
; Signed comparison (two's complement)
CMP P7, P0
JLT cmp_true_14
MOV P7, 0
JMP cmp_end_15
cmp_true_14:
MOV P7, 1
cmp_end_15:
CMP P7, 0
JZ if_end_12
; Assignment to sign
MOV P1, [0xC100]
NEG P1
MOV [0xC100], P1
; Assignment to cq
MOV P2, [FP+6]
NEG P2
MOV [FP+6], P2
if_end_12:
; var hi = ...
MOV P4, [FP+4]
; Unrolled shift SHR by 7
SHR P4, 1
SHR P4, 1
SHR P4, 1
SHR P4, 1
SHR P4, 1
SHR P4, 1
SHR P4, 1
PUSH P4
MOV P5, [FP+6]
POP P4
MUL P4, P5
MOV [0xC102], P4
; var lo = ...
MOV P6, 127
PUSH P6
MOV P7, [FP+4]
POP P6
AND P6, P7
PUSH P6
MOV P0, [FP+6]
POP P6
MUL P6, P0
MOV [0xC104], P6
; Function return
MOV P1, [0xC102]
; Unrolled shift SHR by 1
SHR P1, 1
PUSH P1
MOV P2, [0xC104]
; Unrolled shift SHR by 8
SHR P2, 1
SHR P2, 1
SHR P2, 1
SHR P2, 1
SHR P2, 1
SHR P2, 1
SHR P2, 1
SHR P2, 1
POP P1
ADD P1, P2
PUSH P1
MOV P4, [0xC100]
POP P1
MUL P1, P4
MOV P0, P1
MOV R0, P1
MOV SP, FP
POP FP
RET
; Function: cam_wrap
func_cam_wrap:
ENTER 0
; While loop
while_start_16:
MOV P5, [FP+4]
PUSH P5
MOV P6, 16085
POP P5
; Signed comparison (two's complement)
CMP P5, P6
JGT cmp_true_18
MOV P5, 0
JMP cmp_end_19
cmp_true_18:
MOV P5, 1
cmp_end_19:
CMP P5, 0
JZ while_end_17
; Assignment to qangle
MOV P7, [FP+4]
PUSH P7
MOV P0, 16085
POP P7
SUB P7, P0
MOV [FP+4], P7
JMP while_start_16
while_end_17:
; While loop
while_start_20:
MOV P1, [FP+4]
PUSH P1
MOV P2, -16085
POP P1
; Signed comparison (two's complement)
CMP P1, P2
JLT cmp_true_22
MOV P1, 0
JMP cmp_end_23
cmp_true_22:
MOV P1, 1
cmp_end_23:
CMP P1, 0
JZ while_end_21
; Assignment to qangle
MOV P4, [FP+4]
PUSH P4
MOV P5, 16085
POP P4
ADD P4, P5
MOV [FP+4], P4
JMP while_start_20
while_end_21:
; Function return
MOV P6, [FP+4]
MOV P0, P6
MOV R0, P6
MOV SP, FP
POP FP
RET
; Function: cam_sin_of
func_cam_sin_of:
ENTER 2
; var t = ...
; Call to cam_wrap
MOV P7, [FP+4]
PUSH P7
CALL func_cam_wrap
ADD SP, 2 ; Caller cleans up args
MOV [0xC200], P0
; asm {
SIN [0xC200]
; }
; Function return
MOV P1, [0xC200]
MOV P0, P1
MOV R0, P1
MOV SP, FP
POP FP
RET
; Function: cam_cos_of
func_cam_cos_of:
ENTER 2
; var t = ...
; Call to cam_wrap
MOV P2, [FP+4]
PUSH P2
CALL func_cam_wrap
ADD SP, 2 ; Caller cleans up args
MOV P4, P0
MOV [0xC280], P4
; asm {
COS [0xC280]
; }
; Function return
MOV P5, [0xC280]
MOV P0, P5
MOV R0, P5
MOV SP, FP
POP FP
RET
; Function: cam_calc_trig
func_cam_calc_trig:
ENTER 2
; Assignment to cam_yaw
; Call to cam_wrap
MOV P6, [0x8006]
PUSH P6
CALL func_cam_wrap
ADD SP, 2 ; Caller cleans up args
MOV P7, P0
MOV [0x8006], P7
; var t = ...
MOV P0, [0x8006]
MOV [0xC300], P0
; asm {
SIN [0xC300]
; }
; Assignment to cam_sin
MOV P1, [0xC300]
MOV [0x8008], P1
; Assignment to t
MOV P2, [0x8006]
MOV [0xC300], P2
; asm {
COS [0xC300]
; }
; Assignment to cam_cos
MOV P4, [0xC300]
MOV [0x800A], P4
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: cam_set8
func_cam_set8:
ENTER 0
; Assignment to cam_xq
MOV P5, [FP+4]
MOV [0x8000], P5
; Assignment to cam_yq
MOV P6, [FP+6]
MOV [0x8002], P6
; Assignment to cam_zq
MOV P7, [FP+8]
MOV [0x8004], P7
; Assignment to cam_yaw
MOV P0, [FP+10]
MOV [0x8006], P0
; Call to cam_calc_trig
CALL func_cam_calc_trig
MOV P1, P0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: cam_set
func_cam_set:
ENTER 0
; Call to cam_set8
MOV P2, [FP+10]
PUSH P2
MOV P4, [FP+8]
; Unrolled shift SHL by 3
SHL P4, 1
SHL P4, 1
SHL P4, 1
PUSH P4
MOV P5, [FP+6]
; Unrolled shift SHL by 3
SHL P5, 1
SHL P5, 1
SHL P5, 1
PUSH P5
MOV P6, [FP+4]
; Unrolled shift SHL by 3
SHL P6, 1
SHL P6, 1
SHL P6, 1
PUSH P6
CALL func_cam_set8
ADD SP, 8 ; Caller cleans up args
MOV P7, P0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: cam_rotate
func_cam_rotate:
ENTER 0
; Assignment to cam_yaw
MOV P0, [0x8006]
PUSH P0
MOV P1, [FP+4]
POP P0
ADD P0, P1
MOV [0x8006], P0
; Call to cam_calc_trig
CALL func_cam_calc_trig
MOV P2, P0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: cam_forward
func_cam_forward:
ENTER 0
; Assignment to cam_xq
MOV P4, [0x8000]
PUSH P4
; Call to cam_qmul
MOV P5, [0x8008]
PUSH P5
MOV P6, [FP+4]
PUSH P6
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P7, P0
POP P4
ADD P4, P7
MOV [0x8000], P4
; Assignment to cam_zq
MOV P0, [0x8004]
PUSH P0
; Call to cam_qmul
MOV P1, [0x800A]
PUSH P1
MOV P2, [FP+4]
PUSH P2
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P4, P0
POP P0
ADD P0, P4
MOV [0x8004], P0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: cam_strafe
func_cam_strafe:
ENTER 0
; Assignment to cam_xq
MOV P5, [0x8000]
PUSH P5
; Call to cam_qmul
MOV P6, [0x800A]
PUSH P6
MOV P7, [FP+4]
PUSH P7
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
POP P5
ADD P5, P0
MOV [0x8000], P5
; Assignment to cam_zq
MOV P1, [0x8004]
PUSH P1
; Call to cam_qmul
MOV P2, [0x8008]
PUSH P2
MOV P4, [FP+4]
PUSH P4
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P5, P0
POP P1
SUB P1, P5
MOV [0x8004], P1
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: cam_transform
func_cam_transform:
ENTER 12
; var dx = ...
MOV P6, [FP+6]
; Unrolled shift SHL by 5
SHL P6, 1
SHL P6, 1
SHL P6, 1
SHL P6, 1
SHL P6, 1
PUSH P6
MOV P7, [0x8000]
; Unrolled shift SHL by 2
SHL P7, 1
SHL P7, 1
POP P6
SUB P6, P7
MOV [0xC602], P6
; var dy = ...
MOV P0, [FP+8]
; Unrolled shift SHL by 5
SHL P0, 1
SHL P0, 1
SHL P0, 1
SHL P0, 1
SHL P0, 1
PUSH P0
MOV P1, [0x8002]
; Unrolled shift SHL by 2
SHL P1, 1
SHL P1, 1
POP P0
SUB P0, P1
MOV [0xC604], P0
; var dz = ...
MOV P2, [FP+10]
; Unrolled shift SHL by 5
SHL P2, 1
SHL P2, 1
SHL P2, 1
SHL P2, 1
SHL P2, 1
PUSH P2
MOV P4, [0x8004]
; Unrolled shift SHL by 2
SHL P4, 1
SHL P4, 1
POP P2
SUB P2, P4
MOV [0xC606], P2
; Member assignment to ...x
MOV P5, FP
SUB P5, 6
PUSH P5
; Call to cam_qmul
MOV P6, [0x800A]
PUSH P6
MOV P7, [0xC602]
PUSH P7
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
PUSH P0
; Call to cam_qmul
MOV P1, [0x8008]
PUSH P1
MOV P2, [0xC606]
PUSH P2
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P4, P0
POP P0
SUB P0, P4
POP P5
MOV [P5], P0
; Member assignment to ...y
MOV P5, FP
SUB P5, 4
PUSH P5
MOV P6, [0xC604]
POP P5
MOV [P5], P6
; Member assignment to ...z
MOV P7, FP
SUB P7, 2
PUSH P7
; Call to cam_qmul
MOV P0, [0x8008]
PUSH P0
MOV P1, [0xC602]
PUSH P1
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P2, P0
PUSH P2
; Call to cam_qmul
MOV P4, [0x800A]
PUSH P4
MOV P5, [0xC606]
PUSH P5
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P6, P0
POP P2
ADD P2, P6
POP P7
MOV [P7], P2
; Function return
MOV P7, FP
SUB P7, 6
MOV P0, [FP+4] ; sret destination
MOV P1, [P7]
MOV [P0], P1
MOV P1, [P7+2]
MOV [P0+2], P1
MOV P1, [P7+4]
MOV [P0+4], P1
MOV R0, P0
MOV SP, FP
POP FP
RET
; Function: cam_offset
func_cam_offset:
ENTER 10
; If statement
MOV P2, [FP+6]
PUSH P2
MOV P4, [0x0126]
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JLT cmp_true_26
MOV P2, 0
JMP cmp_end_27
cmp_true_26:
MOV P2, 1
cmp_end_27:
CMP P2, 0
JZ if_end_24
; Assignment to vzw
MOV P5, [0x0126]
MOV [FP+6], P5
if_end_24:
; var inv = ...
MOV P6, [0x0120]
; Unrolled shift SHL by 7
SHL P6, 1
SHL P6, 1
SHL P6, 1
SHL P6, 1
SHL P6, 1
SHL P6, 1
SHL P6, 1
PUSH P6
MOV P7, [FP+6]
; Unrolled shift SHR by 1
SHR P7, 1
POP P6
ADD P6, P7
PUSH P6
MOV P0, [FP+6]
POP P6
CMP P6, 0
JGE sdiv_pos_28
NEG P6
CMP P0, 0
JGE sdiv_np_29
NEG P0
DIV P6, P0
JMP sdiv_done_31
sdiv_np_29:
DIV P6, P0
NEG P6
JMP sdiv_done_31
sdiv_pos_28:
CMP P0, 0
JGE sdiv_pp_30
NEG P0
DIV P6, P0
NEG P6
JMP sdiv_done_31
sdiv_pp_30:
DIV P6, P0
sdiv_done_31:
MOV [0xC682], P6
; If statement
MOV P1, [0xC682]
PUSH P1
MOV P2, 1
POP P1
; Signed comparison (two's complement)
CMP P1, P2
JLT cmp_true_34
MOV P1, 0
JMP cmp_end_35
cmp_true_34:
MOV P1, 1
cmp_end_35:
CMP P1, 0
JZ if_end_32
; Assignment to inv
MOV P4, 1
MOV [0xC682], P4
if_end_32:
; var limit = ...
MOV P5, 32767
PUSH P5
MOV P6, [0xC682]
POP P5
CMP P5, 0
JGE sdiv_pos_36
NEG P5
CMP P6, 0
JGE sdiv_np_37
NEG P6
DIV P5, P6
JMP sdiv_done_39
sdiv_np_37:
DIV P5, P6
NEG P5
JMP sdiv_done_39
sdiv_pos_36:
CMP P6, 0
JGE sdiv_pp_38
NEG P6
DIV P5, P6
NEG P5
JMP sdiv_done_39
sdiv_pp_38:
DIV P5, P6
sdiv_done_39:
MOV [0xC684], P5
; var neg = ...
MOV P7, 0
MOV [0xC686], P7
; var m = ...
MOV P0, [FP+4]
MOV [0xC688], P0
; If statement
MOV P1, [0xC688]
PUSH P1
MOV P2, 0
POP P1
; Signed comparison (two's complement)
CMP P1, P2
JLT cmp_true_42
MOV P1, 0
JMP cmp_end_43
cmp_true_42:
MOV P1, 1
cmp_end_43:
CMP P1, 0
JZ if_end_40
; Assignment to neg
MOV P4, 1
MOV [0xC686], P4
; Assignment to m
MOV P5, [0xC688]
NEG P5
MOV [0xC688], P5
if_end_40:
; If statement
MOV P6, [0xC688]
PUSH P6
MOV P7, [0xC684]
POP P6
; Signed comparison (two's complement)
CMP P6, P7
JGT cmp_true_46
MOV P6, 0
JMP cmp_end_47
cmp_true_46:
MOV P6, 1
cmp_end_47:
CMP P6, 0
JZ if_end_44
; Assignment to m
MOV P0, [0xC684]
MOV [0xC688], P0
if_end_44:
; var t = ...
MOV P1, [0xC682]
PUSH P1
MOV P2, [0xC688]
POP P1
MUL P1, P2
; Unrolled shift SHR by 7
SHR P1, 1
SHR P1, 1
SHR P1, 1
SHR P1, 1
SHR P1, 1
SHR P1, 1
SHR P1, 1
MOV [0xC680], P1
; If statement
MOV P4, 0
PUSH P4
MOV P5, [0xC686]
POP P4
CMP P4, P5
JNZ cmp_true_50
MOV P4, 0
JMP cmp_end_51
cmp_true_50:
MOV P4, 1
cmp_end_51:
CMP P4, 0
JZ if_end_48
; Assignment to t
MOV P6, [0xC680]
NEG P6
MOV [0xC680], P6
if_end_48:
; Function return
MOV P7, [0xC680]
MOV P0, P7
MOV R0, P7
MOV SP, FP
POP FP
RET
; Function: cam_depth
func_cam_depth:
ENTER 8
; var v = ...
; Call to cam_transform
MOV P0, [FP+8]
PUSH P0
MOV P1, [FP+6]
PUSH P1
MOV P2, [FP+4]
PUSH P2
; sret dest := &v
MOV P5, FP
SUB P5, 6
MOV P4, P5
PUSH P4 ; sret destination
CALL func_cam_transform
ADD SP, 8 ; Caller cleans up args
MOV P6, P0
; var dz = ...
; Call to cam_asr5
; Member read (z)
MOV P7, FP
SUB P7, 2
MOV P0, [P7]
PUSH P0
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV P1, P0
MOV [0xC700], P1
; If statement
MOV P2, [0xC700]
PUSH P2
MOV P4, [0x0126]
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JLT cmp_true_54
MOV P2, 0
JMP cmp_end_55
cmp_true_54:
MOV P2, 1
cmp_end_55:
CMP P2, 0
JZ if_end_52
; Function return
MOV P5, 0
MOV P0, P5
MOV R0, P5
MOV SP, FP
POP FP
RET
if_end_52:
; Function return
MOV P6, [0xC700]
MOV P0, P6
MOV R0, P6
MOV SP, FP
POP FP
RET
; Function: cam_project
func_cam_project:
ENTER 2
; If statement
; Member read (z)
MOV P7, FP
ADD P7, 8
MOV P0, [P7]
PUSH P0
MOV P1, [0x0128]
POP P0
; Signed comparison (two's complement)
CMP P0, P1
JLT cmp_true_58
MOV P0, 0
JMP cmp_end_59
cmp_true_58:
MOV P0, 1
cmp_end_59:
CMP P0, 0
JZ if_end_56
; Function return
MOV P2, 0
MOV P0, P2
MOV R0, P2
MOV SP, FP
POP FP
RET
if_end_56:
; var z = ...
; Call to cam_asr5
; Member read (z)
MOV P4, FP
ADD P4, 8
MOV P5, [P4]
PUSH P5
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV P6, P0
MOV [0xC780], P6
; Assignment to cam_px
; Call to cam_offset
MOV P7, [0xC780]
PUSH P7
; Call to cam_asr5
; Member read (x)
MOV P0, FP
ADD P0, 4
MOV P1, [P0]
PUSH P1
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV P2, P0
PUSH P2
CALL func_cam_offset
ADD SP, 4 ; Caller cleans up args
MOV P4, P0
PUSH P4
MOV P5, [0x0122]
POP P4
ADD P4, P5
MOV [0x800C], P4
; Assignment to cam_py
MOV P6, [0x0124]
PUSH P6
; Call to cam_offset
MOV P7, [0xC780]
PUSH P7
; Call to cam_asr5
; Member read (y)
MOV P0, FP
ADD P0, 6
MOV P1, [P0]
PUSH P1
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV P2, P0
PUSH P2
CALL func_cam_offset
ADD SP, 4 ; Caller cleans up args
MOV P4, P0
POP P6
SUB P6, P4
MOV [0x800E], P6
; Function return
MOV P5, 1
MOV P0, P5
MOV R0, P5
MOV SP, FP
POP FP
RET
; Function: cam_clip_frac
func_cam_clip_frac:
ENTER 6
; var rem = ...
MOV P6, [FP+4]
MOV [0xC800], P6
; var f = ...
MOV P7, 0
MOV [0xC802], P7
; var i = ...
MOV P0, 0
MOV [0xC804], P0
; While loop
while_start_60:
MOV P1, [0xC804]
PUSH P1
MOV P2, 8
POP P1
; Signed comparison (two's complement)
CMP P1, P2
JLT cmp_true_62
MOV P1, 0
JMP cmp_end_63
cmp_true_62:
MOV P1, 1
cmp_end_63:
CMP P1, 0
JZ while_end_61
; Assignment to rem
MOV P4, [0xC800]
; Unrolled shift SHL by 1
SHL P4, 1
MOV [0xC800], P4
; Assignment to f
MOV P5, [0xC802]
; Unrolled shift SHL by 1
SHL P5, 1
MOV [0xC802], P5
; If statement
MOV P6, [0xC800]
PUSH P6
MOV P7, [FP+6]
POP P6
; Signed comparison (two's complement)
CMP P6, P7
JGE cmp_true_66
MOV P6, 0
JMP cmp_end_67
cmp_true_66:
MOV P6, 1
cmp_end_67:
CMP P6, 0
JZ if_end_64
; Assignment to rem
MOV P0, [0xC800]
PUSH P0
MOV P1, [FP+6]
POP P0
SUB P0, P1
MOV [0xC800], P0
; Assignment to f
MOV P2, [0xC802]
PUSH P2
MOV P4, 1
POP P2
ADD P2, P4
MOV [0xC802], P2
if_end_64:
; Assignment to i
MOV P5, [0xC804]
PUSH P5
MOV P6, 1
POP P5
ADD P5, P6
MOV [0xC804], P5
JMP while_start_60
while_end_61:
; Function return
MOV P7, [0xC802]
MOV P0, P7
MOV R0, P7
MOV SP, FP
POP FP
RET
; Function: cam_clip_axis
func_cam_clip_axis:
ENTER 0
; If statement
MOV P0, [FP+6]
PUSH P0
MOV P1, 0
POP P0
; Signed comparison (two's complement)
CMP P0, P1
JLT cmp_true_70
MOV P0, 0
JMP cmp_end_71
cmp_true_70:
MOV P0, 1
cmp_end_71:
CMP P0, 0
JZ if_end_68
; Assignment to den
MOV P2, [FP+6]
NEG P2
MOV [FP+6], P2
if_end_68:
; If statement
MOV P4, [FP+6]
PUSH P4
MOV P5, 0
POP P4
; Signed comparison (two's complement)
CMP P4, P5
JLE cmp_true_74
MOV P4, 0
JMP cmp_end_75
cmp_true_74:
MOV P4, 1
cmp_end_75:
CMP P4, 0
JZ if_end_72
; Function return
MOV P6, 0
MOV P0, P6
MOV R0, P6
MOV SP, FP
POP FP
RET
if_end_72:
; If statement
MOV P7, [FP+4]
PUSH P7
MOV P0, 0
POP P7
; Signed comparison (two's complement)
CMP P7, P0
JLE cmp_true_78
MOV P7, 0
JMP cmp_end_79
cmp_true_78:
MOV P7, 1
cmp_end_79:
CMP P7, 0
JZ if_end_76
; Function return
MOV P1, 0
MOV P0, P1
MOV R0, P1
MOV SP, FP
POP FP
RET
if_end_76:
; If statement
MOV P2, [FP+4]
PUSH P2
MOV P4, [FP+6]
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JGE cmp_true_82
MOV P2, 0
JMP cmp_end_83
cmp_true_82:
MOV P2, 1
cmp_end_83:
CMP P2, 0
JZ if_end_80
; Function return
MOV P5, 256
MOV P0, P5
MOV R0, P5
MOV SP, FP
POP FP
RET
if_end_80:
; Function return
; Call to cam_clip_frac
MOV P6, [FP+6]
PUSH P6
MOV P7, [FP+4]
PUSH P7
CALL func_cam_clip_frac
ADD SP, 4 ; Caller cleans up args
MOV R0, P0
MOV SP, FP
POP FP
RET
; Function: cam_code
func_cam_code:
ENTER 2
; var c = ...
MOV P1, 0
MOV [0xC900], P1
; If statement
MOV P2, [FP+4]
PUSH P2
MOV P4, 0
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JLT cmp_true_86
MOV P2, 0
JMP cmp_end_87
cmp_true_86:
MOV P2, 1
cmp_end_87:
CMP P2, 0
JZ if_end_84
; Assignment to c
MOV P5, [0xC900]
PUSH P5
MOV P6, 1
POP P5
ADD P5, P6
MOV [0xC900], P5
if_end_84:
; If statement
MOV P7, [FP+4]
PUSH P7
MOV P0, 255
POP P7
; Signed comparison (two's complement)
CMP P7, P0
JGT cmp_true_90
MOV P7, 0
JMP cmp_end_91
cmp_true_90:
MOV P7, 1
cmp_end_91:
CMP P7, 0
JZ if_end_88
; Assignment to c
MOV P1, [0xC900]
PUSH P1
MOV P2, 2
POP P1
ADD P1, P2
MOV [0xC900], P1
if_end_88:
; If statement
MOV P4, [FP+6]
PUSH P4
MOV P5, 0
POP P4
; Signed comparison (two's complement)
CMP P4, P5
JLT cmp_true_94
MOV P4, 0
JMP cmp_end_95
cmp_true_94:
MOV P4, 1
cmp_end_95:
CMP P4, 0
JZ if_end_92
; Assignment to c
MOV P6, [0xC900]
PUSH P6
MOV P7, 4
POP P6
ADD P6, P7
MOV [0xC900], P6
if_end_92:
; If statement
MOV P0, [FP+6]
PUSH P0
MOV P1, 255
POP P0
; Signed comparison (two's complement)
CMP P0, P1
JGT cmp_true_98
MOV P0, 0
JMP cmp_end_99
cmp_true_98:
MOV P0, 1
cmp_end_99:
CMP P0, 0
JZ if_end_96
; Assignment to c
MOV P2, [0xC900]
PUSH P2
MOV P4, 8
POP P2
ADD P2, P4
MOV [0xC900], P2
if_end_96:
; Function return
MOV P5, [0xC900]
MOV P0, P5
MOV R0, P5
MOV SP, FP
POP FP
RET
; Function: cam_draw_clipped
func_cam_draw_clipped:
ENTER 14
; var c1 = ...
; Call to cam_code
MOV P6, [FP+6]
PUSH P6
MOV P7, [FP+4]
PUSH P7
CALL func_cam_code
ADD SP, 4 ; Caller cleans up args
MOV [0xC982], P0
; var c2 = ...
; Call to cam_code
MOV P1, [FP+10]
PUSH P1
MOV P2, [FP+8]
PUSH P2
CALL func_cam_code
ADD SP, 4 ; Caller cleans up args
MOV P4, P0
MOV [0xC984], P4
; var guard = ...
MOV P5, 0
MOV [0xC986], P5
; While loop
while_start_100:
MOV P6, [0xC982]
PUSH P6
MOV P7, [0xC984]
POP P6
ADD P6, P7
PUSH P6
MOV P0, 0
POP P6
CMP P6, P0
JNZ cmp_true_102
MOV P6, 0
JMP cmp_end_103
cmp_true_102:
MOV P6, 1
cmp_end_103:
CMP P6, 0
JZ while_end_101
; If statement
MOV P1, [0xC982]
PUSH P1
MOV P2, [0xC984]
POP P1
AND P1, P2
PUSH P1
MOV P4, 0
POP P1
CMP P1, P4
JNZ cmp_true_106
MOV P1, 0
JMP cmp_end_107
cmp_true_106:
MOV P1, 1
cmp_end_107:
CMP P1, 0
JZ if_end_104
; Function return
MOV P5, 0
MOV P0, P5
MOV R0, P5
MOV SP, FP
POP FP
RET
if_end_104:
; var cx = ...
MOV P6, [FP+4]
MOV [0xC988], P6
; var cy = ...
MOV P7, [FP+6]
MOV [0xC98A], P7
; var cc = ...
MOV P0, [0xC982]
MOV [0xC98C], P0
; If statement
MOV P1, 0
PUSH P1
MOV P2, [0xC982]
POP P1
CMP P1, P2
JZ cmp_true_110
MOV P1, 0
JMP cmp_end_111
cmp_true_110:
MOV P1, 1
cmp_end_111:
CMP P1, 0
JZ if_end_108
; Assignment to cx
MOV P4, [FP+8]
MOV [0xC988], P4
; Assignment to cy
MOV P5, [FP+10]
MOV [0xC98A], P5
; Assignment to cc
MOV P6, [0xC984]
MOV [0xC98C], P6
if_end_108:
; var f = ...
MOV P7, 0
MOV [0xC980], P7
; If statement
MOV P0, 1
PUSH P0
MOV P1, [0xC98C]
POP P0
AND P0, P1
PUSH P0
MOV P2, 0
POP P0
CMP P0, P2
JNZ cmp_true_114
MOV P0, 0
JMP cmp_end_115
cmp_true_114:
MOV P0, 1
cmp_end_115:
CMP P0, 0
JZ if_else_113
; Assignment to f
; Call to cam_clip_axis
MOV P4, [FP+8]
PUSH P4
MOV P5, [FP+4]
POP P4
SUB P4, P5
PUSH P4
MOV P6, 0
PUSH P6
MOV P7, [0xC988]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_clip_axis
ADD SP, 4 ; Caller cleans up args
MOV [0xC980], P0
; Assignment to cx
MOV P1, 0
MOV [0xC988], P1
; Assignment to cy
; Call to cam_qmul
MOV P2, [0xC980]
PUSH P2
MOV P4, [FP+10]
PUSH P4
MOV P5, [FP+6]
POP P4
SUB P4, P5
PUSH P4
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P6, P0
PUSH P6
MOV P7, [FP+6]
POP P6
ADD P6, P7
MOV [0xC98A], P6
JMP if_end_112
if_else_113:
; If statement
MOV P0, 2
PUSH P0
MOV P1, [0xC98C]
POP P0
AND P0, P1
PUSH P0
MOV P2, 0
POP P0
CMP P0, P2
JNZ cmp_true_118
MOV P0, 0
JMP cmp_end_119
cmp_true_118:
MOV P0, 1
cmp_end_119:
CMP P0, 0
JZ if_else_117
; Assignment to f
; Call to cam_clip_axis
MOV P4, [FP+8]
PUSH P4
MOV P5, [FP+4]
POP P4
SUB P4, P5
PUSH P4
MOV P6, 255
PUSH P6
MOV P7, [0xC988]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_clip_axis
ADD SP, 4 ; Caller cleans up args
MOV [0xC980], P0
; Assignment to cx
MOV P1, 255
MOV [0xC988], P1
; Assignment to cy
; Call to cam_qmul
MOV P2, [0xC980]
PUSH P2
MOV P4, [FP+10]
PUSH P4
MOV P5, [FP+6]
POP P4
SUB P4, P5
PUSH P4
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P6, P0
PUSH P6
MOV P7, [FP+6]
POP P6
ADD P6, P7
MOV [0xC98A], P6
JMP if_end_116
if_else_117:
; If statement
MOV P0, 4
PUSH P0
MOV P1, [0xC98C]
POP P0
AND P0, P1
PUSH P0
MOV P2, 0
POP P0
CMP P0, P2
JNZ cmp_true_122
MOV P0, 0
JMP cmp_end_123
cmp_true_122:
MOV P0, 1
cmp_end_123:
CMP P0, 0
JZ if_else_121
; Assignment to f
; Call to cam_clip_axis
MOV P4, [FP+10]
PUSH P4
MOV P5, [FP+6]
POP P4
SUB P4, P5
PUSH P4
MOV P6, 0
PUSH P6
MOV P7, [0xC98A]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_clip_axis
ADD SP, 4 ; Caller cleans up args
MOV [0xC980], P0
; Assignment to cy
MOV P1, 0
MOV [0xC98A], P1
; Assignment to cx
; Call to cam_qmul
MOV P2, [0xC980]
PUSH P2
MOV P4, [FP+8]
PUSH P4
MOV P5, [FP+4]
POP P4
SUB P4, P5
PUSH P4
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P6, P0
PUSH P6
MOV P7, [FP+4]
POP P6
ADD P6, P7
MOV [0xC988], P6
JMP if_end_120
if_else_121:
; Assignment to f
; Call to cam_clip_axis
MOV P0, [FP+10]
PUSH P0
MOV P1, [FP+6]
POP P0
SUB P0, P1
PUSH P0
MOV P2, 255
PUSH P2
MOV P4, [0xC98A]
POP P2
SUB P2, P4
PUSH P2
CALL func_cam_clip_axis
ADD SP, 4 ; Caller cleans up args
MOV P5, P0
MOV [0xC980], P5
; Assignment to cy
MOV P6, 255
MOV [0xC98A], P6
; Assignment to cx
; Call to cam_qmul
MOV P7, [0xC980]
PUSH P7
MOV P0, [FP+8]
PUSH P0
MOV P1, [FP+4]
POP P0
SUB P0, P1
PUSH P0
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P2, P0
PUSH P2
MOV P4, [FP+4]
POP P2
ADD P2, P4
MOV [0xC988], P2
if_end_120:
if_end_116:
if_end_112:
; If statement
MOV P5, 0
PUSH P5
MOV P6, [0xC982]
POP P5
CMP P5, P6
JZ cmp_true_126
MOV P5, 0
JMP cmp_end_127
cmp_true_126:
MOV P5, 1
cmp_end_127:
CMP P5, 0
JZ if_else_125
; Assignment to x2
MOV P7, [0xC988]
MOV [FP+8], P7
; Assignment to y2
MOV P0, [0xC98A]
MOV [FP+10], P0
; Assignment to c2
; Call to cam_code
MOV P1, [FP+10]
PUSH P1
MOV P2, [FP+8]
PUSH P2
CALL func_cam_code
ADD SP, 4 ; Caller cleans up args
MOV P4, P0
MOV [0xC984], P4
JMP if_end_124
if_else_125:
; Assignment to x1
MOV P5, [0xC988]
MOV [FP+4], P5
; Assignment to y1
MOV P6, [0xC98A]
MOV [FP+6], P6
; Assignment to c1
; Call to cam_code
MOV P7, [FP+6]
PUSH P7
MOV P0, [FP+4]
PUSH P0
CALL func_cam_code
ADD SP, 4 ; Caller cleans up args
MOV P1, P0
MOV [0xC982], P1
if_end_124:
; Assignment to guard
MOV P2, [0xC986]
PUSH P2
MOV P4, 1
POP P2
ADD P2, P4
MOV [0xC986], P2
; If statement
MOV P5, [0xC986]
PUSH P5
MOV P6, 4
POP P5
; Signed comparison (two's complement)
CMP P5, P6
JGT cmp_true_130
MOV P5, 0
JMP cmp_end_131
cmp_true_130:
MOV P5, 1
cmp_end_131:
CMP P5, 0
JZ if_end_128
; Function return
MOV P7, 0
MOV P0, P7
MOV R0, P7
MOV SP, FP
POP FP
RET
if_end_128:
JMP while_start_100
while_end_101:
; Call to set_pos
MOV P0, [FP+6]
PUSH P0
MOV P1, [FP+4]
PUSH P1
CALL builtin_set_pos
; Args consumed by callee
MOV P2, R0
; Call to set_color
MOV P4, [FP+12]
PUSH P4
CALL builtin_set_color
; Args consumed by callee
MOV P5, R0
; Call to draw_line
MOV P6, [FP+10]
PUSH P6
MOV P7, [FP+8]
PUSH P7
CALL builtin_draw_line
; Args consumed by callee
MOV P0, R0
; Function return
MOV P1, 1
MOV P0, P1
MOV R0, P1
MOV SP, FP
POP FP
RET
; Function: cam_line
func_cam_line:
ENTER 40
; var a = ...
; Call to cam_transform
MOV P2, [FP+8]
PUSH P2
MOV P4, [FP+6]
PUSH P4
MOV P5, [FP+4]
PUSH P5
; sret dest := &a
MOV P7, FP
SUB P7, 6
MOV P6, P7
PUSH P6 ; sret destination
CALL func_cam_transform
ADD SP, 8 ; Caller cleans up args
; var b = ...
; Call to cam_transform
MOV P1, [FP+14]
PUSH P1
MOV P2, [FP+12]
PUSH P2
MOV P4, [FP+10]
PUSH P4
; sret dest := &b
MOV P6, FP
SUB P6, 12
MOV P5, P6
PUSH P5 ; sret destination
CALL func_cam_transform
ADD SP, 8 ; Caller cleans up args
MOV P7, P0
; If statement
; Member read (z)
MOV P0, FP
SUB P0, 8
MOV P1, [P0]
PUSH P1
MOV P2, [0x0128]
POP P1
; Signed comparison (two's complement)
CMP P1, P2
JLT cmp_true_134
MOV P1, 0
JMP cmp_end_135
cmp_true_134:
MOV P1, 1
cmp_end_135:
PUSH P1
; Member read (z)
MOV P4, FP
SUB P4, 2
MOV P5, [P4]
PUSH P5
MOV P6, [0x0128]
POP P5
; Signed comparison (two's complement)
CMP P5, P6
JLT cmp_true_136
MOV P5, 0
JMP cmp_end_137
cmp_true_136:
MOV P5, 1
cmp_end_137:
POP P1
CMP P1, 0
JZ sc_false_138
; Member read (z)
MOV P7, FP
SUB P7, 2
MOV P0, [P7]
PUSH P0
MOV P1, [0x0128]
POP P0
; Signed comparison (two's complement)
CMP P0, P1
JLT cmp_true_140
MOV P0, 0
JMP cmp_end_141
cmp_true_140:
MOV P0, 1
cmp_end_141:
CMP P0, 0
JZ sc_false_138
MOV P1, 1
JMP sc_end_139
sc_false_138:
MOV P1, 0
sc_end_139:
CMP P1, 0
JZ if_end_132
; Function return
MOV SP, FP
POP FP
RET
if_end_132:
; var ax = ...
; Call to cam_asr5
; Member read (x)
MOV P2, FP
SUB P2, 6
MOV P4, [P2]
PUSH P4
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV P5, P0
MOV [0xCA08], P5
; var ay = ...
; Call to cam_asr5
; Member read (y)
MOV P6, FP
SUB P6, 4
MOV P7, [P6]
PUSH P7
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV [0xCA0A], P0
; var az = ...
; Call to cam_asr5
; Member read (z)
MOV P1, FP
SUB P1, 2
MOV P2, [P1]
PUSH P2
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV P4, P0
MOV [0xCA0C], P4
; var bx = ...
; Call to cam_asr5
; Member read (x)
MOV P5, FP
SUB P5, 12
MOV P6, [P5]
PUSH P6
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV P7, P0
MOV [0xCA0E], P7
; var by = ...
; Call to cam_asr5
; Member read (y)
MOV P0, FP
SUB P0, 10
MOV P1, [P0]
PUSH P1
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV P2, P0
MOV [0xCA10], P2
; var bz = ...
; Call to cam_asr5
; Member read (z)
MOV P4, FP
SUB P4, 8
MOV P5, [P4]
PUSH P5
CALL func_cam_asr5
ADD SP, 2 ; Caller cleans up args
MOV P6, P0
MOV [0xCA12], P6
; If statement
; Member read (z)
MOV P7, FP
SUB P7, 2
MOV P0, [P7]
PUSH P0
MOV P1, [0x0128]
POP P0
; Signed comparison (two's complement)
CMP P0, P1
JLT cmp_true_144
MOV P0, 0
JMP cmp_end_145
cmp_true_144:
MOV P0, 1
cmp_end_145:
CMP P0, 0
JZ if_end_142
; var t = ...
MOV P2, [0xCA08]
MOV [0xCA02], P2
; Assignment to ax
MOV P4, [0xCA0E]
MOV [0xCA08], P4
; Assignment to bx
MOV P5, [0xCA02]
MOV [0xCA0E], P5
; Assignment to t
MOV P6, [0xCA0A]
MOV [0xCA02], P6
; Assignment to ay
MOV P7, [0xCA10]
MOV [0xCA0A], P7
; Assignment to by
MOV P0, [0xCA02]
MOV [0xCA10], P0
; Assignment to t
MOV P1, [0xCA0C]
MOV [0xCA02], P1
; Assignment to az
MOV P2, [0xCA12]
MOV [0xCA0C], P2
; Assignment to bz
MOV P4, [0xCA02]
MOV [0xCA12], P4
if_end_142:
; If statement
MOV P5, [0xCA12]
PUSH P5
MOV P6, [0x0126]
POP P5
; Signed comparison (two's complement)
CMP P5, P6
JLT cmp_true_148
MOV P5, 0
JMP cmp_end_149
cmp_true_148:
MOV P5, 1
cmp_end_149:
CMP P5, 0
JZ if_end_146
; var num = ...
MOV P7, [0xCA0C]
PUSH P7
MOV P0, [0x0126]
POP P7
SUB P7, P0
MOV [0xCA06], P7
; var den = ...
MOV P1, [0xCA0C]
PUSH P1
MOV P2, [0xCA12]
POP P1
SUB P1, P2
MOV [0xCA04], P1
; var f = ...
; Call to cam_clip_frac
MOV P4, [0xCA04]
PUSH P4
MOV P5, [0xCA06]
PUSH P5
CALL func_cam_clip_frac
ADD SP, 4 ; Caller cleans up args
MOV P6, P0
MOV [0xCA00], P6
; Assignment to bx
; Call to cam_qmul
MOV P7, [0xCA00]
PUSH P7
MOV P0, [0xCA0E]
PUSH P0
MOV P1, [0xCA08]
POP P0
SUB P0, P1
PUSH P0
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P2, P0
PUSH P2
MOV P4, [0xCA08]
POP P2
ADD P2, P4
MOV [0xCA0E], P2
; Assignment to by
; Call to cam_qmul
MOV P5, [0xCA00]
PUSH P5
MOV P6, [0xCA10]
PUSH P6
MOV P7, [0xCA0A]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
PUSH P0
MOV P1, [0xCA0A]
POP P0
ADD P0, P1
MOV [0xCA10], P0
; Assignment to bz
MOV P2, [0x0126]
MOV [0xCA12], P2
if_end_146:
; If statement
MOV P4, [0xCA0C]
PUSH P4
MOV P5, [0x0126]
POP P4
; Signed comparison (two's complement)
CMP P4, P5
JLT cmp_true_152
MOV P4, 0
JMP cmp_end_153
cmp_true_152:
MOV P4, 1
cmp_end_153:
CMP P4, 0
JZ if_end_150
; Assignment to az
MOV P6, [0x0126]
MOV [0xCA0C], P6
if_end_150:
; var sx1 = ...
; Call to cam_offset
MOV P7, [0xCA0C]
PUSH P7
MOV P0, [0xCA08]
PUSH P0
CALL func_cam_offset
ADD SP, 4 ; Caller cleans up args
MOV P1, P0
PUSH P1
MOV P2, [0x0122]
POP P1
ADD P1, P2
MOV [0xCA14], P1
; var sy1 = ...
MOV P4, [0x0124]
PUSH P4
; Call to cam_offset
MOV P5, [0xCA0C]
PUSH P5
MOV P6, [0xCA0A]
PUSH P6
CALL func_cam_offset
ADD SP, 4 ; Caller cleans up args
MOV P7, P0
POP P4
SUB P4, P7
MOV [0xCA16], P4
; var sx2 = ...
; Call to cam_offset
MOV P0, [0xCA12]
PUSH P0
MOV P1, [0xCA0E]
PUSH P1
CALL func_cam_offset
ADD SP, 4 ; Caller cleans up args
MOV P2, P0
PUSH P2
MOV P4, [0x0122]
POP P2
ADD P2, P4
MOV [0xCA18], P2
; var sy2 = ...
MOV P5, [0x0124]
PUSH P5
; Call to cam_offset
MOV P6, [0xCA12]
PUSH P6
MOV P7, [0xCA10]
PUSH P7
CALL func_cam_offset
ADD SP, 4 ; Caller cleans up args
POP P5
SUB P5, P0
MOV [0xCA1A], P5
; Call to cam_draw_clipped
MOV P1, [FP+16]
PUSH P1
MOV P2, [0xCA1A]
PUSH P2
MOV P4, [0xCA18]
PUSH P4
MOV P5, [0xCA16]
PUSH P5
MOV P6, [0xCA14]
PUSH P6
CALL func_cam_draw_clipped
ADD SP, 10 ; Caller cleans up args
MOV P7, P0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: wall_run
func_wall_run:
ENTER 0
; Call to cam_line
MOV P0, [FP+8]
PUSH P0
MOV P1, [FP+6]
PUSH P1
MOV P2, [FP+4]
PUSH P2
MOV P4, [0x0130]
PUSH P4
MOV P5, [FP+6]
PUSH P5
MOV P6, [FP+4]
PUSH P6
MOV P7, [0x0130]
NEG P7
PUSH P7
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: room
func_room:
ENTER 4
; var wall = ...
MOV P1, 19
MOV [0xCB00], P1
; var trim = ...
MOV P2, 23
MOV [0xCB02], P2
; Call to cam_line
MOV P4, [0xCB00]
PUSH P4
MOV P5, 0
PUSH P5
MOV P6, [0x0130]
POP P5
SUB P5, P6
PUSH P5
MOV P7, [0x0132]
PUSH P7
MOV P0, [0x0130]
PUSH P0
MOV P1, 0
PUSH P1
MOV P2, [0x0130]
POP P1
SUB P1, P2
PUSH P1
MOV P4, [0x0132]
PUSH P4
MOV P5, [0x0130]
NEG P5
PUSH P5
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P6, P0
; Call to cam_line
MOV P7, [0xCB02]
PUSH P7
MOV P0, 0
PUSH P0
MOV P1, [0x0130]
POP P0
SUB P0, P1
PUSH P0
MOV P2, 16
PUSH P2
MOV P4, [0x0130]
PUSH P4
MOV P5, 0
PUSH P5
MOV P6, [0x0130]
POP P5
SUB P5, P6
PUSH P5
MOV P7, 16
PUSH P7
MOV P0, [0x0130]
NEG P0
PUSH P0
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P1, P0
; Call to cam_line
MOV P2, [0xCB00]
PUSH P2
MOV P4, 0
PUSH P4
MOV P5, [0x0130]
POP P4
SUB P4, P5
PUSH P4
MOV P6, [0x0134]
PUSH P6
MOV P7, [0x0130]
PUSH P7
MOV P0, 0
PUSH P0
MOV P1, [0x0130]
POP P0
SUB P0, P1
PUSH P0
MOV P2, [0x0134]
PUSH P2
MOV P4, [0x0130]
NEG P4
PUSH P4
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P5, P0
; Call to cam_line
MOV P6, [0xCB00]
PUSH P6
MOV P7, [0x0130]
PUSH P7
MOV P0, [0x0132]
PUSH P0
MOV P1, 0
PUSH P1
MOV P2, [0x0136]
POP P1
SUB P1, P2
PUSH P1
MOV P4, [0x0130]
PUSH P4
MOV P5, [0x0132]
PUSH P5
MOV P6, 0
PUSH P6
MOV P7, [0x0130]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, [0xCB00]
PUSH P1
MOV P2, [0x0130]
PUSH P2
MOV P4, [0x0132]
PUSH P4
MOV P5, [0x0130]
PUSH P5
MOV P6, [0x0130]
PUSH P6
MOV P7, [0x0132]
PUSH P7
MOV P0, [0x0136]
PUSH P0
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P1, P0
; Call to cam_line
MOV P2, [0xCB02]
PUSH P2
MOV P4, [0x0130]
PUSH P4
MOV P5, 16
PUSH P5
MOV P6, 0
PUSH P6
MOV P7, [0x0136]
POP P6
SUB P6, P7
PUSH P6
MOV P0, [0x0130]
PUSH P0
MOV P1, 16
PUSH P1
MOV P2, 0
PUSH P2
MOV P4, [0x0130]
POP P2
SUB P2, P4
PUSH P2
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P5, P0
; Call to cam_line
MOV P6, [0xCB02]
PUSH P6
MOV P7, [0x0130]
PUSH P7
MOV P0, 16
PUSH P0
MOV P1, [0x0130]
PUSH P1
MOV P2, [0x0130]
PUSH P2
MOV P4, 16
PUSH P4
MOV P5, [0x0136]
PUSH P5
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P6, P0
; Call to cam_line
MOV P7, [0xCB02]
PUSH P7
MOV P0, [0x0130]
PUSH P0
MOV P1, 64
PUSH P1
MOV P2, [0x0136]
PUSH P2
MOV P4, [0x0130]
PUSH P4
MOV P5, 64
PUSH P5
MOV P6, 0
PUSH P6
MOV P7, [0x0136]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, [0xCB00]
PUSH P1
MOV P2, [0x0130]
PUSH P2
MOV P4, [0x0134]
PUSH P4
MOV P5, [0x0130]
PUSH P5
MOV P6, [0x0130]
PUSH P6
MOV P7, [0x0134]
PUSH P7
MOV P0, [0x0130]
NEG P0
PUSH P0
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P1, P0
; Call to cam_line
MOV P2, [0xCB02]
PUSH P2
MOV P4, [0x0130]
PUSH P4
MOV P5, 64
PUSH P5
MOV P6, 0
PUSH P6
MOV P7, [0x0136]
POP P6
SUB P6, P7
PUSH P6
MOV P0, [0x0130]
PUSH P0
MOV P1, [0x0132]
PUSH P1
MOV P2, 0
PUSH P2
MOV P4, [0x0136]
POP P2
SUB P2, P4
PUSH P2
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P5, P0
; Call to cam_line
MOV P6, [0xCB02]
PUSH P6
MOV P7, [0x0130]
PUSH P7
MOV P0, 64
PUSH P0
MOV P1, [0x0136]
PUSH P1
MOV P2, [0x0130]
PUSH P2
MOV P4, [0x0132]
PUSH P4
MOV P5, [0x0136]
PUSH P5
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P6, P0
; Call to cam_line
MOV P7, [0xCB00]
PUSH P7
MOV P0, [0x0130]
PUSH P0
MOV P1, [0x0132]
PUSH P1
MOV P2, 0
PUSH P2
MOV P4, [0x0130]
POP P2
SUB P2, P4
PUSH P2
MOV P5, 0
PUSH P5
MOV P6, [0x0130]
POP P5
SUB P5, P6
PUSH P5
MOV P7, [0x0132]
PUSH P7
MOV P0, 0
PUSH P0
MOV P1, [0x0130]
POP P0
SUB P0, P1
PUSH P0
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P2, P0
; Call to cam_line
MOV P4, [0xCB00]
PUSH P4
MOV P5, [0x0130]
PUSH P5
MOV P6, [0x0132]
PUSH P6
MOV P7, [0x0130]
PUSH P7
MOV P0, 0
PUSH P0
MOV P1, [0x0130]
POP P0
SUB P0, P1
PUSH P0
MOV P2, [0x0132]
PUSH P2
MOV P4, [0x0130]
PUSH P4
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P5, P0
; Call to cam_line
MOV P6, [0xCB02]
PUSH P6
MOV P7, [0x0130]
PUSH P7
MOV P0, 16
PUSH P0
MOV P1, 0
PUSH P1
MOV P2, [0x0130]
POP P1
SUB P1, P2
PUSH P1
MOV P4, 0
PUSH P4
MOV P5, [0x0130]
POP P4
SUB P4, P5
PUSH P4
MOV P6, 16
PUSH P6
MOV P7, 0
PUSH P7
MOV P0, [0x0130]
POP P7
SUB P7, P0
PUSH P7
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P1, P0
; Call to cam_line
MOV P2, [0xCB02]
PUSH P2
MOV P4, [0x0130]
PUSH P4
MOV P5, 16
PUSH P5
MOV P6, [0x0130]
PUSH P6
MOV P7, 0
PUSH P7
MOV P0, [0x0130]
POP P7
SUB P7, P0
PUSH P7
MOV P1, 16
PUSH P1
MOV P2, [0x0130]
PUSH P2
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P4, P0
; Call to cam_line
MOV P5, [0xCB00]
PUSH P5
MOV P6, [0x0130]
PUSH P6
MOV P7, [0x0134]
PUSH P7
MOV P0, 0
PUSH P0
MOV P1, [0x0130]
POP P0
SUB P0, P1
PUSH P0
MOV P2, 0
PUSH P2
MOV P4, [0x0130]
POP P2
SUB P2, P4
PUSH P2
MOV P5, [0x0134]
PUSH P5
MOV P6, 0
PUSH P6
MOV P7, [0x0130]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, [0xCB00]
PUSH P1
MOV P2, [0x0130]
PUSH P2
MOV P4, [0x0134]
PUSH P4
MOV P5, [0x0130]
PUSH P5
MOV P6, 0
PUSH P6
MOV P7, [0x0130]
POP P6
SUB P6, P7
PUSH P6
MOV P0, [0x0134]
PUSH P0
MOV P1, [0x0130]
PUSH P1
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P2, P0
; Call to cam_line
MOV P4, [0xCB02]
PUSH P4
MOV P5, 0
PUSH P5
MOV P6, [0x0130]
POP P5
SUB P5, P6
PUSH P5
MOV P7, [0x0134]
PUSH P7
MOV P0, 0
PUSH P0
MOV P1, [0x0130]
POP P0
SUB P0, P1
PUSH P0
MOV P2, 0
PUSH P2
MOV P4, [0x0130]
POP P2
SUB P2, P4
PUSH P2
MOV P5, [0x0132]
PUSH P5
MOV P6, 0
PUSH P6
MOV P7, [0x0130]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, [0xCB02]
PUSH P1
MOV P2, 0
PUSH P2
MOV P4, [0x0130]
POP P2
SUB P2, P4
PUSH P2
MOV P5, [0x0134]
PUSH P5
MOV P6, [0x0130]
PUSH P6
MOV P7, 0
PUSH P7
MOV P0, [0x0130]
POP P7
SUB P7, P0
PUSH P7
MOV P1, [0x0132]
PUSH P1
MOV P2, [0x0130]
PUSH P2
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P4, P0
; Call to cam_line
MOV P5, [0xCB02]
PUSH P5
MOV P6, [0x0130]
PUSH P6
MOV P7, [0x0134]
PUSH P7
MOV P0, 0
PUSH P0
MOV P1, [0x0130]
POP P0
SUB P0, P1
PUSH P0
MOV P2, [0x0130]
PUSH P2
MOV P4, [0x0132]
PUSH P4
MOV P5, 0
PUSH P5
MOV P6, [0x0130]
POP P5
SUB P5, P6
PUSH P5
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P7, P0
; Call to cam_line
MOV P0, [0xCB02]
PUSH P0
MOV P1, [0x0130]
PUSH P1
MOV P2, [0x0134]
PUSH P2
MOV P4, [0x0130]
PUSH P4
MOV P5, [0x0130]
PUSH P5
MOV P6, [0x0132]
PUSH P6
MOV P7, [0x0130]
PUSH P7
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: beams
func_beams:
ENTER 2
; For loop
; var k = ...
MOV P1, -1
MOV [0xCB80], P1
for_start_154:
MOV P2, [0xCB80]
PUSH P2
MOV P4, 1
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JLE cmp_true_157
MOV P2, 0
JMP cmp_end_158
cmp_true_157:
MOV P2, 1
cmp_end_158:
CMP P2, 0
JZ for_end_155
; Call to cam_line
MOV P5, 17
PUSH P5
MOV P6, [0x0130]
PUSH P6
MOV P7, [0x0132]
PUSH P7
MOV P0, 96
PUSH P0
MOV P1, [0xCB80]
POP P0
MUL P0, P1
PUSH P0
MOV P2, 0
PUSH P2
MOV P4, [0x0130]
POP P2
SUB P2, P4
PUSH P2
MOV P5, [0x0132]
PUSH P5
MOV P6, 96
PUSH P6
MOV P7, [0xCB80]
POP P6
MUL P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, 17
PUSH P1
MOV P2, [0x0130]
PUSH P2
MOV P4, [0x0134]
PUSH P4
MOV P5, 96
PUSH P5
MOV P6, [0xCB80]
POP P5
MUL P5, P6
PUSH P5
MOV P7, 0
PUSH P7
MOV P0, [0x0130]
POP P7
SUB P7, P0
PUSH P7
MOV P1, [0x0134]
PUSH P1
MOV P2, 96
PUSH P2
MOV P4, [0xCB80]
POP P2
MUL P2, P4
PUSH P2
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P5, P0
for_continue_156:
; Wrap-check: save k before update
MOV P6, [0xCB80]
PUSH P6
MOV P7, [0xCB80]
MOV P0, P7
INC P7
MOV [0xCB80], P7
; Wrap-check: compare k new vs old
POP P1
MOV P2, [0xCB80]
CMP P2, P1
JC for_end_155
JMP for_start_154
for_end_155:
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: marker
func_marker:
ENTER 4
; var mh = ...
MOV P4, 24
MOV [0xCC00], P4
; var mc = ...
MOV P5, 31
MOV [0xCC02], P5
; Call to cam_line
MOV P6, [0xCC02]
PUSH P6
MOV P7, 96
PUSH P7
MOV P0, [0xCC00]
POP P7
SUB P7, P0
PUSH P7
MOV P1, 0
PUSH P1
MOV P2, [0xCC00]
POP P1
SUB P1, P2
PUSH P1
MOV P4, 96
PUSH P4
MOV P5, [0xCC00]
POP P4
ADD P4, P5
PUSH P4
MOV P6, 96
PUSH P6
MOV P7, [0xCC00]
POP P6
SUB P6, P7
PUSH P6
MOV P0, 0
PUSH P0
MOV P1, [0xCC00]
POP P0
SUB P0, P1
PUSH P0
MOV P2, 96
PUSH P2
MOV P4, [0xCC00]
POP P2
SUB P2, P4
PUSH P2
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P5, P0
; Call to cam_line
MOV P6, [0xCC02]
PUSH P6
MOV P7, 96
PUSH P7
MOV P0, [0xCC00]
POP P7
SUB P7, P0
PUSH P7
MOV P1, [0xCC00]
PUSH P1
MOV P2, 96
PUSH P2
MOV P4, [0xCC00]
POP P2
ADD P2, P4
PUSH P2
MOV P5, 96
PUSH P5
MOV P6, [0xCC00]
POP P5
SUB P5, P6
PUSH P5
MOV P7, [0xCC00]
PUSH P7
MOV P0, 96
PUSH P0
MOV P1, [0xCC00]
POP P0
SUB P0, P1
PUSH P0
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P2, P0
; Call to cam_line
MOV P4, [0xCC02]
PUSH P4
MOV P5, 96
PUSH P5
MOV P6, [0xCC00]
POP P5
ADD P5, P6
PUSH P5
MOV P7, 0
PUSH P7
MOV P0, [0xCC00]
POP P7
SUB P7, P0
PUSH P7
MOV P1, 96
PUSH P1
MOV P2, [0xCC00]
POP P1
ADD P1, P2
PUSH P1
MOV P4, 96
PUSH P4
MOV P5, [0xCC00]
POP P4
ADD P4, P5
PUSH P4
MOV P6, 0
PUSH P6
MOV P7, [0xCC00]
POP P6
SUB P6, P7
PUSH P6
MOV P0, 96
PUSH P0
MOV P1, [0xCC00]
POP P0
SUB P0, P1
PUSH P0
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P2, P0
; Call to cam_line
MOV P4, [0xCC02]
PUSH P4
MOV P5, 96
PUSH P5
MOV P6, [0xCC00]
POP P5
ADD P5, P6
PUSH P5
MOV P7, [0xCC00]
PUSH P7
MOV P0, 96
PUSH P0
MOV P1, [0xCC00]
POP P0
ADD P0, P1
PUSH P0
MOV P2, 96
PUSH P2
MOV P4, [0xCC00]
POP P2
ADD P2, P4
PUSH P2
MOV P5, [0xCC00]
PUSH P5
MOV P6, 96
PUSH P6
MOV P7, [0xCC00]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, [0xCC02]
PUSH P1
MOV P2, 96
PUSH P2
MOV P4, [0xCC00]
POP P2
ADD P2, P4
PUSH P2
MOV P5, 0
PUSH P5
MOV P6, [0xCC00]
POP P5
SUB P5, P6
PUSH P5
MOV P7, 96
PUSH P7
MOV P0, [0xCC00]
POP P7
SUB P7, P0
PUSH P7
MOV P1, 96
PUSH P1
MOV P2, [0xCC00]
POP P1
SUB P1, P2
PUSH P1
MOV P4, 0
PUSH P4
MOV P5, [0xCC00]
POP P4
SUB P4, P5
PUSH P4
MOV P6, 96
PUSH P6
MOV P7, [0xCC00]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, [0xCC02]
PUSH P1
MOV P2, 96
PUSH P2
MOV P4, [0xCC00]
POP P2
ADD P2, P4
PUSH P2
MOV P5, 0
PUSH P5
MOV P6, [0xCC00]
POP P5
SUB P5, P6
PUSH P5
MOV P7, 96
PUSH P7
MOV P0, [0xCC00]
POP P7
ADD P7, P0
PUSH P7
MOV P1, 96
PUSH P1
MOV P2, [0xCC00]
POP P1
SUB P1, P2
PUSH P1
MOV P4, 0
PUSH P4
MOV P5, [0xCC00]
POP P4
SUB P4, P5
PUSH P4
MOV P6, 96
PUSH P6
MOV P7, [0xCC00]
POP P6
ADD P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, [0xCC02]
PUSH P1
MOV P2, 96
PUSH P2
MOV P4, [0xCC00]
POP P2
ADD P2, P4
PUSH P2
MOV P5, [0xCC00]
PUSH P5
MOV P6, 96
PUSH P6
MOV P7, [0xCC00]
POP P6
SUB P6, P7
PUSH P6
MOV P0, 96
PUSH P0
MOV P1, [0xCC00]
POP P0
SUB P0, P1
PUSH P0
MOV P2, [0xCC00]
PUSH P2
MOV P4, 96
PUSH P4
MOV P5, [0xCC00]
POP P4
SUB P4, P5
PUSH P4
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P6, P0
; Call to cam_line
MOV P7, [0xCC02]
PUSH P7
MOV P0, 96
PUSH P0
MOV P1, [0xCC00]
POP P0
ADD P0, P1
PUSH P0
MOV P2, [0xCC00]
PUSH P2
MOV P4, 96
PUSH P4
MOV P5, [0xCC00]
POP P4
ADD P4, P5
PUSH P4
MOV P6, 96
PUSH P6
MOV P7, [0xCC00]
POP P6
SUB P6, P7
PUSH P6
MOV P0, [0xCC00]
PUSH P0
MOV P1, 96
PUSH P1
MOV P2, [0xCC00]
POP P1
ADD P1, P2
PUSH P1
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P4, P0
; Call to cam_line
MOV P5, [0xCC02]
PUSH P5
MOV P6, 96
PUSH P6
MOV P7, [0xCC00]
POP P6
SUB P6, P7
PUSH P6
MOV P0, [0xCC00]
PUSH P0
MOV P1, 96
PUSH P1
MOV P2, [0xCC00]
POP P1
SUB P1, P2
PUSH P1
MOV P4, 96
PUSH P4
MOV P5, [0xCC00]
POP P4
SUB P4, P5
PUSH P4
MOV P6, 0
PUSH P6
MOV P7, [0xCC00]
POP P6
SUB P6, P7
PUSH P6
MOV P0, 96
PUSH P0
MOV P1, [0xCC00]
POP P0
SUB P0, P1
PUSH P0
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P2, P0
; Call to cam_line
MOV P4, [0xCC02]
PUSH P4
MOV P5, 96
PUSH P5
MOV P6, [0xCC00]
POP P5
SUB P5, P6
PUSH P5
MOV P7, [0xCC00]
PUSH P7
MOV P0, 96
PUSH P0
MOV P1, [0xCC00]
POP P0
ADD P0, P1
PUSH P0
MOV P2, 96
PUSH P2
MOV P4, [0xCC00]
POP P2
SUB P2, P4
PUSH P2
MOV P5, 0
PUSH P5
MOV P6, [0xCC00]
POP P5
SUB P5, P6
PUSH P5
MOV P7, 96
PUSH P7
MOV P0, [0xCC00]
POP P7
ADD P7, P0
PUSH P7
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P1, P0
; Call to cam_line
MOV P2, [0xCC02]
PUSH P2
MOV P4, 96
PUSH P4
MOV P5, [0xCC00]
POP P4
ADD P4, P5
PUSH P4
MOV P6, [0xCC00]
PUSH P6
MOV P7, 96
PUSH P7
MOV P0, [0xCC00]
POP P7
SUB P7, P0
PUSH P7
MOV P1, 96
PUSH P1
MOV P2, [0xCC00]
POP P1
ADD P1, P2
PUSH P1
MOV P4, 0
PUSH P4
MOV P5, [0xCC00]
POP P4
SUB P4, P5
PUSH P4
MOV P6, 96
PUSH P6
MOV P7, [0xCC00]
POP P6
SUB P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, [0xCC02]
PUSH P1
MOV P2, 96
PUSH P2
MOV P4, [0xCC00]
POP P2
ADD P2, P4
PUSH P2
MOV P5, [0xCC00]
PUSH P5
MOV P6, 96
PUSH P6
MOV P7, [0xCC00]
POP P6
ADD P6, P7
PUSH P6
MOV P0, 96
PUSH P0
MOV P1, [0xCC00]
POP P0
ADD P0, P1
PUSH P0
MOV P2, 0
PUSH P2
MOV P4, [0xCC00]
POP P2
SUB P2, P4
PUSH P2
MOV P5, 96
PUSH P5
MOV P6, [0xCC00]
POP P5
ADD P5, P6
PUSH P5
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P7, P0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: step
func_step:
ENTER 4
; If statement
MOV P0, 0
PUSH P0
MOV P1, [FP+4]
POP P0
CMP P0, P1
JZ cmp_true_161
MOV P0, 0
JMP cmp_end_162
cmp_true_161:
MOV P0, 1
cmp_end_162:
CMP P0, 0
JZ if_end_159
; Assignment to cam_xq
MOV P2, [0x8000]
PUSH P2
; Call to cam_qmul
MOV P4, [0x8008]
PUSH P4
MOV P5, [0x012E]
PUSH P5
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P6, P0
POP P2
ADD P2, P6
MOV [0x8000], P2
; Assignment to cam_zq
MOV P7, [0x8004]
PUSH P7
; Call to cam_qmul
MOV P0, [0x800A]
PUSH P0
MOV P1, [0x012E]
PUSH P1
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P2, P0
POP P7
ADD P7, P2
MOV [0x8004], P7
if_end_159:
; If statement
MOV P4, 1
PUSH P4
MOV P5, [FP+4]
POP P4
CMP P4, P5
JZ cmp_true_165
MOV P4, 0
JMP cmp_end_166
cmp_true_165:
MOV P4, 1
cmp_end_166:
CMP P4, 0
JZ if_end_163
; Assignment to cam_xq
MOV P6, [0x8000]
PUSH P6
; Call to cam_qmul
MOV P7, [0x800A]
PUSH P7
MOV P0, [0x012E]
PUSH P0
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P1, P0
POP P6
ADD P6, P1
MOV [0x8000], P6
; Assignment to cam_zq
MOV P2, [0x8004]
PUSH P2
; Call to cam_qmul
MOV P4, [0x8008]
PUSH P4
MOV P5, [0x012E]
PUSH P5
CALL func_cam_qmul
ADD SP, 4 ; Caller cleans up args
MOV P6, P0
POP P2
SUB P2, P6
MOV [0x8004], P2
if_end_163:
; If statement
MOV P7, 2
PUSH P7
MOV P0, [FP+4]
POP P7
CMP P7, P0
JZ cmp_true_169
MOV P7, 0
JMP cmp_end_170
cmp_true_169:
MOV P7, 1
cmp_end_170:
CMP P7, 0
JZ if_end_167
; Assignment to cam_yaw
MOV P1, [0x8006]
PUSH P1
MOV P2, [0x012C]
POP P1
ADD P1, P2
MOV [0x8006], P1
; Call to cam_calc_trig
CALL func_cam_calc_trig
MOV P4, P0
if_end_167:
; If statement
MOV P5, 3
PUSH P5
MOV P6, [FP+4]
POP P5
CMP P5, P6
JZ cmp_true_173
MOV P5, 0
JMP cmp_end_174
cmp_true_173:
MOV P5, 1
cmp_end_174:
CMP P5, 0
JZ if_end_171
; Assignment to cam_yaw
MOV P7, [0x8006]
PUSH P7
MOV P0, 0
PUSH P0
MOV P1, [0x012C]
POP P0
SUB P0, P1
POP P7
ADD P7, P0
MOV [0x8006], P7
; Call to cam_calc_trig
CALL func_cam_calc_trig
MOV P2, P0
if_end_171:
; var pocket = ...
MOV P4, 0
MOV [0xCC82], P4
; If statement
MOV P5, [0x8004]
PUSH P5
MOV P6, 1408
POP P5
; Signed comparison (two's complement)
CMP P5, P6
JGT cmp_true_177
MOV P5, 0
JMP cmp_end_178
cmp_true_177:
MOV P5, 1
cmp_end_178:
CMP P5, 0
JZ if_end_175
; If statement
MOV P7, [0x8000]
PUSH P7
MOV P0, 320
POP P7
; Signed comparison (two's complement)
CMP P7, P0
JLT cmp_true_181
MOV P7, 0
JMP cmp_end_182
cmp_true_181:
MOV P7, 1
cmp_end_182:
PUSH P7
MOV P1, [0x8000]
PUSH P1
MOV P2, -320
POP P1
; Signed comparison (two's complement)
CMP P1, P2
JGT cmp_true_183
MOV P1, 0
JMP cmp_end_184
cmp_true_183:
MOV P1, 1
cmp_end_184:
POP P7
CMP P7, 0
JZ sc_false_185
MOV P4, [0x8000]
PUSH P4
MOV P5, -320
POP P4
; Signed comparison (two's complement)
CMP P4, P5
JGT cmp_true_187
MOV P4, 0
JMP cmp_end_188
cmp_true_187:
MOV P4, 1
cmp_end_188:
CMP P4, 0
JZ sc_false_185
MOV P7, 1
JMP sc_end_186
sc_false_185:
MOV P7, 0
sc_end_186:
CMP P7, 0
JZ if_end_179
; Assignment to pocket
MOV P6, 1
MOV [0xCC82], P6
if_end_179:
if_end_175:
; If statement
MOV P7, [0x8000]
PUSH P7
MOV P0, -1408
POP P7
; Signed comparison (two's complement)
CMP P7, P0
JLT cmp_true_191
MOV P7, 0
JMP cmp_end_192
cmp_true_191:
MOV P7, 1
cmp_end_192:
CMP P7, 0
JZ if_end_189
; Assignment to cam_xq
MOV P1, -1408
MOV [0x8000], P1
if_end_189:
; If statement
MOV P2, [0x8000]
PUSH P2
MOV P4, 1408
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JGT cmp_true_195
MOV P2, 0
JMP cmp_end_196
cmp_true_195:
MOV P2, 1
cmp_end_196:
CMP P2, 0
JZ if_end_193
; Assignment to cam_xq
MOV P5, 1408
MOV [0x8000], P5
if_end_193:
; If statement
MOV P6, 0
PUSH P6
MOV P7, [0xCC82]
POP P6
CMP P6, P7
JZ cmp_true_199
MOV P6, 0
JMP cmp_end_200
cmp_true_199:
MOV P6, 1
cmp_end_200:
CMP P6, 0
JZ if_else_198
; If statement
MOV P0, [0x8004]
PUSH P0
MOV P1, -1408
POP P0
; Signed comparison (two's complement)
CMP P0, P1
JLT cmp_true_203
MOV P0, 0
JMP cmp_end_204
cmp_true_203:
MOV P0, 1
cmp_end_204:
CMP P0, 0
JZ if_end_201
; Assignment to cam_zq
MOV P2, -1408
MOV [0x8004], P2
if_end_201:
; If statement
MOV P4, [0x8004]
PUSH P4
MOV P5, 1408
POP P4
; Signed comparison (two's complement)
CMP P4, P5
JGT cmp_true_207
MOV P4, 0
JMP cmp_end_208
cmp_true_207:
MOV P4, 1
cmp_end_208:
CMP P4, 0
JZ if_end_205
; Assignment to cam_zq
MOV P6, 1408
MOV [0x8004], P6
if_end_205:
JMP if_end_197
if_else_198:
; If statement
MOV P7, [0x8004]
PUSH P7
MOV P0, 2304
POP P7
; Signed comparison (two's complement)
CMP P7, P0
JGT cmp_true_211
MOV P7, 0
JMP cmp_end_212
cmp_true_211:
MOV P7, 1
cmp_end_212:
CMP P7, 0
JZ if_end_209
; Assignment to cam_zq
MOV P1, 2304
MOV [0x8004], P1
if_end_209:
; If statement
MOV P2, [0x8004]
PUSH P2
MOV P4, -1408
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JLT cmp_true_215
MOV P2, 0
JMP cmp_end_216
cmp_true_215:
MOV P2, 1
cmp_end_216:
CMP P2, 0
JZ if_end_213
; Assignment to cam_zq
MOV P5, -1408
MOV [0x8004], P5
if_end_213:
if_end_197:
; Call to screen_fill
MOV P6, 0
PUSH P6
CALL builtin_screen_fill
; Args consumed by callee
MOV P7, R0
; Call to room
CALL func_room
; For loop
; var k = ...
MOV P1, -1
MOV [0xCC80], P1
for_start_217:
MOV P2, [0xCC80]
PUSH P2
MOV P4, 1
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JLE cmp_true_220
MOV P2, 0
JMP cmp_end_221
cmp_true_220:
MOV P2, 1
cmp_end_221:
CMP P2, 0
JZ for_end_218
; Call to cam_line
MOV P5, 17
PUSH P5
MOV P6, [0x0130]
PUSH P6
MOV P7, [0x0132]
PUSH P7
MOV P0, 96
PUSH P0
MOV P1, [0xCC80]
POP P0
MUL P0, P1
PUSH P0
MOV P2, 0
PUSH P2
MOV P4, [0x0130]
POP P2
SUB P2, P4
PUSH P2
MOV P5, [0x0132]
PUSH P5
MOV P6, 96
PUSH P6
MOV P7, [0xCC80]
POP P6
MUL P6, P7
PUSH P6
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
; Call to cam_line
MOV P1, 17
PUSH P1
MOV P2, [0x0130]
PUSH P2
MOV P4, [0x0134]
PUSH P4
MOV P5, 96
PUSH P5
MOV P6, [0xCC80]
POP P5
MUL P5, P6
PUSH P5
MOV P7, 0
PUSH P7
MOV P0, [0x0130]
POP P7
SUB P7, P0
PUSH P7
MOV P1, [0x0134]
PUSH P1
MOV P2, 96
PUSH P2
MOV P4, [0xCC80]
POP P2
MUL P2, P4
PUSH P2
CALL func_cam_line
ADD SP, 14 ; Caller cleans up args
MOV P5, P0
for_continue_219:
; Wrap-check: save k before update
MOV P6, [0xCC80]
PUSH P6
MOV P7, [0xCC80]
MOV P0, P7
INC P7
MOV [0xCC80], P7
; Wrap-check: compare k new vs old
POP P1
MOV P2, [0xCC80]
CMP P2, P1
JC for_end_218
JMP for_start_217
for_end_218:
; Call to marker
CALL func_marker
MOV P4, P0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: main
func_main:
ENTER 4
; Call to set_layer
MOV P5, 0
PUSH P5
CALL builtin_set_layer
; Args consumed by callee
MOV P6, R0
; Call to screen_fill
MOV P7, 0
PUSH P7
CALL builtin_screen_fill
; Args consumed by callee
MOV P0, R0
; Call to cam_set
MOV P1, 0
PUSH P1
MOV P2, -96
PUSH P2
MOV P4, [0x0138]
PUSH P4
MOV P5, 0
PUSH P5
CALL func_cam_set
ADD SP, 8 ; Caller cleans up args
MOV P6, P0
; For loop
; var f = ...
MOV P7, 0
MOV [0xCD00], P7
for_start_222:
MOV P0, [0xCD00]
PUSH P0
MOV P1, [0x012A]
POP P0
; Signed comparison (two's complement)
CMP P0, P1
JLT cmp_true_225
MOV P0, 0
JMP cmp_end_226
cmp_true_225:
MOV P0, 1
cmp_end_226:
CMP P0, 0
JZ for_end_223
; var op = ...
MOV P2, 0
MOV [0xCD02], P2
; If statement
MOV P4, [0xCD00]
PUSH P4
MOV P5, 30
POP P4
; Signed comparison (two's complement)
CMP P4, P5
JLT cmp_true_229
MOV P4, 0
JMP cmp_end_230
cmp_true_229:
MOV P4, 1
cmp_end_230:
CMP P4, 0
JZ if_else_228
; Assignment to op
MOV P6, 0
MOV [0xCD02], P6
JMP if_end_227
if_else_228:
; If statement
MOV P7, [0xCD00]
PUSH P7
MOV P0, 40
POP P7
; Signed comparison (two's complement)
CMP P7, P0
JLT cmp_true_233
MOV P7, 0
JMP cmp_end_234
cmp_true_233:
MOV P7, 1
cmp_end_234:
CMP P7, 0
JZ if_else_232
; Assignment to op
MOV P1, 1
MOV [0xCD02], P1
JMP if_end_231
if_else_232:
; If statement
MOV P2, [0xCD00]
PUSH P2
MOV P4, 70
POP P2
; Signed comparison (two's complement)
CMP P2, P4
JLT cmp_true_237
MOV P2, 0
JMP cmp_end_238
cmp_true_237:
MOV P2, 1
cmp_end_238:
CMP P2, 0
JZ if_else_236
; Assignment to op
MOV P5, 0
MOV [0xCD02], P5
JMP if_end_235
if_else_236:
; If statement
MOV P6, [0xCD00]
PUSH P6
MOV P7, 100
POP P6
; Signed comparison (two's complement)
CMP P6, P7
JLT cmp_true_241
MOV P6, 0
JMP cmp_end_242
cmp_true_241:
MOV P6, 1
cmp_end_242:
CMP P6, 0
JZ if_else_240
; Assignment to op
MOV P0, 2
MOV [0xCD02], P0
JMP if_end_239
if_else_240:
; If statement
MOV P1, [0xCD00]
PUSH P1
MOV P2, 130
POP P1
; Signed comparison (two's complement)
CMP P1, P2
JLT cmp_true_245
MOV P1, 0
JMP cmp_end_246
cmp_true_245:
MOV P1, 1
cmp_end_246:
CMP P1, 0
JZ if_else_244
; Assignment to op
MOV P4, 0
MOV [0xCD02], P4
JMP if_end_243
if_else_244:
; If statement
MOV P5, [0xCD00]
PUSH P5
MOV P6, 150
POP P5
; Signed comparison (two's complement)
CMP P5, P6
JLT cmp_true_249
MOV P5, 0
JMP cmp_end_250
cmp_true_249:
MOV P5, 1
cmp_end_250:
CMP P5, 0
JZ if_else_248
; Assignment to op
MOV P7, 1
MOV [0xCD02], P7
JMP if_end_247
if_else_248:
; If statement
MOV P0, [0xCD00]
PUSH P0
MOV P1, 170
POP P0
; Signed comparison (two's complement)
CMP P0, P1
JLT cmp_true_253
MOV P0, 0
JMP cmp_end_254
cmp_true_253:
MOV P0, 1
cmp_end_254:
CMP P0, 0
JZ if_else_252
; Assignment to op
MOV P2, 3
MOV [0xCD02], P2
JMP if_end_251
if_else_252:
; Assignment to op
MOV P4, 0
MOV [0xCD02], P4
; If statement
MOV P5, [0xCD00]
PUSH P5
MOV P6, 185
POP P5
; Signed comparison (two's complement)
CMP P5, P6
JGE cmp_true_257
MOV P5, 0
JMP cmp_end_258
cmp_true_257:
MOV P5, 1
cmp_end_258:
CMP P5, 0
JZ if_end_255
; Assignment to op
MOV P7, 2
MOV [0xCD02], P7
if_end_255:
if_end_251:
if_end_247:
if_end_243:
if_end_239:
if_end_235:
if_end_231:
if_end_227:
; Call to step
MOV P0, [0xCD02]
PUSH P0
CALL func_step
ADD SP, 2 ; Caller cleans up args
MOV P1, P0
for_continue_224:
; Wrap-check: save f before update
MOV P2, [0xCD00]
PUSH P2
MOV P4, [0xCD00]
MOV P5, P4
INC P4
MOV [0xCD00], P4
; Wrap-check: compare f new vs old
POP P6
MOV P7, [0xCD00]
CMP P7, P6
JC for_end_223
JMP for_start_222
for_end_223:
; Call to halt
CALL builtin_halt
MOV P0, R0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Built-in Function Implementations
builtin_set_layer:
POP P0
POP P1
MOV VL, P1
PUSH P0
RET
builtin_set_pos:
POP P0
POP P1
POP P2
MOV VX, P1
MOV VY, P2
PUSH P0
RET
builtin_screen_fill:
POP P0
POP P1
SFILL P1
PUSH P0
RET
builtin_set_color:
; Args: color -> VC (drawing color for SRECT/SLINE/SCIRC/CHAR)
POP P0
POP P1
MOV VC, P1
PUSH P0
RET
builtin_draw_line:
; Args: x2, y2 (uses VX/VY as start)
POP P0
POP P1
POP P2
SLINE P1, P2
PUSH P0
RET
builtin_halt:
HLT
; Const data -- read-only program image
ORG 0x0120
; const global 'CAM_FOCAL'
gvar_CAM_FOCAL:
DW 112
ORG 0x0122
; const global 'CAM_CX'
gvar_CAM_CX:
DW 128
ORG 0x0124
; const global 'CAM_CY'
gvar_CAM_CY:
DW 128
ORG 0x0126
; const global 'CAM_NEAR'
gvar_CAM_NEAR:
DW 32
ORG 0x0128
; const global 'CAM_NEAR32'
gvar_CAM_NEAR32:
DW 1024
ORG 0x012A
; const global 'FRAMES'
gvar_FRAMES:
DW 200
ORG 0x012C
; const global 'TURN_STEP'
gvar_TURN_STEP:
DW 12
ORG 0x012E
; const global 'WALK'
gvar_WALK:
DW 32
ORG 0x0130
; const global 'WALL'
gvar_WALL:
DW 192
ORG 0x0132
; const global 'FLOOR'
gvar_FLOOR:
DW 65456
ORG 0x0134
; const global 'CEIL'
gvar_CEIL:
DW 112
ORG 0x0136
; const global 'DOOR'
gvar_DOOR:
DW 48
ORG 0x0138
; const global 'EYE'
gvar_EYE:
DW 65496
ORG 0x8000
; Global Variables
gvar_cam_xq:
DW 0
gvar_cam_yq:
DW 0
gvar_cam_zq:
DW 0
gvar_cam_yaw:
DW 0
gvar_cam_sin:
DW 0
gvar_cam_cos:
DW 256
gvar_cam_px:
DW 0
gvar_cam_py:
DW 0