; Generated by the Astrid Compiler for Nova-16
ORG 0x1000
start:
MOV SP, 0xFFFF ; Set stack pointer to high memory
MOV FP, 0xFFFF ; Also init frame pointer
CALL func_main
HLT
ORG 0x0100
DW func_timer_interrupt
ORG 0x0120
; Function: px_putc
func_px_putc:
ENTER 0
; Call to set_layer
MOV P0, [FP+4]
PUSH P0
CALL builtin_set_layer
; Args consumed by callee
MOV P1, R0
; Call to set_pos
MOV P2, [FP+8]
PUSH P2
MOV P4, [FP+6]
PUSH P4
CALL builtin_set_pos
; Args consumed by callee
MOV P5, R0
; Call to write_screen
MOV P6, [FP+10]
PUSH P6
CALL builtin_write_screen
; Args consumed by callee
MOV P7, R0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: scroll_console
func_scroll_console:
ENTER 0
; Call to set_layer
MOV P0, 5
PUSH P0
CALL builtin_set_layer
; Args consumed by callee
MOV P1, R0
; Call to screen_shift
MOV P2, -8
PUSH P2
MOV P4, 1
PUSH P4
CALL builtin_screen_shift
; Args consumed by callee
MOV P5, R0
; Call to set_color
MOV P6, 0
PUSH P6
CALL builtin_set_color
; Args consumed by callee
MOV P7, R0
; Call to set_pos
MOV P0, 48
PUSH P0
MOV P1, 0
PUSH P1
CALL builtin_set_pos
; Args consumed by callee
MOV P2, R0
; Call to draw_rect
MOV P4, 1
PUSH P4
MOV P5, 55
PUSH P5
MOV P6, 255
PUSH P6
CALL builtin_draw_rect
; Args consumed by callee
MOV P7, R0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: line_advance
func_line_advance:
ENTER 0
; Assignment to cursor_col
MOV P0, 4
MOV [0x8002], P0
MOV P1, [0x8004]
MOV P2, P1
INC P1
MOV [0x8004], P1
; If statement
MOV P4, [0x8004]
PUSH P4
MOV P5, 21
POP P4
CMP P5, P4
JC cmp_true_2
MOV P4, 0
JMP cmp_end_3
cmp_true_2:
MOV P4, 1
cmp_end_3:
CMP P4, 0
JZ if_end_0
; Call to scroll_console
CALL func_scroll_console
MOV P6, P0
; Assignment to cursor_row
MOV P7, 21
MOV [0x8004], P7
if_end_0:
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: win_putc
func_win_putc:
ENTER 0
; If statement
MOV P0, 10
PUSH P0
MOV P1, [FP+4]
POP P0
CMP P0, P1
JZ cmp_true_6
MOV P0, 0
JMP cmp_end_7
cmp_true_6:
MOV P0, 1
cmp_end_7:
PUSH P0
MOV P2, 13
PUSH P2
MOV P4, [FP+4]
POP P2
CMP P2, P4
JZ cmp_true_8
MOV P2, 0
JMP cmp_end_9
cmp_true_8:
MOV P2, 1
cmp_end_9:
POP P0
CMP P0, 0
JNZ sc_true_10
MOV P5, 13
PUSH P5
MOV P6, [FP+4]
POP P5
CMP P5, P6
JZ cmp_true_12
MOV P5, 0
JMP cmp_end_13
cmp_true_12:
MOV P5, 1
cmp_end_13:
CMP P5, 0
JNZ sc_true_10
MOV P0, 0
JMP sc_end_11
sc_true_10:
MOV P0, 1
sc_end_11:
CMP P0, 0
JZ if_end_4
; Call to line_advance
CALL func_line_advance
MOV P7, P0
; Function return
MOV SP, FP
POP FP
RET
if_end_4:
; Call to set_layer
MOV P0, 5
PUSH P0
CALL builtin_set_layer
; Args consumed by callee
MOV P1, R0
; Call to set_color
MOV P2, 31
PUSH P2
CALL builtin_set_color
; Args consumed by callee
MOV P4, R0
; Call to set_pos
MOV P5, [0x8004]
; Unrolled shift SHL by 3
SHL P5, 1
SHL P5, 1
SHL P5, 1
PUSH P5
MOV P6, [0x8002]
; Unrolled shift SHL by 3
SHL P6, 1
SHL P6, 1
SHL P6, 1
PUSH P6
CALL builtin_set_pos
; Args consumed by callee
MOV P7, R0
; Call to draw_char
MOV P0, [FP+4]
PUSH P0
CALL builtin_draw_char
; Args consumed by callee
MOV P1, R0
MOV P2, [0x8002]
MOV P4, P2
INC P2
MOV [0x8002], P2
; If statement
MOV P5, [0x8002]
PUSH P5
MOV P6, 30
POP P5
CMP P5, P6
JNC cmp_true_16
MOV P5, 0
JMP cmp_end_17
cmp_true_16:
MOV P5, 1
cmp_end_17:
CMP P5, 0
JZ if_end_14
; Call to line_advance
CALL func_line_advance
MOV P7, P0
if_end_14:
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: console_prompt
func_console_prompt:
ENTER 0
; Call to win_putc
MOV P0, 62
PUSH P0
CALL func_win_putc
ADD SP, 2 ; Caller cleans up args
MOV P1, P0
; Call to win_putc
MOV P2, 32
PUSH P2
CALL func_win_putc
ADD SP, 2 ; Caller cleans up args
MOV P4, P0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: r_read
func_r_read:
ENTER 4
; var prev = ...
; Call to read_bank
CALL builtin_read_bank
MOV P5, P0
MOV [0xC280], P5
; Call to cli
CALL builtin_cli
MOV P6, R0
; Call to set_bank
MOV P7, [FP+4]
PUSH P7
CALL builtin_set_bank
; Args consumed by callee
MOV P0, R0
; var v = ...
; Call to peek
MOV P1, 32768
PUSH P1
MOV P2, [FP+6]
POP P1
ADD P1, P2
PUSH P1
CALL builtin_peek
; Args consumed by callee
MOV P4, P0
MOV [0xC282], P4
; Call to set_bank
MOV P5, [0xC280]
PUSH P5
CALL builtin_set_bank
; Args consumed by callee
MOV P6, R0
; Call to sti
CALL builtin_sti
MOV P7, R0
; Function return
MOV P0, [0xC282]
MOV R0, P0
MOV SP, FP
POP FP
RET
; Function: r_write
func_r_write:
ENTER 2
; var prev = ...
; Call to read_bank
CALL builtin_read_bank
MOV P1, P0
MOV [0xC300], P1
; Call to cli
CALL builtin_cli
MOV P2, R0
; Call to set_bank
MOV P4, [FP+4]
PUSH P4
CALL builtin_set_bank
; Args consumed by callee
MOV P5, R0
; Call to poke
MOV P6, [FP+8]
PUSH P6
MOV P7, 32768
PUSH P7
MOV P0, [FP+6]
POP P7
ADD P7, P0
PUSH P7
CALL builtin_poke
; Args consumed by callee
MOV P1, R0
; Call to set_bank
MOV P2, [0xC300]
PUSH P2
CALL builtin_set_bank
; Args consumed by callee
MOV P4, R0
; Call to sti
CALL builtin_sti
MOV P5, R0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: clear_video
func_clear_video:
ENTER 2
; For loop
; Assignment to i
MOV P6, 0
MOV [0xC380], P6
for_start_18:
MOV P7, [0xC380]
PUSH P7
MOV P0, 8
POP P7
CMP P7, P0
JC cmp_true_21
MOV P7, 0
JMP cmp_end_22
cmp_true_21:
MOV P7, 1
cmp_end_22:
CMP P7, 0
JZ for_end_19
; Call to set_layer
MOV P1, [0xC380]
PUSH P1
CALL builtin_set_layer
; Args consumed by callee
MOV P2, R0
; Call to screen_fill
MOV P4, 0
PUSH P4
CALL builtin_screen_fill
; Args consumed by callee
MOV P5, R0
for_continue_20:
; Wrap-check: save i before update
MOV P6, [0xC380]
PUSH P6
MOV P7, [0xC380]
MOV P0, P7
INC P7
MOV [0xC380], P7
; Wrap-check: compare i new vs old
POP P1
MOV P2, [0xC380]
CMP P2, P1
JC for_end_19
JMP for_start_18
for_end_19:
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: mount_tables
func_mount_tables:
ENTER 0
; Call to poke
MOV P4, 16
PUSH P4
MOV P5, 16
PUSH P5
CALL builtin_poke
; Args consumed by callee
MOV P6, R0
; Call to poke
MOV P7, 0
PUSH P7
MOV P0, 17
PUSH P0
CALL builtin_poke
; Args consumed by callee
MOV P1, R0
; Call to poke
MOV P2, 15
PUSH P2
MOV P4, 18
PUSH P4
CALL builtin_poke
; Args consumed by callee
MOV P5, R0
; Call to poke
MOV P6, 128
PUSH P6
MOV P7, 20
PUSH P7
CALL builtin_poke
; Args consumed by callee
MOV P0, R0
; Call to poke
MOV P1, 83
PUSH P1
MOV P2, 22
PUSH P2
CALL builtin_poke
; Args consumed by callee
MOV P4, R0
; Call to poke
MOV P5, 83
PUSH P5
MOV P6, 23
PUSH P6
CALL builtin_poke
; Args consumed by callee
MOV P7, R0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: banner
func_banner:
ENTER 0
; Call to set_layer
MOV P0, 1
PUSH P0
CALL builtin_set_layer
; Args consumed by callee
MOV P1, R0
; Call to set_color
MOV P2, 31
PUSH P2
CALL builtin_set_color
; Args consumed by callee
MOV P4, R0
; Call to set_pos
MOV P5, 4
PUSH P5
MOV P6, 4
PUSH P6
CALL builtin_set_pos
; Args consumed by callee
MOV P7, R0
; Call to draw_rect
MOV P0, 0
PUSH P0
MOV P1, 251
PUSH P1
MOV P2, 251
PUSH P2
CALL builtin_draw_rect
; Args consumed by callee
MOV P4, R0
; Call to set_layer
MOV P5, 2
PUSH P5
CALL builtin_set_layer
; Args consumed by callee
MOV P6, R0
; Call to set_color
MOV P7, 23
PUSH P7
CALL builtin_set_color
; Args consumed by callee
MOV P0, R0
; Call to set_pos
MOV P1, 16
PUSH P1
MOV P2, 16
PUSH P2
CALL builtin_set_pos
; Args consumed by callee
MOV P4, R0
; Call to draw_rect
MOV P5, 0
PUSH P5
MOV P6, 180
PUSH P6
MOV P7, 252
PUSH P7
CALL builtin_draw_rect
; Args consumed by callee
MOV P0, R0
; Call to set_layer
MOV P1, 2
PUSH P1
CALL builtin_set_layer
; Args consumed by callee
MOV P2, R0
; Call to set_pos
MOV P4, 24
PUSH P4
MOV P5, 24
PUSH P5
CALL builtin_set_pos
; Args consumed by callee
MOV P6, R0
; Call to write_text
MOV P7, 31
PUSH P7
MOV P0, str_23
PUSH P0
CALL builtin_write_text
; Args consumed by callee
MOV P1, R0
; Call to set_pos
MOV P2, 40
PUSH P2
MOV P4, 24
PUSH P4
CALL builtin_set_pos
; Args consumed by callee
MOV P5, R0
; Call to write_text
MOV P6, 23
PUSH P6
MOV P7, str_24
PUSH P7
CALL builtin_write_text
; Args consumed by callee
MOV P0, R0
; Assignment to cursor_col
MOV P1, 4
MOV [0x8002], P1
; Assignment to cursor_row
MOV P2, 7
MOV [0x8004], P2
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: boot
func_boot:
ENTER 0
; Assignment to ticks
MOV P4, 0
MOV [0x8000], P4
; Assignment to cursor_col
MOV P5, 4
MOV [0x8002], P5
; Assignment to cursor_row
MOV P6, 7
MOV [0x8004], P6
; Assignment to last_key
MOV P7, 0
MOV [0x8006], P7
; Assignment to ramdisk_ok
MOV P0, 0
MOV [0x8008], P0
; Assignment to bank_invariant
MOV P1, 1
MOV [0x800A], P1
; Assignment to booted
MOV P2, 0
MOV [0x800C], P2
; Call to clear_video
CALL func_clear_video
MOV P4, P0
; Call to mount_tables
CALL func_mount_tables
MOV P5, P0
; Call to banner
CALL func_banner
MOV P6, P0
; If statement
; Call to peek
MOV P7, 18
PUSH P7
CALL builtin_peek
; Args consumed by callee
PUSH P0
MOV P1, 15
POP P0
CMP P0, P1
JNZ cmp_true_27
MOV P0, 0
JMP cmp_end_28
cmp_true_27:
MOV P0, 1
cmp_end_28:
PUSH P0
; Call to peek
MOV P2, 22
PUSH P2
CALL builtin_peek
; Args consumed by callee
MOV P4, P0
PUSH P4
MOV P5, 83
POP P4
CMP P4, P5
JNZ cmp_true_29
MOV P4, 0
JMP cmp_end_30
cmp_true_29:
MOV P4, 1
cmp_end_30:
POP P0
CMP P0, 0
JNZ sc_true_31
; Call to peek
MOV P6, 22
PUSH P6
CALL builtin_peek
; Args consumed by callee
MOV P7, P0
PUSH P7
MOV P0, 83
POP P7
CMP P7, P0
JNZ cmp_true_33
MOV P7, 0
JMP cmp_end_34
cmp_true_33:
MOV P7, 1
cmp_end_34:
CMP P7, 0
JNZ sc_true_31
MOV P0, 0
JMP sc_end_32
sc_true_31:
MOV P0, 1
sc_end_32:
CMP P0, 0
JZ if_end_25
; Call to set_layer
MOV P1, 5
PUSH P1
CALL builtin_set_layer
; Args consumed by callee
MOV P2, R0
; Call to set_pos
MOV P4, 200
PUSH P4
MOV P5, 24
PUSH P5
CALL builtin_set_pos
; Args consumed by callee
MOV P6, R0
; Call to write_text
MOV P7, 28
PUSH P7
MOV P0, str_35
PUSH P0
CALL builtin_write_text
; Args consumed by callee
MOV P1, R0
if_end_25:
; Assignment to booted
MOV P2, 1
MOV [0x800C], P2
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: timer_interrupt
func_timer_interrupt:
; Save general registers (interrupt entry only saves PC+flags)
PUSH P0
PUSH P1
PUSH P2
PUSH P3
PUSH P4
PUSH P5
PUSH P6
PUSH P7
PUSH P9
PUSH R0
PUSH R1
PUSH R2
PUSH R3
PUSH R4
PUSH R5
PUSH R6
PUSH R7
PUSH R8
PUSH R9
MOV P4, [0x8000]
MOV P5, P4
INC P4
MOV [0x8000], P4
POP R9
POP R8
POP R7
POP R6
POP R5
POP R4
POP R3
POP R2
POP R1
POP R0
POP P9
POP P7
POP P6
POP P5
POP P4
POP P3
POP P2
POP P1
POP P0
IRET
; Function: ramdisk_selftest
func_ramdisk_selftest:
ENTER 2
; Call to r_write
MOV P6, 83
PUSH P6
MOV P7, 0
PUSH P7
MOV P0, 3
PUSH P0
CALL func_r_write
ADD SP, 6 ; Caller cleans up args
MOV P1, P0
; Call to r_write
MOV P2, 49
PUSH P2
MOV P4, 1
PUSH P4
MOV P5, 3
PUSH P5
CALL func_r_write
ADD SP, 6 ; Caller cleans up args
MOV P6, P0
; var ok = ...
MOV P7, 1
MOV [0xC600], P7
; If statement
; Call to r_read
MOV P0, 0
PUSH P0
MOV P1, 3
PUSH P1
CALL func_r_read
ADD SP, 4 ; Caller cleans up args
MOV P2, P0
PUSH P2
MOV P4, 83
POP P2
CMP P2, P4
JNZ cmp_true_38
MOV P2, 0
JMP cmp_end_39
cmp_true_38:
MOV P2, 1
cmp_end_39:
CMP P2, 0
JZ if_end_36
; Assignment to ok
MOV P5, 0
MOV [0xC600], P5
if_end_36:
; If statement
; Call to r_read
MOV P6, 1
PUSH P6
MOV P7, 3
PUSH P7
CALL func_r_read
ADD SP, 4 ; Caller cleans up args
PUSH P0
MOV P1, 49
POP P0
CMP P0, P1
JNZ cmp_true_42
MOV P0, 0
JMP cmp_end_43
cmp_true_42:
MOV P0, 1
cmp_end_43:
CMP P0, 0
JZ if_end_40
; Assignment to ok
MOV P2, 0
MOV [0xC600], P2
if_end_40:
; If statement
; Call to read_bank
CALL builtin_read_bank
MOV P4, P0
PUSH P4
MOV P5, 0
POP P4
CMP P4, P5
JNZ cmp_true_46
MOV P4, 0
JMP cmp_end_47
cmp_true_46:
MOV P4, 1
cmp_end_47:
CMP P4, 0
JZ if_end_44
; Assignment to ok
MOV P6, 0
MOV [0xC600], P6
; Assignment to bank_invariant
MOV P7, 0
MOV [0x800A], P7
if_end_44:
; If statement
MOV P0, 1
PUSH P0
MOV P1, [0xC600]
POP P0
CMP P0, P1
JZ cmp_true_50
MOV P0, 0
JMP cmp_end_51
cmp_true_50:
MOV P0, 1
cmp_end_51:
CMP P0, 0
JZ if_else_49
; Assignment to ramdisk_ok
MOV P2, 1
MOV [0x8008], P2
; Call to set_layer
MOV P4, 5
PUSH P4
CALL builtin_set_layer
; Args consumed by callee
MOV P5, R0
; Call to set_pos
MOV P6, [0x8004]
; Unrolled shift SHL by 3
SHL P6, 1
SHL P6, 1
SHL P6, 1
PUSH P6
MOV P7, 32
PUSH P7
CALL builtin_set_pos
; Args consumed by callee
MOV P0, R0
; Call to write_text
MOV P1, 30
PUSH P1
MOV P2, str_52
PUSH P2
CALL builtin_write_text
; Args consumed by callee
MOV P4, R0
JMP if_end_48
if_else_49:
; Assignment to ramdisk_ok
MOV P5, 2
MOV [0x8008], P5
; Call to set_layer
MOV P6, 5
PUSH P6
CALL builtin_set_layer
; Args consumed by callee
MOV P7, R0
; Call to set_pos
MOV P0, [0x8004]
; Unrolled shift SHL by 3
SHL P0, 1
SHL P0, 1
SHL P0, 1
PUSH P0
MOV P1, 32
PUSH P1
CALL builtin_set_pos
; Args consumed by callee
MOV P2, R0
; Call to write_text
MOV P4, 28
PUSH P4
MOV P5, str_53
PUSH P5
CALL builtin_write_text
; Args consumed by callee
MOV P6, R0
if_end_48:
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: shutdown
func_shutdown:
ENTER 0
; Call to clear_video
CALL func_clear_video
MOV P7, P0
; Call to set_layer
MOV P0, 5
PUSH P0
CALL builtin_set_layer
; Args consumed by callee
MOV P1, R0
; Call to set_pos
MOV P2, 120
PUSH P2
MOV P4, 96
PUSH P4
CALL builtin_set_pos
; Args consumed by callee
MOV P5, R0
; Call to write_text
MOV P6, 31
PUSH P6
MOV P7, str_54
PUSH P7
CALL builtin_write_text
; Args consumed by callee
MOV P0, R0
; Call to halt
CALL builtin_halt
MOV P1, R0
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: shell
func_shell:
ENTER 2
; Call to console_prompt
CALL func_console_prompt
MOV P2, P0
; While loop
while_start_55:
MOV P4, 1
CMP P4, 0
JZ while_end_56
; If statement
; Call to key_available
CALL builtin_key_available
MOV P5, P0
CMP P5, 0
JZ if_end_57
; var k = ...
; Call to key_read
CALL builtin_key_read
MOV P6, P0
MOV [0xC700], P6
; Assignment to last_key
MOV P7, [0xC700]
MOV [0x8006], P7
; If statement
MOV P0, 27
PUSH P0
MOV P1, [0xC700]
POP P0
CMP P0, P1
JZ cmp_true_61
MOV P0, 0
JMP cmp_end_62
cmp_true_61:
MOV P0, 1
cmp_end_62:
CMP P0, 0
JZ if_else_60
; Call to shutdown
CALL func_shutdown
MOV P2, P0
JMP if_end_59
if_else_60:
; If statement
MOV P4, 10
PUSH P4
MOV P5, [0xC700]
POP P4
CMP P4, P5
JZ cmp_true_65
MOV P4, 0
JMP cmp_end_66
cmp_true_65:
MOV P4, 1
cmp_end_66:
PUSH P4
MOV P6, 13
PUSH P6
MOV P7, [0xC700]
POP P6
CMP P6, P7
JZ cmp_true_67
MOV P6, 0
JMP cmp_end_68
cmp_true_67:
MOV P6, 1
cmp_end_68:
POP P4
CMP P4, 0
JNZ sc_true_69
MOV P0, 13
PUSH P0
MOV P1, [0xC700]
POP P0
CMP P0, P1
JZ cmp_true_71
MOV P0, 0
JMP cmp_end_72
cmp_true_71:
MOV P0, 1
cmp_end_72:
CMP P0, 0
JNZ sc_true_69
MOV P4, 0
JMP sc_end_70
sc_true_69:
MOV P4, 1
sc_end_70:
CMP P4, 0
JZ if_else_64
; Call to line_advance
CALL func_line_advance
MOV P2, P0
; Call to console_prompt
CALL func_console_prompt
MOV P4, P0
JMP if_end_63
if_else_64:
; If statement
MOV P5, 114
PUSH P5
MOV P6, [0xC700]
POP P5
CMP P5, P6
JZ cmp_true_75
MOV P5, 0
JMP cmp_end_76
cmp_true_75:
MOV P5, 1
cmp_end_76:
PUSH P5
MOV P7, 82
PUSH P7
MOV P0, [0xC700]
POP P7
CMP P7, P0
JZ cmp_true_77
MOV P7, 0
JMP cmp_end_78
cmp_true_77:
MOV P7, 1
cmp_end_78:
POP P5
CMP P5, 0
JNZ sc_true_79
MOV P1, 82
PUSH P1
MOV P2, [0xC700]
POP P1
CMP P1, P2
JZ cmp_true_81
MOV P1, 0
JMP cmp_end_82
cmp_true_81:
MOV P1, 1
cmp_end_82:
CMP P1, 0
JNZ sc_true_79
MOV P5, 0
JMP sc_end_80
sc_true_79:
MOV P5, 1
sc_end_80:
CMP P5, 0
JZ if_else_74
; Call to win_putc
MOV P4, [0xC700]
PUSH P4
CALL func_win_putc
ADD SP, 2 ; Caller cleans up args
MOV P5, P0
; Call to line_advance
CALL func_line_advance
MOV P6, P0
; Call to ramdisk_selftest
CALL func_ramdisk_selftest
MOV P7, P0
; Call to line_advance
CALL func_line_advance
; Call to console_prompt
CALL func_console_prompt
MOV P1, P0
JMP if_end_73
if_else_74:
; If statement
MOV P2, [0xC700]
PUSH P2
MOV P4, 127
POP P2
CMP P2, P4
JC cmp_true_85
MOV P2, 0
JMP cmp_end_86
cmp_true_85:
MOV P2, 1
cmp_end_86:
PUSH P2
MOV P5, [0xC700]
PUSH P5
MOV P6, 32
POP P5
CMP P5, P6
JNC cmp_true_87
MOV P5, 0
JMP cmp_end_88
cmp_true_87:
MOV P5, 1
cmp_end_88:
POP P2
CMP P2, 0
JZ sc_false_89
MOV P7, [0xC700]
PUSH P7
MOV P0, 32
POP P7
CMP P7, P0
JNC cmp_true_91
MOV P7, 0
JMP cmp_end_92
cmp_true_91:
MOV P7, 1
cmp_end_92:
CMP P7, 0
JZ sc_false_89
MOV P2, 1
JMP sc_end_90
sc_false_89:
MOV P2, 0
sc_end_90:
CMP P2, 0
JZ if_end_83
; Call to win_putc
MOV P1, [0xC700]
PUSH P1
CALL func_win_putc
ADD SP, 2 ; Caller cleans up args
MOV P2, P0
if_end_83:
if_end_73:
if_end_63:
if_end_59:
if_end_57:
JMP while_start_55
while_end_56:
; Implicit return for void function
MOV SP, FP
POP FP
RET
; Function: main
func_main:
ENTER 0
; Call to boot
CALL func_boot
MOV P4, P0
; Call to set_timer
MOV P5, 3
PUSH P5
MOV P6, 3
PUSH P6
MOV P7, 64
PUSH P7
MOV P0, 0
PUSH P0
CALL builtin_set_timer
; Args consumed by callee
MOV P1, R0
; Call to sti
CALL builtin_sti
MOV P2, R0
; Call to shell
CALL func_shell
MOV P4, P0
; Implicit return for void function
MOV SP, FP
POP FP
RET
;
; Data Section
;
str_23: DEFSTR "STAR SYSTEM 1"
str_24: DEFSTR "C: R: ONLINE - ESC HALTS"
str_35: DEFSTR "MOUNT TABLE CORRUPT"
str_52: DEFSTR "R: OK"
str_53: DEFSTR "R: FAIL"
str_54: DEFSTR "HALT"
; Built-in Function Implementations
builtin_set_layer:
POP P0
POP P1
MOV VL, P1
PUSH P0
RET
builtin_set_pos:
POP P0
POP P1
POP P2
MOV VX, P1
MOV VY, P2
PUSH P0
RET
builtin_write_screen:
POP P0
POP P1
SWRITE P1
PUSH P0
RET
builtin_screen_fill:
POP P0
POP P1
SFILL P1
PUSH P0
RET
builtin_draw_rect:
; Args: x2, y2, filled (start corner from VX/VY, color VC)
POP P0
POP P1
POP P2
POP P3
SRECT P1, P2, P3
PUSH P0
RET
builtin_set_color:
; Args: color -> VC (drawing color for SRECT/SLINE/SCIRC/CHAR)
POP P0
POP P1
MOV VC, P1
PUSH P0
RET
builtin_screen_shift:
; Args: axis, amount
POP P0
POP P1
POP P2
SSHFT P1, P2
PUSH P0
RET
builtin_draw_char:
; Args: char (uses VX/VY position, VC color)
POP P0
POP P1
CHAR P1
PUSH P0
RET
builtin_write_text:
POP P0
POP P1
POP P2
MOV VC, P2
TEXT P1
PUSH P0
RET
builtin_set_timer:
POP P0
POP P1
POP P2
POP P3
POP P4
; Args pushed in reversed source order: stack top->bottom after POP P0 is
; [arg0=TT, arg1=TM, arg2=TS, arg3=TC]. So POP P1=TT, P2=TM, P3=TS, P4=TC.
MOV TT, P1
MOV TM, P2
MOV TS, P3
MOV TC, P4
PUSH P0
RET
builtin_sti:
STI
RET
builtin_cli:
CLI
RET
builtin_key_available:
KEYSTAT P0
RET
builtin_key_read:
KEYIN P0
RET
builtin_peek:
; peek(addr) -> the byte stored at addr.
; The data bus is word-granular and big-endian (the high byte of a
; word lives at the LOWER address), so the byte AT addr is the HIGH
; byte of the word loaded from addr. P-high-byte access (:P syntax
; inverted: Px:) extracts it without any shift sequence.
POP P3
POP P1
MOV P2, [P1]
MOV P0, P2:
PUSH P3
RET
builtin_poke:
; poke(addr, val): store low byte of val at addr.
; No byte-wide store exists on the bus, so this is a read-modify-
; write of the containing word: keep the neighbor byte at addr+1
; masked in place and splice val into the high byte. The 8-left-
; shift also drops anything above bit 7 of val for free.
POP P3
POP P1
POP P2
MOV P4, [P1]
MOV P5, 255
AND P4, P5
MOV P5, P2
; val << 8: unrolled two-operand shifts (the bare "SHL Px" form
; mis-encodes -- the ISA defines SHL as dst,count)
SHL P5, 1
SHL P5, 1
SHL P5, 1
SHL P5, 1
SHL P5, 1
SHL P5, 1
SHL P5, 1
SHL P5, 1
OR P4, P5
MOV [P1], P4
PUSH P3
RET
builtin_set_bank:
; set_bank(n): aim the 0x8000-0xBFFF window at page n.
; Hardware clamps to 0-15 and invalidates the instruction cache;
; banked writes never touch base RAM (see nova/memory/memory.py).
POP P0
POP P1
MOV BANK, P1
PUSH P0
RET
builtin_read_bank:
; read_bank() -> currently visible page number (0-15).
; Clear P0 first so the R->P move can never inherit stale
; high-byte garbage from earlier expression evaluation.
MOV P0, 0
MOV R0, BANK
MOV P0, R0
RET
builtin_halt:
HLT
ORG 0x8000
; Global Variables
gvar_ticks:
DS 2
gvar_cursor_col:
DS 2
gvar_cursor_row:
DS 2
gvar_last_key:
DS 2
gvar_ramdisk_ok:
DS 2
gvar_bank_invariant:
DS 2
gvar_booted:
DS 2