# Astrid Language Code Generator
# File: astrid/codegen/codegen.py
# Translates Astrid AST to Nova-16 assembly code

from typing import List, Dict, Optional, Set
from astrid.parser.parser import (
    Program, FunctionDef, VarDecl, Assignment, Return, If, While, DoWhile, For, FuncCall,
    Switch, Case,
    Expression, Number, StringLiteral, CharLiteral, Identifier, BinaryOp, UnaryOp, PostfixOp,
    Break, Continue
)

class CodeGenerator:
    """Generates Nova-16 assembly code from Astrid AST"""

    def __init__(self):
        self.assembly = []
        self.global_vars = {}
        self.local_vars = {}
        self.functions = {}
        self.strings = {}
        self.string_counter = 0
        self.label_counter = 0
        self.reg_counter = 0 
        self.current_function = None
        self.builtin_functions = self._init_builtins()
        # Stack of (start_label, end_label) for break/continue support
        self.loop_stack = []

    def _init_builtins(self) -> Dict[str, str]:
        """Initialize built-in function to assembly mappings"""
        return {
            'set_mode': 'builtin_set_vmode', 'set_vmode': 'builtin_set_vmode',
            'set_layer': 'builtin_set_layer', 'set_pos': 'builtin_set_pos',
            'write_screen': 'builtin_write_screen', 'read_screen': 'builtin_read_screen',
            'scroll_x': 'builtin_scroll_x', 'scroll_y': 'builtin_scroll_y',
            'set_pointers': 'builtin_set_pointers', 'write_text': 'builtin_write_text',
            'set_font': 'builtin_set_font', 'sound_play': 'builtin_sound_play',
            'sound_stop': 'builtin_sound_stop', 'set_timer': 'builtin_set_timer',
            'sti': 'builtin_sti', 'cli': 'builtin_cli', 'iret': 'builtin_iret',
            'key_available': 'builtin_key_available', 'key_read': 'builtin_key_read',
            'key_clear': 'builtin_key_clear', 'random': 'builtin_random',
            'random_range': 'builtin_random_range', 'halt': 'builtin_halt',
            'enable_interrupts': 'builtin_sti', 'disable_interrupts': 'builtin_cli'
        }

    def generate(self, ast: Program) -> List[str]:
        self.assembly.append("; Generated by the Astrid Compiler for Nova-16")
        
        # Main entry point MUST be first segment so emulator sets PC correctly
        self.assembly.append("ORG 0x1000")
        self.assembly.append("start:")
        self.assembly.append("    MOV SP, 0xFF00 ; Set stack pointer to high memory")
        self.assembly.append("    MOV FP, 0xFF00 ; Also init frame pointer")
        self.assembly.append("    CALL func_main")
        self.assembly.append("    HLT")
        self.assembly.append("")

        # Emit interrupt vector FIRST at 0x0100 (before functions)
        if any(func.name == 'timer_interrupt' for func in ast.functions):
            self.assembly.append("ORG 0x0100")
            self.assembly.append("    DW func_timer_interrupt")
            self.assembly.append("")

        # Generate all functions and data AFTER interrupt vector
        for func_def in ast.functions:
            self.generate_function(func_def)

        self.generate_strings()
        self.generate_builtins()

        return self.assembly

    def generate_strings(self):
        if not self.strings:
            return
        self.assembly.append(";")
        self.assembly.append("; Data Section")
        self.assembly.append(";")
        for value, label in self.strings.items():
            self.assembly.append(f"{label}: DEFSTR \"{value}\"")
        self.assembly.append("")

    def find_local_vars(self, statements: List) -> List[VarDecl]:
        """Recursively find all VarDecl nodes in a list of statements."""
        decls = []
        for stmt in statements:
            if isinstance(stmt, VarDecl):
                decls.append(stmt)
            elif isinstance(stmt, list):
                decls.extend(self.find_local_vars(stmt))
            elif isinstance(stmt, If):
                decls.extend(self.find_local_vars(stmt.then_body))
                if stmt.else_body:
                    decls.extend(self.find_local_vars(stmt.else_body))
            elif isinstance(stmt, While):
                decls.extend(self.find_local_vars(stmt.body))
            elif isinstance(stmt, DoWhile):
                decls.extend(self.find_local_vars(stmt.body))
            elif isinstance(stmt, For):
                if isinstance(stmt.init, list):
                    decls.extend(stmt.init)
                decls.extend(self.find_local_vars(stmt.body))
            elif isinstance(stmt, Switch):
                for case in stmt.cases:
                    decls.extend(self.find_local_vars(case.body))
                if stmt.default_body:
                    decls.extend(self.find_local_vars(stmt.default_body))
        return decls

    def _get_local_offset(self, name: str) -> int:
        offset = self.local_vars[name]['offset']
        return offset

    def _emit_local_load(self, reg: str, name: str):
        offset = self._get_local_offset(name)
        if self.current_function == 'timer_interrupt':
            # Interrupt handler uses SP-relative locals (no ENTER/FP)
            self.emit(f"    MOV {reg}, [SP-{-offset}]")
        else:
            self.emit(f"    MOV P2, FP")
            if offset > 0:
                self.emit(f"    ADD P2, {offset}")
            else:
                self.emit(f"    SUB P2, {-offset}")
            self.emit(f"    MOV {reg}, [P2]")

    def _emit_local_store(self, name: str, src_reg: str):
        offset = self._get_local_offset(name)
        if self.current_function == 'timer_interrupt':
            # Interrupt handler uses SP-relative locals (no ENTER/FP)
            self.emit(f"    MOV [SP-{-offset}], {src_reg}")
        else:
            self.emit(f"    MOV P2, FP")
            if offset > 0:
                self.emit(f"    ADD P2, {offset}")
            else:
                self.emit(f"    SUB P2, {-offset}")
            self.emit(f"    MOV [P2], {src_reg}")

    def generate_function(self, func_def: FunctionDef):
        self.functions[func_def.name] = {
            'label': f'func_{func_def.name}',
            'params': len(func_def.params),
            'return_type': func_def.return_type
        }
        
        self.current_function = func_def.name
        self.local_vars = {}
        
        self.assembly.append(f"; Function: {func_def.name}")
        self.assembly.append(f"func_{func_def.name}:")
        
        all_local_decls = self.find_local_vars(func_def.body)
        locals_size = len(all_local_decls)
        
        if func_def.name == 'timer_interrupt':
            # Interrupt handlers must NOT use ENTER/LEAVE because the CPU
            # already pushed PC and flags on the stack. Use direct SP
            # manipulation instead so IRET can find the saved context.
            if locals_size > 0:
                self.assembly.append(f"    SUB SP, {locals_size} ; Allocate locals")
        else:
            self.assembly.append(f"    ENTER {locals_size}")

        for i, param in enumerate(func_def.params):
            self.local_vars[param.name] = {'offset': i + 4}

        for i, decl in enumerate(all_local_decls):
            self.local_vars[decl.name] = {'offset': -(i + 1)}

        # Store locals_size for iret() cleanup
        self._timer_interrupt_locals_size = locals_size if func_def.name == 'timer_interrupt' else 0
        self._emitted_return = False
        self.generate_block(func_def.body)

        # Only emit implicit return if the function didn't already return (e.g. via iret)
        if func_def.return_type == 'void' and not self._emitted_return:
            self.assembly.append("; Implicit return for void function")
            self.assembly.append("    MOV SP, FP")
            self.assembly.append("    POP FP")
            self.assembly.append("    RET")

        self.assembly.append("")
        self.current_function = None

    def generate_block(self, body: List):
        for statement in body:
            if isinstance(statement, list):
                self.generate_block(statement)
            elif isinstance(statement, VarDecl):
                self.generate_var_decl(statement)
            elif isinstance(statement, Assignment):
                self.generate_assignment(statement)
            elif isinstance(statement, Return):
                self.generate_return(statement)
            elif isinstance(statement, If):
                self.generate_if(statement)
            elif isinstance(statement, While):
                self.generate_while(statement)
            elif isinstance(statement, DoWhile):
                self.generate_do_while(statement)
            elif isinstance(statement, Switch):
                self.generate_switch(statement)
            elif isinstance(statement, For):
                self.generate_for(statement)
            elif isinstance(statement, Break):
                self.generate_break()
            elif isinstance(statement, Continue):
                self.generate_continue()
            elif isinstance(statement, FuncCall):
                if statement.name == 'iret' and self.current_function == 'timer_interrupt':
                    # Special handling for iret: don't emit normal epilogue
                    if hasattr(self, '_timer_interrupt_locals_size') and self._timer_interrupt_locals_size > 0:
                        self.emit(f"    ADD SP, {self._timer_interrupt_locals_size} ; Deallocate locals before IRET")
                    self.emit("    IRET")
                    self._emitted_return = True
                    return  # Exit function after IRET
                else:
                    self.generate_call(statement)
            elif isinstance(statement, Expression):
                self.generate_expression(statement)
            else:
                raise RuntimeError(f"Unknown statement type: {type(statement)}")

    def generate_var_decl(self, var_decl: VarDecl):
        if var_decl.value:
            self.emit_comment(f"var {var_decl.name} = ...")
            reg = self.generate_expression(var_decl.value)
            self._emit_local_store(var_decl.name, reg)
            self.free_register()

    def generate_assignment(self, assignment: Assignment):
        self.emit_comment(f"Assignment to {assignment.name}")
        # Check for compound assignment pattern: x = x <op> rhs
        # The parser decomposes x += y into Assignment('x', BinaryOp(Identifier('x'), '+', y))
        if (isinstance(assignment.value, BinaryOp) and
            isinstance(assignment.value.left, Identifier) and
            assignment.value.left.name == assignment.name):
            op = assignment.value.op
            var_reg = self.get_register()
            self._emit_local_load(var_reg, assignment.name)
            if op in ['<<', '>>']:
                # Shift operations: amount must be a constant (parser requires this)
                if not isinstance(assignment.value.right, Number):
                    raise TypeError("Shift amount must be a constant integer for this compiler version.")
                shift_amount = int(assignment.value.right.value, 0)
                op_mnemonic = "SHR" if op == '>>' else "SHL"
                self.emit_comment(f"Compound shift {op_mnemonic} by {shift_amount}")
                for _ in range(shift_amount):
                    self.emit(f"    {op_mnemonic} {var_reg}")
            else:
                rhs_reg = self.generate_expression(assignment.value.right)
                if op == '+': self.emit(f"    ADD {var_reg}, {rhs_reg}")
                elif op == '-': self.emit(f"    SUB {var_reg}, {rhs_reg}")
                elif op == '*': self.emit(f"    MUL {var_reg}, {rhs_reg}")
                elif op == '/': self.emit(f"    DIV {var_reg}, {rhs_reg}")
                elif op == '&': self.emit(f"    AND {var_reg}, {rhs_reg}")
                elif op == '|': self.emit(f"    OR {var_reg}, {rhs_reg}")
                elif op == '^': self.emit(f"    XOR {var_reg}, {rhs_reg}")
                else: raise SyntaxError(f"Unknown compound operator '{op}'")
                self.free_register()
            self._emit_local_store(assignment.name, var_reg)
            self.free_register()
        else:
            reg = self.generate_expression(assignment.value)
            if assignment.name in self.local_vars:
                self._emit_local_store(assignment.name, reg)
            else:
                raise NameError(f"Undefined variable '{assignment.name}'")
            self.free_register()

    def generate_return(self, return_stmt: Return):
        self.emit_comment("Function return")
        if return_stmt.value:
            reg = self.generate_expression(return_stmt.value)
            self.emit(f"    MOV R0, {reg}")
            self.free_register()
        self.emit("    MOV SP, FP")
        self.emit("    POP FP")
        self.emit("    RET")
        self._emitted_return = True

    def generate_if(self, if_stmt: If):
        self.emit_comment("If statement")
        end_label = self.generate_label("if_end")
        else_label = self.generate_label("if_else")
        reg = self.generate_expression(if_stmt.cond)
        self.emit(f"    CMP {reg}, 0")
        self.free_register()
        self.emit(f"    JZ {else_label if if_stmt.else_body else end_label}")
        self.generate_block(if_stmt.then_body)
        if if_stmt.else_body:
            self.emit(f"    JMP {end_label}")
            self.emit_label(else_label)
            self.generate_block(if_stmt.else_body)
        self.emit_label(end_label)

    def generate_while(self, while_stmt: While):
        self.emit_comment("While loop")
        start_label = self.generate_label("while_start")
        end_label = self.generate_label("while_end")
        # For while loops, continue jumps to the start (condition check)
        self.loop_stack.append((start_label, end_label))
        self.emit_label(start_label)
        reg = self.generate_expression(while_stmt.cond)
        self.emit(f"    CMP {reg}, 0")
        self.free_register()
        self.emit(f"    JZ {end_label}")
        self.generate_block(while_stmt.body)
        self.emit(f"    JMP {start_label}")
        self.emit_label(end_label)
        self.loop_stack.pop()

    def generate_for(self, for_stmt: For):
        self.emit_comment("For loop")
        start_label = self.generate_label("for_start")
        end_label = self.generate_label("for_end")
        # For for loops, continue jumps to the update expression
        # We use a separate continue_label that points to the update section
        continue_label = self.generate_label("for_continue")
        self.loop_stack.append((continue_label, end_label))

        if for_stmt.init:
            self.generate_block([for_stmt.init])

        self.emit_label(start_label)

        if for_stmt.cond:
            reg = self.generate_expression(for_stmt.cond)
            self.emit(f"    CMP {reg}, 0")
            self.free_register()
            self.emit(f"    JZ {end_label}")

        self.generate_block(for_stmt.body)

        # Continue target: update expression
        self.emit_label(continue_label)
        if for_stmt.update:
            self.generate_block([for_stmt.update])
            
        self.emit(f"    JMP {start_label}")
        self.emit_label(end_label)
        self.loop_stack.pop()

    def generate_do_while(self, stmt: DoWhile):
        """Generate code for do-while loop: do { body } while (cond);"""
        self.emit_comment("Do-While loop")
        start_label = self.generate_label("dowhile_start")
        end_label = self.generate_label("dowhile_end")
        # For do-while, continue jumps to the start of the loop body
        self.loop_stack.append((start_label, end_label))
        self.emit_label(start_label)
        self.generate_block(stmt.body)
        reg = self.generate_expression(stmt.cond)
        self.emit(f"    CMP {reg}, 0")
        self.free_register()
        self.emit(f"    JNZ {start_label}")  # Loop back if condition is true
        self.emit_label(end_label)
        self.loop_stack.pop()

    def generate_switch(self, stmt: Switch):
        """Generate code for switch/case statement.

        Compiles to a series of comparisons (CMP/JZ) against each case value.
        Supports break and C-style fall-through between cases (no break).
        """
        self.emit_comment("Switch statement")
        end_label = self.generate_label("switch_end")
        # Push loop context so break inside switch exits to end_label.
        # No continue target (None) because continue is not valid in switch.
        self.loop_stack.append((None, end_label))

        reg = self.generate_expression(stmt.expr)

        # Pre-generate labels for each case body
        case_labels = [self.generate_label("case") for _ in stmt.cases]

        # Emit comparisons for each case value
        for i, case in enumerate(stmt.cases):
            case_val_reg = self.generate_expression(case.value)
            self.emit(f"    CMP {reg}, {case_val_reg}")
            self.free_register()  # free case_val_reg
            self.emit(f"    JZ {case_labels[i]}")

        # If no case matched, go to default or end
        if stmt.default_body:
            self.generate_block(stmt.default_body)
            self.emit(f"    JMP {end_label}")
        else:
            self.emit(f"    JMP {end_label}")

        # Emit case bodies (fall-through is natural between consecutive cases)
        for i, case in enumerate(stmt.cases):
            self.emit_label(case_labels[i])
            self.generate_block(case.body)

        self.emit_label(end_label)
        self.loop_stack.pop()

    def generate_break(self):
        """Generate assembly for a break statement - jump to loop end."""
        if not self.loop_stack:
            raise RuntimeError("break statement outside of loop")
        _, end_label = self.loop_stack[-1]
        self.emit_comment("break")
        self.emit(f"    JMP {end_label}")

    def generate_continue(self):
        """Generate assembly for a continue statement - jump to loop continue target."""
        if not self.loop_stack:
            raise RuntimeError("continue statement outside of loop")
        continue_label, _ = self.loop_stack[-1]
        if continue_label is None:
            raise RuntimeError("continue statement is not valid inside a switch")
        self.emit_comment("continue")
        self.emit(f"    JMP {continue_label}")

    def generate_expression(self, expr: Expression) -> str:
        if isinstance(expr, Number):
            reg = self.get_register()
            self.emit(f"    MOV {reg}, {expr.value}")
            return reg
        elif isinstance(expr, StringLiteral):
            reg = self.get_register()
            label = self.get_string_label(expr.value)
            self.emit(f"    MOV {reg}, {label}")
            return reg
        elif isinstance(expr, CharLiteral):
            reg = self.get_register()
            self.emit(f"    MOV {reg}, {expr.char_value}")
            return reg
        elif isinstance(expr, Identifier):
            reg = self.get_register()
            if expr.name in self.local_vars:
                self._emit_local_load(reg, expr.name)
                return reg
            else:
                raise NameError(f"Undefined variable '{expr.name}'")
        elif isinstance(expr, BinaryOp):
            if (expr.op == '&' and isinstance(expr.right, Number) and expr.right.value in ('0xFF', '255')):
                if (isinstance(expr.left, BinaryOp) and expr.left.op == '>>' and 
                    isinstance(expr.left.right, Number) and expr.left.right.value == '8'):
                    self.emit_comment("Optimized high-byte access: (val >> 8) & 0xFF")
                    val_reg = self.generate_expression(expr.left.left)
                    result_reg = self.get_register()
                    if val_reg.startswith('P'):
                        self.emit(f"    MOV {result_reg}, {val_reg}:")
                    else:
                        self.emit(f"    MOV {result_reg}, {val_reg}")
                    self.free_register()
                    return result_reg
                else:
                    self.emit_comment("Optimized low-byte access: val & 0xFF")
                    val_reg = self.generate_expression(expr.left)
                    result_reg = self.get_register()
                    if val_reg.startswith('P'):
                        self.emit(f"    MOV {result_reg}, :{val_reg}")
                    else:
                        self.emit(f"    MOV {result_reg}, {val_reg}")
                    self.free_register()
                    return result_reg
            
            if expr.op == '>>' or expr.op == '<<':
                if not isinstance(expr.right, Number):
                    raise TypeError("Shift amount must be a constant integer for this compiler version.")
                left_reg = self.generate_expression(expr.left)
                shift_amount = int(expr.right.value, 0)
                op_mnemonic = "SHR" if expr.op == '>>' else "SHL"
                self.emit_comment(f"Unrolled shift {op_mnemonic} by {shift_amount}")
                for _ in range(shift_amount):
                    self.emit(f"    {op_mnemonic} {left_reg}")
                return left_reg

            left_reg = self.generate_expression(expr.left)
            right_reg = self.generate_expression(expr.right)
            op = expr.op
            if op == '+': self.emit(f"    ADD {left_reg}, {right_reg}")
            elif op == '-': self.emit(f"    SUB {left_reg}, {right_reg}")
            elif op == '*': self.emit(f"    MUL {left_reg}, {right_reg}")
            elif op == '/': self.emit(f"    DIV {left_reg}, {right_reg}")
            elif op == '%': self.emit(f"    MOD {left_reg}, {right_reg}")
            elif op in ['==', '!=', '>', '<', '>=', '<=']:
                self.emit(f"    CMP {left_reg}, {right_reg}")
                jmp_map = {'==': 'JZ', '!=': 'JNZ', '>': 'JGT', '<': 'JLT', '>=': 'JGE', '<=': 'JLE'}
                true_label = self.generate_label("cmp_true")
                end_label = self.generate_label("cmp_end")
                self.emit(f"    {jmp_map[op]} {true_label}")
                self.emit(f"    MOV {left_reg}, 0")
                self.emit(f"    JMP {end_label}")
                self.emit_label(true_label)
                self.emit(f"    MOV {left_reg}, 1")
                self.emit_label(end_label)
            elif op == '&&': self.emit(f"    AND {left_reg}, {right_reg}")
            elif op == '||': self.emit(f"    OR {left_reg}, {right_reg}")
            elif op == '&': self.emit(f"    AND {left_reg}, {right_reg}")
            elif op == '|': self.emit(f"    OR {left_reg}, {right_reg}")
            elif op == '^': self.emit(f"    XOR {left_reg}, {right_reg}")
            else: raise SyntaxError(f"Unknown binary operator '{op}'")
            self.free_register()
            return left_reg
        elif isinstance(expr, UnaryOp):
            reg = self.generate_expression(expr.right)
            op = expr.op
            if op == '-': self.emit(f"    NEG {reg}")
            elif op == '!': self.emit(f"    NOT {reg}")
            elif op == '~': self.emit(f"    INV {reg}")
            else: raise SyntaxError(f"Unknown unary operator '{op}'")
            return reg
        elif isinstance(expr, PostfixOp):
            if not isinstance(expr.left, Identifier):
                raise SyntaxError("Postfix operators can only be applied to identifiers")
            reg = self.get_register()
            self._emit_local_load(reg, expr.left.name)
            result_reg = self.get_register()
            self.emit(f"    MOV {result_reg}, {reg}")
            if expr.op == '++': self.emit(f"    INC {reg}")
            elif expr.op == '--': self.emit(f"    DEC {reg}")
            else: raise SyntaxError(f"Unknown postfix operator '{expr.op}'")
            self._emit_local_store(expr.left.name, reg)
            self.free_register()
            return result_reg
        elif isinstance(expr, FuncCall):
            return self.generate_call(expr)
        else:
            raise RuntimeError(f"Unknown expression type: {type(expr)}")

    def generate_call(self, call: FuncCall) -> str:
        self.emit_comment(f"Call to {call.name}")
        for arg in reversed(call.args):
            arg_reg = self.generate_expression(arg)
            self.emit(f"    PUSH {arg_reg}")
            self.free_register()
        
        label = self.functions.get(call.name, {}).get('label') or self.builtin_functions.get(call.name)
        if not label:
            raise NameError(f"Undefined function '{call.name}'")
        
        self.emit(f"    CALL {label}")
        if call.args:
            self.emit(f"    ; Args consumed by callee")

        result_reg = self.get_register()
        self.emit(f"    MOV {result_reg}, R0")
        return result_reg

    def generate_builtins(self):
        self.assembly.append("; Built-in Function Implementations")
        self.emit_label("builtin_set_vmode")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    MOV VM, R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_set_layer")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    MOV VL, R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_set_pos")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    POP R2"); self.emit("    MOV VX, R2"); self.emit("    MOV VY, R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_write_screen")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    SWRITE R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_read_screen")
        self.emit("    SREAD R0"); self.emit("    RET")
        self.emit_label("builtin_scroll_x")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    SROLX R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_scroll_y")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    SROLY R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_set_pointers")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    POP R2")
        self.emit("    MOV P2, R2"); self.emit("    MOV P1, R1"); self.emit("    MOV P0, P2"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_write_text")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    POP R2"); self.emit("    TEXT R2, R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_set_font")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_sound_play")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    POP R2"); self.emit("    POP R3"); self.emit("    SPLAY R3, R2, R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_sound_stop")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    SPLAY R1, 0, 0"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_set_timer")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    POP R2"); self.emit("    POP R3"); self.emit("    POP R4"); self.emit("    MOV TT, R4"); self.emit("    MOV TM, R3"); self.emit("    MOV TS, R2"); self.emit("    MOV TC, R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_sti")
        self.emit("    STI"); self.emit("    RET")
        self.emit_label("builtin_cli")
        self.emit("    CLI"); self.emit("    RET")
        self.emit_label("builtin_iret")
        self.emit("    IRET"); self.emit("    RET")
        self.emit_label("builtin_random")
        self.emit("    RND R0"); self.emit("    RET")
        self.emit_label("builtin_random_range")
        self.emit("    POP P0"); self.emit("    POP R1"); self.emit("    POP R2"); self.emit("    RNDR R0, R2, R1"); self.emit("    PUSH P0"); self.emit("    RET")
        self.emit_label("builtin_halt")
        self.emit("    HLT"); self.emit("    RET")

    def get_string_label(self, value: str) -> str:
        if value not in self.strings:
            label = self.generate_label("str")
            self.strings[value] = label
            return label
        return self.strings[value]

    def emit(self, line: str):
        self.assembly.append(f"    {line}")

    def emit_comment(self, comment: str):
        self.assembly.append(f"; {comment}")

    def emit_label(self, label: str):
        self.assembly.append(f"{label}:")

    def generate_label(self, prefix: str) -> str:
        label = f"{prefix}_{self.label_counter}"
        self.label_counter += 1
        return label

    def get_register(self) -> str:
        reg = f"R{self.reg_counter % 10}"
        self.reg_counter += 1
        return reg

    def free_register(self):
        pass