; NoBASIC compiler output
; Generated for Nova-16
ORG 0x0200
MOV P7:, 0xFF
MOV :P7, 0xFF
MOV SP, P7
MOV FP, SP
MOV VX, 0
MOV VC, 15
TEXT STR0
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR1
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR2
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR1
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR3
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR1
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR4
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR1
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR5
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR1
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR6
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR1
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR7
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR1
ADD VY, 8
MOV VX, 0
MOV VC, 15
TEXT STR8
ADD VY, 8
HLT
STR0: DEFSTR "Aa Bb Cc Dd Ee Ff Gg Hh"
STR1: DEFSTR ""
STR2: DEFSTR "Ii Jj Kk Ll Mm Nn Oo Pp"
STR3: DEFSTR "Qq Rr Ss Tt Uu Vv Ww Xx"
STR4: DEFSTR "Yy Zz 1234567890"
STR5: DEFSTR "[]:'{}|<>?,./`~!@#$%^&*()_+"
STR6: DEFSTR "Cool cat"
STR7: DEFSTR "Owls hoot"
STR8: DEFSTR "The quick brown fox jumped over the lazy dog as a boxing wizard jabbed deftly."